// Auto-generated by csasn1 v0.1.0: InnerCancelErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerCancelErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerCancelErrorPDU obj = new InnerCancelErrorPDU();
        obj.encodeTest();
    }
}
