// Auto-generated by csasn1 v0.1.0 at 2026-07-29 05:47 UTC: InnerInt16U
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerInt16UTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerInt16U obj = new InnerInt16U(1);
        byte[] data = obj.encodeTest();
        InnerInt16U d = InnerInt16U.decode(data);
        assertEquals(obj, d);
    }
}
