// Auto-generated by csasn1 v0.1.0 at 2026-07-28 03:54 UTC: InnerDataDefinition
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerDataDefinitionTest {

    @Test
    public void testAlternativeerror() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "error";
        obj.error = new InnerServiceError();
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativearray() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "array";
        obj.array = new InnerDataDefinitionArray();
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativestructure() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "structure";
        obj.structure = new InnerDataDefinitionStructure();
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeBoolean() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "Boolean";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint8() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "int8";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint16() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "int16";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint32() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "int32";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint64() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "int64";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint8u() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "int8u";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint16u() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "int16u";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint32u() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "int32u";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint64u() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "int64u";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativefloat32() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "float32";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativefloat64() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "float64";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativebit_string() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "bit-string";
        obj.bit_string = 42;
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeoctet_string() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "octet-string";
        obj.octet_string = 42;
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativevisible_string() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "visible-string";
        obj.visible_string = 42;
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeunicode_string() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "unicode-string";
        obj.unicode_string = 42;
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeutc_time() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "utc-time";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativebinary_time() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "binary-time";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativequality() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "quality";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativedbpos() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "dbpos";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativetcmd() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "tcmd";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativecheck() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "check";
        // Object (ANY) — skip; no meaningful value
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj._choice, d._choice);
    }

}
