// Auto-generated by csasn1 v0.1.0: InnerAssociateNegotiateResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAssociateNegotiateResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAssociateNegotiateResponsePDU obj = new InnerAssociateNegotiateResponsePDU();
        obj.encodeTest();
    }
}
