// Auto-generated by csasn1 v0.1.0 at 2026-07-28 03:54 UTC: InnerGetDataSetDirectoryResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetDataSetDirectoryResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetDataSetDirectoryResponsePDU obj = new InnerGetDataSetDirectoryResponsePDU();
        obj.memberData = new InnerGetDataSetDirectoryResponsePDUMemberData();
        obj.memberData.value = java.util.Collections.singletonList(new InnerAnonymousGetDataSetDirectoryResponsePDUMemberData());
        obj.moreFollows = new InnerBoolean();
        byte[] data = obj.encodeTest();
        InnerGetDataSetDirectoryResponsePDU d = InnerGetDataSetDirectoryResponsePDU.decode(data);
        assertEquals(obj, d);
    }
}
