// Auto-generated by csasn1 v0.1.0 at 2026-07-28 03:54 UTC: InnerOperateRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerOperateRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerOperateRequestPDU obj = new InnerOperateRequestPDU();
        obj.reference = new InnerObjectReference();
        obj.ctlVal = new InnerData();
        obj.ctlVal._choice = "error";
        obj.ctlVal.error = new InnerServiceError();
        obj.origin = new InnerOriginator();
        obj.origin.orCat = 0;
        obj.ctlNum = new InnerInt8U();
        obj.t = new InnerTimeStamp();
        obj.test = new InnerBoolean();
        obj.check = new InnerCheck();
        byte[] data = obj.encodeTest();
        InnerOperateRequestPDU d = InnerOperateRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
