// Auto-generated by csasn1 v0.1.0: InnerApch
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerApchTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerApch obj = new InnerApch();
        obj.encodeTest();
    }
}
