// Auto-generated by csasn1 v0.1.0 at 2026-07-28 03:54 UTC: InnerAnonymousReportPDUEntryEntryData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousReportPDUEntryEntryDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousReportPDUEntryEntryData obj = new InnerAnonymousReportPDUEntryEntryData();
        obj.reference = new InnerObjectReference();
        obj.fc = new InnerFunctionalConstraint();
        obj.id = new InnerInt16U();
        obj.value = new InnerData();
        obj.value._choice = "error";
        obj.value.error = new InnerServiceError();
        obj.reason = new InnerReasonCode();
        byte[] data = obj.encodeTest();
        InnerAnonymousReportPDUEntryEntryData d = InnerAnonymousReportPDUEntryEntryData.decode(data);
        assertEquals(obj, d);
    }
}
