// Auto-generated by csasn1 v0.1.0: InnerGetLogStatusValuesResponsePDULog
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetLogStatusValuesResponsePDULogTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetLogStatusValuesResponsePDULog obj = new InnerGetLogStatusValuesResponsePDULog();
        obj._v.put("_", java.util.Collections.singletonList(new InnerAnonymousGetLogStatusValuesResponsePDULog()));
        byte[] data = obj.encodeTest();
        InnerGetLogStatusValuesResponsePDULog d = InnerGetLogStatusValuesResponsePDULog.decode(data);
        assertEquals(obj, d);
    }
}
