// Auto-generated by csasn1 v0.1.0 at 2026-07-30 09:33 UTC: InnerACSIClass
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerACSIClassTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerACSIClass obj = new InnerACSIClass(1);
        byte[] data = obj.encodeTest();
        InnerACSIClass d = InnerACSIClass.decode(data);
        assertEquals(obj, d);
    }
}
