// Auto-generated by csasn1 v0.1.0 at 2026-07-23 14:23 UTC: InnerAnonymousGetSGCBValuesResponsePDUSgscb
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetSGCBValuesResponsePDUSgscbTest {

    @Test
    public void testEncodeDecodeApererror() throws Exception {
        InnerAnonymousGetSGCBValuesResponsePDUSgscb obj = new InnerAnonymousGetSGCBValuesResponsePDUSgscb();
        obj._choice = "error";
        obj.error = new InnerServiceError();
        byte[] data = obj.encodeTest();
        InnerAnonymousGetSGCBValuesResponsePDUSgscb d = InnerAnonymousGetSGCBValuesResponsePDUSgscb.decode(data);
        assertEquals(obj, d);
    }

    @Test
    public void testEncodeDecodeApervalue() throws Exception {
        InnerAnonymousGetSGCBValuesResponsePDUSgscb obj = new InnerAnonymousGetSGCBValuesResponsePDUSgscb();
        obj._choice = "value";
        obj.value = new InnerSGCB();
        obj.value.tActEdt.value = new byte[8];
        byte[] data = obj.encodeTest();
        InnerAnonymousGetSGCBValuesResponsePDUSgscb d = InnerAnonymousGetSGCBValuesResponsePDUSgscb.decode(data);
        assertEquals(obj, d);
    }

}
