// Auto-generated by csasn1 v0.1.0: InnerGetSGCBValuesResponsePDUSgscb
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetSGCBValuesResponsePDUSgscbTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetSGCBValuesResponsePDUSgscb obj = new InnerGetSGCBValuesResponsePDUSgscb();
        obj._v.put("_", java.util.Collections.singletonList(new InnerAnonymousGetSGCBValuesResponsePDUSgscb()));
        byte[] data = obj.encodeTest();
        InnerGetSGCBValuesResponsePDUSgscb d = InnerGetSGCBValuesResponsePDUSgscb.decode(data);
        assertEquals(obj, d);
    }
}
