// Auto-generated by csasn1 v0.1.0: InnerGetAllDataValuesErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetAllDataValuesErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetAllDataValuesErrorPDU obj = new InnerGetAllDataValuesErrorPDU(1);
        byte[] data = obj.encodeTest();
        InnerGetAllDataValuesErrorPDU d = InnerGetAllDataValuesErrorPDU.decode(data);
        assertEquals(obj, d);
    }
}
