// Auto-generated by csasn1 v0.1.0: InnerGetSGCBValuesRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetSGCBValuesRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetSGCBValuesRequestPDU obj = new InnerGetSGCBValuesRequestPDU();
        obj.encodeTest();
    }
}
