// Auto-generated by csasn1 v0.1.0 at 2026-07-28 03:54 UTC: InnerGetSGCBValuesErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetSGCBValuesErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetSGCBValuesErrorPDU obj = new InnerGetSGCBValuesErrorPDU(1);
        byte[] data = obj.encodeTest();
        InnerGetSGCBValuesErrorPDU d = InnerGetSGCBValuesErrorPDU.decode(data);
        assertEquals(obj, d);
    }
}
