// Auto-generated by csasn1 v0.1.0: InnerGetURCBValuesErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetURCBValuesErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetURCBValuesErrorPDU obj = new InnerGetURCBValuesErrorPDU(1);
        byte[] data = obj.encodeTest();
        InnerGetURCBValuesErrorPDU d = InnerGetURCBValuesErrorPDU.decode(data);
        assertEquals(obj, d);
    }
}
