// Auto-generated by csasn1 v0.1.0 at 2026-07-28 04:52 UTC: InnerSetMSVCBValuesRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSetMSVCBValuesRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSetMSVCBValuesRequestPDU obj = new InnerSetMSVCBValuesRequestPDU();
        obj.msvcb = new InnerSetMSVCBValuesRequestPDUMsvcb();
        obj.msvcb.value = java.util.Collections.singletonList(new InnerAnonymousSetMSVCBValuesRequestPDUMsvcb());
        byte[] data = obj.encodeTest();
        InnerSetMSVCBValuesRequestPDU d = InnerSetMSVCBValuesRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
