// Auto-generated by csasn1 v0.1.0 at 2026-07-27 08:06 UTC: InnerGetDataDefinitionResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetDataDefinitionResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetDataDefinitionResponsePDU obj = new InnerGetDataDefinitionResponsePDU();
        obj.data = new InnerGetDataDefinitionResponsePDUData();
        obj.data.value = java.util.Collections.singletonList(new InnerAnonymousGetDataDefinitionResponsePDUData());
        obj.moreFollows = new InnerBoolean();
        byte[] data = obj.encodeTest();
        InnerGetDataDefinitionResponsePDU d = InnerGetDataDefinitionResponsePDU.decode(data);
        assertEquals(obj, d);
    }
}
