// Auto-generated by csasn1 v0.1.0 at 2026-07-27 08:06 UTC: InnerAnonymousGetDataDefinitionResponsePDUData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetDataDefinitionResponsePDUDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousGetDataDefinitionResponsePDUData obj = new InnerAnonymousGetDataDefinitionResponsePDUData();
        obj.cdcType = "xx";
        obj.definition = new InnerDataDefinition();
        obj.definition._choice = "error";
        obj.definition.error = new InnerServiceError();
        byte[] data = obj.encodeTest();
        InnerAnonymousGetDataDefinitionResponsePDUData d = InnerAnonymousGetDataDefinitionResponsePDUData.decode(data);
        assertEquals(obj, d);
    }
}
