// Auto-generated by csasn1 v0.1.0 at 2026-07-30 09:33 UTC: InnerSetFileResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSetFileResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSetFileResponsePDU obj = new InnerSetFileResponsePDU();
        byte[] data = obj.encodeTest();
        InnerSetFileResponsePDU d = InnerSetFileResponsePDU.decode(data);
        assertEquals(obj, d);
    }
}
