// Auto-generated by csasn1 v0.1.0: InnerAnonymousGetMSVCBValuesResponsePDUMsvcb
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetMSVCBValuesResponsePDUMsvcbTest {

    @Test
    public void testAlternativeerror() throws Exception {
        InnerAnonymousGetMSVCBValuesResponsePDUMsvcb obj = new InnerAnonymousGetMSVCBValuesResponsePDUMsvcb();
        obj._v.clear();
        obj._v.put("_choice", "error");
        obj._v.put("_", new InnerServiceError()._v);
        byte[] data = obj.encodeTest();
        InnerAnonymousGetMSVCBValuesResponsePDUMsvcb d = InnerAnonymousGetMSVCBValuesResponsePDUMsvcb.decode(data);
        assertEquals(obj._v.get("_choice"), d._v.get("_choice"));
    }

    @Test
    public void testAlternativevalue() throws Exception {
        InnerAnonymousGetMSVCBValuesResponsePDUMsvcb obj = new InnerAnonymousGetMSVCBValuesResponsePDUMsvcb();
        obj._v.clear();
        obj._v.put("_choice", "value");
        obj._v.put("_", new InnerMSVCB()._v);
        byte[] data = obj.encodeTest();
        InnerAnonymousGetMSVCBValuesResponsePDUMsvcb d = InnerAnonymousGetMSVCBValuesResponsePDUMsvcb.decode(data);
        assertEquals(obj._v.get("_choice"), d._v.get("_choice"));
    }

}
