// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: InnerGetDataDefinitionResponsePDUData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetDataDefinitionResponsePDUDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetDataDefinitionResponsePDUData obj = new InnerGetDataDefinitionResponsePDUData();
        obj._v.put("_", java.util.Collections.singletonList(new InnerAnonymousGetDataDefinitionResponsePDUData()));
        byte[] data = obj.encodeTest();
        InnerGetDataDefinitionResponsePDUData d = InnerGetDataDefinitionResponsePDUData.decode(data);
        assertEquals(obj, d);
    }
}
