// Auto-generated by csasn1 v0.1.0 at 2026-07-29 05:47 UTC: InnerGetFileDirectoryRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetFileDirectoryRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetFileDirectoryRequestPDU obj = new InnerGetFileDirectoryRequestPDU();
        obj.pathName = new DefaultInnerVisibleString();
        obj.startTime = new InnerTimeStamp();
        obj.stopTime = new InnerTimeStamp();
        obj.fileAfter = new DefaultInnerVisibleString();
        byte[] data = obj.encodeTest();
        InnerGetFileDirectoryRequestPDU d = InnerGetFileDirectoryRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
