// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: InnerAnonymousGetDataDirectoryResponsePDUDataAttribute
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetDataDirectoryResponsePDUDataAttributeTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousGetDataDirectoryResponsePDUDataAttribute obj = new InnerAnonymousGetDataDirectoryResponsePDUDataAttribute();
        obj.reference = new InnerSubReference();
        obj.reference.value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        obj.fc = new InnerFunctionalConstraint();
        obj.fc.value = "xx";
        byte[] data = obj.encodeTest();
        InnerAnonymousGetDataDirectoryResponsePDUDataAttribute d = InnerAnonymousGetDataDirectoryResponsePDUDataAttribute.decode(data);
        assertEquals(obj, d);
    }
}
