// Auto-generated by csasn1 v0.1.0 at 2026-07-23 14:23 UTC: InnerGetRpcInterfaceDirectoryRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetRpcInterfaceDirectoryRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetRpcInterfaceDirectoryRequestPDU obj = new InnerGetRpcInterfaceDirectoryRequestPDU();
        obj.referenceAfter = "xx";
        byte[] data = obj.encodeTest();
        InnerGetRpcInterfaceDirectoryRequestPDU d = InnerGetRpcInterfaceDirectoryRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
