// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: InnerGoCB
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGoCBTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGoCB obj = new InnerGoCB();
        obj.goEna = new InnerBoolean();
        obj.goID = "xx";
        obj.datSet = new InnerObjectReference();
        obj.datSet.value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        obj.confRev = new InnerInt32U();
        obj.ndsCom = new InnerBoolean();
        obj.dstAddress = new InnerPhyComAddr();
        obj.dstAddress.addr = new byte[6];
        byte[] data = obj.encodeTest();
        InnerGoCB d = InnerGoCB.decode(data);
        assertEquals(obj, d);
    }
}
