// Auto-generated by csasn1 v0.1.0 at 2026-07-29 05:47 UTC: InnerAddCause
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAddCauseTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAddCause obj = new InnerAddCause(1);
        byte[] data = obj.encodeTest();
        InnerAddCause d = InnerAddCause.decode(data);
        assertEquals(obj, d);
    }
}
