// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: InnerSetDataValuesResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSetDataValuesResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSetDataValuesResponsePDU obj = new InnerSetDataValuesResponsePDU();
        byte[] data = obj.encodeTest();
        InnerSetDataValuesResponsePDU d = InnerSetDataValuesResponsePDU.decode(data);
        assertEquals(obj, d);
    }
}
