// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: InnerAnonymousSetLCBValuesRequestPDULcb
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousSetLCBValuesRequestPDULcbTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousSetLCBValuesRequestPDULcb obj = new InnerAnonymousSetLCBValuesRequestPDULcb();
        obj.reference = new InnerObjectReference();
        obj.reference.value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        obj.logEna = new InnerBoolean();
        obj.datSet = new InnerObjectReference();
        obj.datSet.value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        obj.trgOps = new InnerTriggerConditions();
        obj.intgPd = new InnerInt32U();
        obj.logRef = new InnerObjectReference();
        obj.logRef.value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        obj.optFlds = new InnerLcbOptFlds();
        obj.bufTm = new InnerInt32U();
        byte[] data = obj.encodeTest();
        InnerAnonymousSetLCBValuesRequestPDULcb d = InnerAnonymousSetLCBValuesRequestPDULcb.decode(data);
        assertEquals(obj, d);
    }
}
