// Auto-generated by csasn1 v0.1.0: InnerGetLogStatusValuesResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetLogStatusValuesResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetLogStatusValuesResponsePDU obj = new InnerGetLogStatusValuesResponsePDU();
        obj.encodeTest();
    }
}
