// Auto-generated by csasn1 v0.1.0 at 2026-07-28 04:52 UTC: InnerAnonymousGetGoReferenceResponsePDUMemberData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetGoReferenceResponsePDUMemberDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousGetGoReferenceResponsePDUMemberData obj = new InnerAnonymousGetGoReferenceResponsePDUMemberData();
        obj.reference = new InnerObjectReference();
        obj.fc = new InnerFunctionalConstraint();
        byte[] data = obj.encodeTest();
        InnerAnonymousGetGoReferenceResponsePDUMemberData d = InnerAnonymousGetGoReferenceResponsePDUMemberData.decode(data);
        assertEquals(obj, d);
    }
}
