// Auto-generated by csasn1 v0.1.0: InnerGetMSVCBValuesErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetMSVCBValuesErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetMSVCBValuesErrorPDU obj = new InnerGetMSVCBValuesErrorPDU(1);
        byte[] data = obj.encodeTest();
        InnerGetMSVCBValuesErrorPDU d = InnerGetMSVCBValuesErrorPDU.decode(data);
        assertEquals(obj, d);
    }
}
