// Auto-generated by csasn1 v0.1.0 at 2026-07-28 09:11 UTC: InnerEntryTime
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerEntryTimeTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerEntryTime obj = new InnerEntryTime();
        byte[] data = obj.encodeTest();
        InnerEntryTime d = InnerEntryTime.decode(data);
        assertEquals(obj, d);
    }
}
