// Auto-generated by csasn1 v0.1.0 at 2026-07-27 08:06 UTC: InnerDeleteFileResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerDeleteFileResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerDeleteFileResponsePDU obj = new InnerDeleteFileResponsePDU();
        byte[] data = obj.encodeTest();
        InnerDeleteFileResponsePDU d = InnerDeleteFileResponsePDU.decode(data);
        assertEquals(obj, d);
    }
}
