// Auto-generated by csasn1 v0.1.0: InnerAnonymousCreateDataSetRequestPDUMemberData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousCreateDataSetRequestPDUMemberDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousCreateDataSetRequestPDUMemberData obj = new InnerAnonymousCreateDataSetRequestPDUMemberData();
        obj.encodeTest();
    }
}
