// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: InnerGetRpcInterfaceDefinitionResponsePDUMethod
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetRpcInterfaceDefinitionResponsePDUMethodTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetRpcInterfaceDefinitionResponsePDUMethod obj = new InnerGetRpcInterfaceDefinitionResponsePDUMethod();
        obj._v.put("_", java.util.Collections.singletonList(new InnerAnonymousGetRpcInterfaceDefinitionResponsePDUMethod()));
        byte[] data = obj.encodeTest();
        InnerGetRpcInterfaceDefinitionResponsePDUMethod d = InnerGetRpcInterfaceDefinitionResponsePDUMethod.decode(data);
        assertEquals(obj, d);
    }
}
