// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: InnerGetServerDirectoryResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetServerDirectoryResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetServerDirectoryResponsePDU obj = new InnerGetServerDirectoryResponsePDU();
        obj.encodeTest();
    }
}
