// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: InnerAnonymousGetGOOSEElementNumberRequestPDUMemberData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetGOOSEElementNumberRequestPDUMemberDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousGetGOOSEElementNumberRequestPDUMemberData obj = new InnerAnonymousGetGOOSEElementNumberRequestPDUMemberData();
        obj.reference = new InnerObjectReference();
        obj.reference.value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        obj.fc = new InnerFunctionalConstraint();
        obj.fc.value = "xx";
        byte[] data = obj.encodeTest();
        InnerAnonymousGetGOOSEElementNumberRequestPDUMemberData d = InnerAnonymousGetGOOSEElementNumberRequestPDUMemberData.decode(data);
        assertEquals(obj, d);
    }
}
