// Auto-generated by csasn1 v0.1.0 at 2026-07-28 04:52 UTC: InnerGetLCBValuesResponsePDULcb
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetLCBValuesResponsePDULcbTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetLCBValuesResponsePDULcb obj = new InnerGetLCBValuesResponsePDULcb();
        obj.value = new java.util.ArrayList<>();
        byte[] data = obj.encodeTest();
        InnerGetLCBValuesResponsePDULcb d = InnerGetLCBValuesResponsePDULcb.decode(data);
        assertEquals(obj, d);
    }
}
