// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: InnerDeleteDataSetRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerDeleteDataSetRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerDeleteDataSetRequestPDU obj = new InnerDeleteDataSetRequestPDU();
        obj.datasetReference = new InnerObjectReference();
        obj.datasetReference.value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        byte[] data = obj.encodeTest();
        InnerDeleteDataSetRequestPDU d = InnerDeleteDataSetRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
