// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: InnerGetDataSetValuesErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetDataSetValuesErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetDataSetValuesErrorPDU obj = new InnerGetDataSetValuesErrorPDU(1);
        byte[] data = obj.encodeTest();
        InnerGetDataSetValuesErrorPDU d = InnerGetDataSetValuesErrorPDU.decode(data);
        assertEquals(obj, d);
    }
}
