// Auto-generated by csasn1 v0.1.0: InnerGetLogicalNodeDirectoryRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetLogicalNodeDirectoryRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetLogicalNodeDirectoryRequestPDU obj = new InnerGetLogicalNodeDirectoryRequestPDU();
        obj.encodeTest();
    }
}
