// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: InnerDataDefinition
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerDataDefinitionTest {

    @Test
    public void testEncodeDecodeApererror() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "error";
        obj.error = new InnerServiceError();
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj, d);
    }

    @Test
    public void testEncodeDecodeAperarray() throws Exception {
        InnerDataDefinition obj = new InnerDataDefinition();
        obj._choice = "array";
        obj.array = new InnerDataDefinitionArray();
        byte[] data = obj.encodeTest();
        InnerDataDefinition d = InnerDataDefinition.decode(data);
        assertEquals(obj, d);
    }

}
