// Auto-generated by csasn1 v0.1.0: InnerGetFileDirectoryResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetFileDirectoryResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetFileDirectoryResponsePDU obj = new InnerGetFileDirectoryResponsePDU();
        obj.encodeTest();
    }
}
