// Auto-generated by csasn1 v0.1.0: InnerDeleteFileRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerDeleteFileRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerDeleteFileRequestPDU obj = new InnerDeleteFileRequestPDU();
        obj.encodeTest();
    }
}
