// Auto-generated by csasn1 v0.1.0 at 2026-07-27 08:06 UTC: InnerGetSGCBValuesRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetSGCBValuesRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetSGCBValuesRequestPDU obj = new InnerGetSGCBValuesRequestPDU();
        obj.sgcbReference = java.util.Collections.singletonList(new InnerObjectReference());
        byte[] data = obj.encodeTest();
        InnerGetSGCBValuesRequestPDU d = InnerGetSGCBValuesRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
