// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: InnerGetDataDirectoryResponsePDUDataAttribute
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetDataDirectoryResponsePDUDataAttributeTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetDataDirectoryResponsePDUDataAttribute obj = new InnerGetDataDirectoryResponsePDUDataAttribute();
        obj._v.put("_", java.util.Collections.singletonList(new InnerAnonymousGetDataDirectoryResponsePDUDataAttribute()));
        byte[] data = obj.encodeTest();
        InnerGetDataDirectoryResponsePDUDataAttribute d = InnerGetDataDirectoryResponsePDUDataAttribute.decode(data);
        assertEquals(obj, d);
    }
}
