// Auto-generated by csasn1 v0.1.0: InnerAnonymousSetDataValuesRequestPDUData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousSetDataValuesRequestPDUDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousSetDataValuesRequestPDUData obj = new InnerAnonymousSetDataValuesRequestPDUData();
        obj.encodeTest();
    }
}
