// Auto-generated by csasn1 v0.1.0 at 2026-07-28 09:11 UTC: InnerGetLCBValuesErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetLCBValuesErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetLCBValuesErrorPDU obj = new InnerGetLCBValuesErrorPDU(1);
        byte[] data = obj.encodeTest();
        InnerGetLCBValuesErrorPDU d = InnerGetLCBValuesErrorPDU.decode(data);
        assertEquals(obj, d);
    }
}
