// Auto-generated by csasn1 v0.1.0 at 2026-07-30 09:33 UTC: InnerSetDataValuesRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSetDataValuesRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSetDataValuesRequestPDU obj = new InnerSetDataValuesRequestPDU();
        obj.encodeTest();
    }
}
