// Auto-generated by csasn1 v0.1.0 at 2026-07-28 03:54 UTC: InnerGetURCBValuesRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetURCBValuesRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetURCBValuesRequestPDU obj = new InnerGetURCBValuesRequestPDU();
        obj.reference = java.util.Collections.singletonList(new InnerObjectReference());
        byte[] data = obj.encodeTest();
        InnerGetURCBValuesRequestPDU d = InnerGetURCBValuesRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
