// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: InnerPhyComAddr
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerPhyComAddrTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerPhyComAddr obj = new InnerPhyComAddr();
        obj.addr = new byte[6];
        obj.priority = new InnerInt8U();
        obj.vid = new InnerInt16U();
        obj.appid = new InnerInt16U();
        byte[] data = obj.encodeTest();
        InnerPhyComAddr d = InnerPhyComAddr.decode(data);
        assertEquals(obj, d);
    }
}
