// Auto-generated by csasn1 v0.1.0 at 2026-07-28 01:34 UTC: InnerAnonymousGetAllDataValuesResponsePDUData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetAllDataValuesResponsePDUDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousGetAllDataValuesResponsePDUData obj = new InnerAnonymousGetAllDataValuesResponsePDUData();
        obj.reference = new InnerSubReference();
        obj.value = new InnerData();
        obj.value._choice = "error";
        obj.value.error = new InnerServiceError();
        byte[] data = obj.encodeTest();
        InnerAnonymousGetAllDataValuesResponsePDUData d = InnerAnonymousGetAllDataValuesResponsePDUData.decode(data);
        assertEquals(obj, d);
    }
}
