// Auto-generated by csasn1 v0.1.0 at 2026-07-28 04:52 UTC: InnerCancelResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerCancelResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerCancelResponsePDU obj = new InnerCancelResponsePDU();
        obj.reference = new InnerObjectReference();
        obj.ctlVal = new InnerData();
        obj.ctlVal._choice = "error";
        obj.ctlVal.error = new InnerServiceError();
        obj.operTm = new InnerTimeStamp();
        obj.origin = new InnerOriginator();
        obj.origin.orCat = 0;
        obj.ctlNum = new InnerInt8U();
        obj.t = new InnerTimeStamp();
        obj.test = new InnerBoolean();
        byte[] data = obj.encodeTest();
        InnerCancelResponsePDU d = InnerCancelResponsePDU.decode(data);
        assertEquals(obj, d);
    }
}
