// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: InnerGetDataSetDirectoryResponsePDUMemberData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetDataSetDirectoryResponsePDUMemberDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetDataSetDirectoryResponsePDUMemberData obj = new InnerGetDataSetDirectoryResponsePDUMemberData();
        obj._v.put("_", java.util.Collections.singletonList(new InnerAnonymousGetDataSetDirectoryResponsePDUMemberData()));
        byte[] data = obj.encodeTest();
        InnerGetDataSetDirectoryResponsePDUMemberData d = InnerGetDataSetDirectoryResponsePDUMemberData.decode(data);
        assertEquals(obj, d);
    }
}
