// Auto-generated by csasn1 v0.1.0: InnerSetDataValuesErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSetDataValuesErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSetDataValuesErrorPDU obj = new InnerSetDataValuesErrorPDU();
        obj.encodeTest();
    }
}
