// Auto-generated by csasn1 v0.1.0 at 2026-07-28 09:11 UTC: InnerGetBRCBValuesRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetBRCBValuesRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetBRCBValuesRequestPDU obj = new InnerGetBRCBValuesRequestPDU();
        obj.reference = java.util.Collections.singletonList(new InnerObjectReference());
        byte[] data = obj.encodeTest();
        InnerGetBRCBValuesRequestPDU d = InnerGetBRCBValuesRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
