// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: InnerSetGoCBValuesRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSetGoCBValuesRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSetGoCBValuesRequestPDU obj = new InnerSetGoCBValuesRequestPDU();
        obj.gocb = new InnerSetGoCBValuesRequestPDUGocb();
        obj.gocb.value = java.util.Collections.singletonList(new InnerAnonymousSetGoCBValuesRequestPDUGocb());
        byte[] data = obj.encodeTest();
        InnerSetGoCBValuesRequestPDU d = InnerSetGoCBValuesRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
