// Auto-generated by csasn1 v0.1.0 at 2026-07-28 01:34 UTC: InnerURCB
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerURCBTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerURCB obj = new InnerURCB();
        obj.rptID = new DefaultInnerVisibleString();
        obj.rptEna = new InnerBoolean();
        obj.datSet = new InnerObjectReference();
        obj.confRev = new InnerInt32U();
        obj.optFlds = new InnerRcbOptFlds();
        obj.bufTm = new InnerInt32U();
        obj.sqNum = new InnerInt16U();
        obj.trgOps = new InnerTriggerConditions();
        obj.intgPd = new InnerInt32U();
        obj.gi = new InnerBoolean();
        obj.resv = new InnerBoolean();
        obj.owner = new DefaultInnerOctetString();
        byte[] data = obj.encodeTest();
        InnerURCB d = InnerURCB.decode(data);
        assertEquals(obj, d);
    }
}
