// Auto-generated by csasn1 v0.1.0 at 2026-07-28 01:34 UTC: InnerCreateDataSetRequestPDUMemberData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerCreateDataSetRequestPDUMemberDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerCreateDataSetRequestPDUMemberData obj = new InnerCreateDataSetRequestPDUMemberData();
        obj.value = new java.util.ArrayList<>();
        byte[] data = obj.encodeTest();
        InnerCreateDataSetRequestPDUMemberData d = InnerCreateDataSetRequestPDUMemberData.decode(data);
        assertEquals(obj, d);
    }
}
