// Auto-generated by csasn1 v0.1.0 at 2026-07-27 08:06 UTC: InnerAnonymousGetGoCbValuesResponsePDUGocb
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetGoCbValuesResponsePDUGocbTest {

    @Test
    public void testAlternativeerror() throws Exception {
        InnerAnonymousGetGoCbValuesResponsePDUGocb obj = new InnerAnonymousGetGoCbValuesResponsePDUGocb();
        obj._choice = "error";
        obj.error = new InnerServiceError();
        byte[] data = obj.encodeTest();
        InnerAnonymousGetGoCbValuesResponsePDUGocb d = InnerAnonymousGetGoCbValuesResponsePDUGocb.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativevalue() throws Exception {
        InnerAnonymousGetGoCbValuesResponsePDUGocb obj = new InnerAnonymousGetGoCbValuesResponsePDUGocb();
        obj._choice = "value";
        obj.value = new InnerGoCB();
        byte[] data = obj.encodeTest();
        InnerAnonymousGetGoCbValuesResponsePDUGocb d = InnerAnonymousGetGoCbValuesResponsePDUGocb.decode(data);
        assertEquals(obj._choice, d._choice);
    }

}
