// Auto-generated by csasn1 v0.1.0 at 2026-07-23 14:23 UTC: InnerGetDataValuesRequestPDUData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetDataValuesRequestPDUDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetDataValuesRequestPDUData obj = new InnerGetDataValuesRequestPDUData();
        obj.value = new java.util.ArrayList<>();
        byte[] data = obj.encodeTest();
        InnerGetDataValuesRequestPDUData d = InnerGetDataValuesRequestPDUData.decode(data);
        assertEquals(obj, d);
    }
}
