// Auto-generated by csasn1 v0.1.0 at 2026-07-30 09:33 UTC: InnerSetMSVCBValuesErrorPDUResult
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSetMSVCBValuesErrorPDUResultTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSetMSVCBValuesErrorPDUResult obj = new InnerSetMSVCBValuesErrorPDUResult();
        obj._v.put("_", java.util.Collections.singletonList(new InnerAnonymousSetMSVCBValuesErrorPDUResult()));
        byte[] data = obj.encodeTest();
        InnerSetMSVCBValuesErrorPDUResult d = InnerSetMSVCBValuesErrorPDUResult.decode(data);
        assertEquals(obj, d);
    }
}
