// Auto-generated by csasn1 v0.1.0: InnerAssociateErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAssociateErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAssociateErrorPDU obj = new InnerAssociateErrorPDU(1);
        byte[] data = obj.encodeTest();
        InnerAssociateErrorPDU d = InnerAssociateErrorPDU.decode(data);
        assertEquals(obj, d);
    }
}
