// Auto-generated by csasn1 v0.1.0: InnerGetGoCbValuesErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetGoCbValuesErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetGoCbValuesErrorPDU obj = new InnerGetGoCbValuesErrorPDU(1);
        byte[] data = obj.encodeTest();
        InnerGetGoCbValuesErrorPDU d = InnerGetGoCbValuesErrorPDU.decode(data);
        assertEquals(obj, d);
    }
}
