// Auto-generated by csasn1 v0.1.0 at 2026-07-28 09:11 UTC: InnerAnonymousGetLogStatusValuesResponsePDULogValue
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetLogStatusValuesResponsePDULogValueTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousGetLogStatusValuesResponsePDULogValue obj = new InnerAnonymousGetLogStatusValuesResponsePDULogValue();
        obj.oldEntrTm = new InnerEntryTime();
        obj.newEntrTm = new InnerEntryTime();
        obj.oldEntr = new InnerEntryID();
        obj.newEntr = new InnerEntryID();
        byte[] data = obj.encodeTest();
        InnerAnonymousGetLogStatusValuesResponsePDULogValue d = InnerAnonymousGetLogStatusValuesResponsePDULogValue.decode(data);
        assertEquals(obj, d);
    }
}
