// Auto-generated by csasn1 v0.1.0 at 2026-07-28 01:34 UTC: InnerGetRpcMethodDirectoryRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetRpcMethodDirectoryRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetRpcMethodDirectoryRequestPDU obj = new InnerGetRpcMethodDirectoryRequestPDU();
        obj._interface = new DefaultInnerVisibleString();
        obj.referenceAfter = new DefaultInnerVisibleString();
        byte[] data = obj.encodeTest();
        InnerGetRpcMethodDirectoryRequestPDU d = InnerGetRpcMethodDirectoryRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
