// Auto-generated by csasn1 v0.1.0 at 2026-07-27 08:06 UTC: InnerSelectActiveSGResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSelectActiveSGResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSelectActiveSGResponsePDU obj = new InnerSelectActiveSGResponsePDU();
        byte[] data = obj.encodeTest();
        InnerSelectActiveSGResponsePDU d = InnerSelectActiveSGResponsePDU.decode(data);
        assertEquals(obj, d);
    }
}
