// Auto-generated by csasn1 v0.1.0 at 2026-07-23 14:23 UTC: InnerSetLCBValuesRequestPDULcb
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSetLCBValuesRequestPDULcbTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSetLCBValuesRequestPDULcb obj = new InnerSetLCBValuesRequestPDULcb();
        obj.value = new java.util.ArrayList<>();
        byte[] data = obj.encodeTest();
        InnerSetLCBValuesRequestPDULcb d = InnerSetLCBValuesRequestPDULcb.decode(data);
        assertEquals(obj, d);
    }
}
