// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: InnerFloat64
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerFloat64Test {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerFloat64 obj = new InnerFloat64();
        obj.value = new byte[8];
        byte[] data = obj.encodeTest();
        InnerFloat64 d = InnerFloat64.decode(data);
        assertEquals(obj, d);
    }
}
