// Auto-generated by csasn1 v0.1.0: InnerAnonymousGetAllDataDefinitionResponsePDUData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetAllDataDefinitionResponsePDUDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousGetAllDataDefinitionResponsePDUData obj = new InnerAnonymousGetAllDataDefinitionResponsePDUData();
        obj.encodeTest();
    }
}
