// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: InnerAnonymousGetMSVCBValuesResponsePDUMsvcb
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetMSVCBValuesResponsePDUMsvcbTest {

    @Test
    public void testEncodeDecodeApererror() throws Exception {
        InnerAnonymousGetMSVCBValuesResponsePDUMsvcb obj = new InnerAnonymousGetMSVCBValuesResponsePDUMsvcb();
        obj._choice = "error";
        obj.error = new InnerServiceError();
        byte[] data = obj.encodeTest();
        InnerAnonymousGetMSVCBValuesResponsePDUMsvcb d = InnerAnonymousGetMSVCBValuesResponsePDUMsvcb.decode(data);
        assertEquals(obj, d);
    }

    @Test
    public void testEncodeDecodeApervalue() throws Exception {
        InnerAnonymousGetMSVCBValuesResponsePDUMsvcb obj = new InnerAnonymousGetMSVCBValuesResponsePDUMsvcb();
        obj._choice = "value";
        obj.value = new InnerMSVCB();
        obj.value.msvID = "xx";
        obj.value.datSet.value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        byte[] data = obj.encodeTest();
        InnerAnonymousGetMSVCBValuesResponsePDUMsvcb d = InnerAnonymousGetMSVCBValuesResponsePDUMsvcb.decode(data);
        assertEquals(obj, d);
    }

}
