// Auto-generated by csasn1 v0.1.0: InnerAnonymousGetRpcInterfaceDefinitionResponsePDUMethod
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetRpcInterfaceDefinitionResponsePDUMethodTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousGetRpcInterfaceDefinitionResponsePDUMethod obj = new InnerAnonymousGetRpcInterfaceDefinitionResponsePDUMethod();
        obj.encodeTest();
    }
}
