// Auto-generated by csasn1 v0.1.0 at 2026-07-28 01:34 UTC: InnerGetBRCBValuesErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetBRCBValuesErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetBRCBValuesErrorPDU obj = new InnerGetBRCBValuesErrorPDU(1);
        byte[] data = obj.encodeTest();
        InnerGetBRCBValuesErrorPDU d = InnerGetBRCBValuesErrorPDU.decode(data);
        assertEquals(obj, d);
    }
}
