// Auto-generated by csasn1 v0.1.0 at 2026-07-29 05:47 UTC: InnerSelectEditSGRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSelectEditSGRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSelectEditSGRequestPDU obj = new InnerSelectEditSGRequestPDU();
        obj.sgcbReference = new InnerObjectReference();
        obj.settingGroupNumber = new InnerInt8U();
        byte[] data = obj.encodeTest();
        InnerSelectEditSGRequestPDU d = InnerSelectEditSGRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
