// Auto-generated by csasn1 v0.1.0 at 2026-07-28 03:54 UTC: InnerAnonymousLogEntryEntryData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousLogEntryEntryDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousLogEntryEntryData obj = new InnerAnonymousLogEntryEntryData();
        obj.reference = new InnerObjectReference();
        obj.fc = new InnerFunctionalConstraint();
        obj.value = new InnerData();
        obj.value._choice = "error";
        obj.value.error = new InnerServiceError();
        obj.reason = new InnerReasonCode();
        byte[] data = obj.encodeTest();
        InnerAnonymousLogEntryEntryData d = InnerAnonymousLogEntryEntryData.decode(data);
        assertEquals(obj, d);
    }
}
