// Auto-generated by csasn1 v0.1.0 at 2026-07-30 09:33 UTC: InnerGetGOOSEElementNumberResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetGOOSEElementNumberResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetGOOSEElementNumberResponsePDU obj = new InnerGetGOOSEElementNumberResponsePDU();
        obj.encodeTest();
    }
}
