// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: InnerAssociateNegotiateRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAssociateNegotiateRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAssociateNegotiateRequestPDU obj = new InnerAssociateNegotiateRequestPDU();
        obj.encodeTest();
    }
}
