// Auto-generated by csasn1 v0.1.0: InnerQueryLogByTimeResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerQueryLogByTimeResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerQueryLogByTimeResponsePDU obj = new InnerQueryLogByTimeResponsePDU();
        obj.encodeTest();
    }
}
