// Auto-generated by csasn1 v0.1.0 at 2026-07-29 05:47 UTC: InnerSelectEditSGErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSelectEditSGErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSelectEditSGErrorPDU obj = new InnerSelectEditSGErrorPDU(1);
        byte[] data = obj.encodeTest();
        InnerSelectEditSGErrorPDU d = InnerSelectEditSGErrorPDU.decode(data);
        assertEquals(obj, d);
    }
}
