// Auto-generated by csasn1 v0.1.0 at 2026-07-28 04:52 UTC: InnerGetFileDirectoryErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetFileDirectoryErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetFileDirectoryErrorPDU obj = new InnerGetFileDirectoryErrorPDU(1);
        byte[] data = obj.encodeTest();
        InnerGetFileDirectoryErrorPDU d = InnerGetFileDirectoryErrorPDU.decode(data);
        assertEquals(obj, d);
    }
}
