// Auto-generated by csasn1 v0.1.0: InnerAsdu
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAsduTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAsdu obj = new InnerAsdu();
        obj.encodeTest();
    }
}
