// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: InnerGetFileRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetFileRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetFileRequestPDU obj = new InnerGetFileRequestPDU();
        obj.filename = "xx";
        obj.startPosition = new InnerInt32U();
        byte[] data = obj.encodeTest();
        InnerGetFileRequestPDU d = InnerGetFileRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
