// Auto-generated by csasn1 v0.1.0: InnerGetAllCBValuesResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetAllCBValuesResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetAllCBValuesResponsePDU obj = new InnerGetAllCBValuesResponsePDU();
        obj.encodeTest();
    }
}
