// Auto-generated by csasn1 v0.1.0: InnerAnonymousSetURCBValuesRequestPDUUrcb
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousSetURCBValuesRequestPDUUrcbTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousSetURCBValuesRequestPDUUrcb obj = new InnerAnonymousSetURCBValuesRequestPDUUrcb();
        obj.encodeTest();
    }
}
