// Auto-generated by csasn1 v0.1.0: InnerGetDataDirectoryResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetDataDirectoryResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetDataDirectoryResponsePDU obj = new InnerGetDataDirectoryResponsePDU();
        obj.encodeTest();
    }
}
