// Auto-generated by csasn1 v0.1.0 at 2026-07-28 01:34 UTC: InnerGetGOOSEElementNumberResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetGOOSEElementNumberResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetGOOSEElementNumberResponsePDU obj = new InnerGetGOOSEElementNumberResponsePDU();
        obj.gocbReference = new InnerObjectReference();
        obj.confRev = new InnerInt32U();
        obj.datSet = new InnerObjectReference();
        obj.memberOffset = java.util.Collections.singletonList(new InnerInt16U());
        byte[] data = obj.encodeTest();
        InnerGetGOOSEElementNumberResponsePDU d = InnerGetGOOSEElementNumberResponsePDU.decode(data);
        assertEquals(obj, d);
    }
}
