// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: InnerSelectResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSelectResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSelectResponsePDU obj = new InnerSelectResponsePDU();
        obj.reference = new InnerObjectReference();
        obj.reference.value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        byte[] data = obj.encodeTest();
        InnerSelectResponsePDU d = InnerSelectResponsePDU.decode(data);
        assertEquals(obj, d);
    }
}
