// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: InnerAnonymousGetAllCBValuesResponsePDUCbValue
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetAllCBValuesResponsePDUCbValueTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousGetAllCBValuesResponsePDUCbValue obj = new InnerAnonymousGetAllCBValuesResponsePDUCbValue();
        obj.encodeTest();
    }
}
