// Auto-generated by csasn1 v0.1.0: InnerTimeActivatedOperateErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerTimeActivatedOperateErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerTimeActivatedOperateErrorPDU obj = new InnerTimeActivatedOperateErrorPDU();
        obj.encodeTest();
    }
}
