// Auto-generated by csasn1 v0.1.0 at 2026-07-30 09:33 UTC: InnerCheck
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerCheckTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerCheck obj = new InnerCheck(1);
        byte[] data = obj.encodeTest();
        InnerCheck d = InnerCheck.decode(data);
        assertEquals(obj, d);
    }
}
