// Auto-generated by csasn1 v0.1.0 at 2026-07-30 09:33 UTC: InnerAnonymousSetGoCBValuesErrorPDUResult
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousSetGoCBValuesErrorPDUResultTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousSetGoCBValuesErrorPDUResult obj = new InnerAnonymousSetGoCBValuesErrorPDUResult();
        obj.encodeTest();
    }
}
