// Auto-generated by csasn1 v0.1.0: InnerGetGoCbValuesRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetGoCbValuesRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetGoCbValuesRequestPDU obj = new InnerGetGoCbValuesRequestPDU();
        obj.encodeTest();
    }
}
