// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: InnerGetAllDataValuesRequestPDUReference
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetAllDataValuesRequestPDUReferenceTest {

    @Test
    public void testAlternativeldName() throws Exception {
        InnerGetAllDataValuesRequestPDUReference obj = new InnerGetAllDataValuesRequestPDUReference();
        obj._choice = "ldName";
        obj.ldName = new InnerObjectName();
        byte[] data = obj.encodeTest();
        InnerGetAllDataValuesRequestPDUReference d = InnerGetAllDataValuesRequestPDUReference.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativelnReference() throws Exception {
        InnerGetAllDataValuesRequestPDUReference obj = new InnerGetAllDataValuesRequestPDUReference();
        obj._choice = "lnReference";
        obj.lnReference = new InnerObjectReference();
        byte[] data = obj.encodeTest();
        InnerGetAllDataValuesRequestPDUReference d = InnerGetAllDataValuesRequestPDUReference.decode(data);
        assertEquals(obj._choice, d._choice);
    }

}
