// Auto-generated by csasn1 v0.1.0: InnerAnonymousDataDefinitionStructure
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousDataDefinitionStructureTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousDataDefinitionStructure obj = new InnerAnonymousDataDefinitionStructure();
        obj.encodeTest();
    }
}
