// Auto-generated by csasn1 v0.1.0 at 2026-07-28 09:11 UTC: InnerSubReference
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSubReferenceTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSubReference obj = new InnerSubReference();
        byte[] data = obj.encodeTest();
        InnerSubReference d = InnerSubReference.decode(data);
        assertEquals(obj, d);
    }
}
