// Auto-generated by csasn1 v0.1.0: InnerGetGOOSEElementNumberRequestPDUMemberData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetGOOSEElementNumberRequestPDUMemberDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetGOOSEElementNumberRequestPDUMemberData obj = new InnerGetGOOSEElementNumberRequestPDUMemberData();
        obj._v.put("_", java.util.Collections.singletonList(new InnerAnonymousGetGOOSEElementNumberRequestPDUMemberData()));
        byte[] data = obj.encodeTest();
        InnerGetGOOSEElementNumberRequestPDUMemberData d = InnerGetGOOSEElementNumberRequestPDUMemberData.decode(data);
        assertEquals(obj, d);
    }
}
