// Auto-generated by csasn1 v0.1.0: InnerGetGoReferenceRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetGoReferenceRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetGoReferenceRequestPDU obj = new InnerGetGoReferenceRequestPDU();
        obj.encodeTest();
    }
}
