// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: InnerData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerDataTest {

    @Test
    public void testAlternativeerror() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "error";
        obj.error = new InnerServiceError();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativearray() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "array";
        obj.array = new java.util.ArrayList<>();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativestructure() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "structure";
        obj.structure = new java.util.ArrayList<>();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeBoolean() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "Boolean";
        obj.Boolean = new InnerBoolean();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint8() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "int8";
        obj.int8 = new InnerInt8();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint16() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "int16";
        obj.int16 = new InnerInt16();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint32() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "int32";
        obj.int32 = new InnerInt32();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint64() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "int64";
        obj.int64 = new InnerInt64();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint8u() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "int8u";
        obj.int8u = new InnerInt8U();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint16u() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "int16u";
        obj.int16u = new InnerInt16U();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint32u() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "int32u";
        obj.int32u = new InnerInt32U();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeint64u() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "int64u";
        obj.int64u = new InnerInt64U();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativefloat32() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "float32";
        obj.float32 = new InnerFloat32();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativefloat64() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "float64";
        obj.float64 = new InnerFloat64();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativebit_string() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "bit-string";
        obj.bit_string = new byte[]{(byte)0xAA, (byte)0xBB};
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeoctet_string() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "octet-string";
        obj.octet_string = new byte[]{(byte)0xAA, (byte)0xBB};
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativevisible_string() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "visible-string";
        obj.visible_string = "test-value";
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeunicode_string() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "unicode-string";
        obj.unicode_string = "test-value";
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativeutc_time() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "utc-time";
        obj.utc_time = new InnerUtcTime();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativebinary_time() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "binary-time";
        obj.binary_time = new InnerBinaryTime();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativequality() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "quality";
        obj.quality = new InnerQuality();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativedbpos() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "dbpos";
        obj.dbpos = new InnerDbpos();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativetcmd() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "tcmd";
        obj.tcmd = new InnerTcmd();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

    @Test
    public void testAlternativecheck() throws Exception {
        InnerData obj = new InnerData();
        obj._choice = "check";
        obj.check = new InnerCheck();
        byte[] data = obj.encodeTest();
        InnerData d = InnerData.decode(data);
        assertEquals(obj._choice, d._choice);
    }

}
