// Auto-generated by csasn1 v0.1.0: InnerPhyComAddr
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerPhyComAddrTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerPhyComAddr obj = new InnerPhyComAddr();
        obj.encodeTest();
    }
}
