// Auto-generated by csasn1 v0.1.0: InnerRpcCallRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerRpcCallRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerRpcCallRequestPDU obj = new InnerRpcCallRequestPDU();
        obj.encodeTest();
    }
}
