// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: InnerGetGOOSEElementNumberRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetGOOSEElementNumberRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetGOOSEElementNumberRequestPDU obj = new InnerGetGOOSEElementNumberRequestPDU();
        obj.gocbReference = new InnerObjectReference();
        obj.gocbReference.value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        obj.memberData = new InnerGetGOOSEElementNumberRequestPDUMemberData();
        obj.memberData.value = java.util.Collections.singletonList(new InnerAnonymousGetGOOSEElementNumberRequestPDUMemberData());
        byte[] data = obj.encodeTest();
        InnerGetGOOSEElementNumberRequestPDU d = InnerGetGOOSEElementNumberRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
