// Auto-generated by csasn1 v0.1.0 at 2026-07-28 09:11 UTC: InnerGetLCBValuesResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetLCBValuesResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetLCBValuesResponsePDU obj = new InnerGetLCBValuesResponsePDU();
        obj.lcb = new InnerGetLCBValuesResponsePDULcb();
        obj.lcb.value = java.util.Collections.singletonList(new InnerAnonymousGetLCBValuesResponsePDULcb());
        obj.moreFollows = new InnerBoolean();
        byte[] data = obj.encodeTest();
        InnerGetLCBValuesResponsePDU d = InnerGetLCBValuesResponsePDU.decode(data);
        assertEquals(obj, d);
    }
}
