// Auto-generated by csasn1 v0.1.0: InnerGetDataDirectoryErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetDataDirectoryErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetDataDirectoryErrorPDU obj = new InnerGetDataDirectoryErrorPDU(1);
        byte[] data = obj.encodeTest();
        InnerGetDataDirectoryErrorPDU d = InnerGetDataDirectoryErrorPDU.decode(data);
        assertEquals(obj, d);
    }
}
