// Auto-generated by csasn1 v0.1.0 at 2026-07-28 09:11 UTC: InnerGetRpcInterfaceDefinitionErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetRpcInterfaceDefinitionErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetRpcInterfaceDefinitionErrorPDU obj = new InnerGetRpcInterfaceDefinitionErrorPDU(1);
        byte[] data = obj.encodeTest();
        InnerGetRpcInterfaceDefinitionErrorPDU d = InnerGetRpcInterfaceDefinitionErrorPDU.decode(data);
        assertEquals(obj, d);
    }
}
