// Auto-generated by csasn1 v0.1.0: InnerGetAllDataValuesRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetAllDataValuesRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetAllDataValuesRequestPDU obj = new InnerGetAllDataValuesRequestPDU();
        obj.encodeTest();
    }
}
