// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: InnerCreateDataSetResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerCreateDataSetResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerCreateDataSetResponsePDU obj = new InnerCreateDataSetResponsePDU();
        byte[] data = obj.encodeTest();
        InnerCreateDataSetResponsePDU d = InnerCreateDataSetResponsePDU.decode(data);
        assertEquals(obj, d);
    }
}
