// Auto-generated by csasn1 v0.1.0: InnerSetLCBValuesErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSetLCBValuesErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSetLCBValuesErrorPDU obj = new InnerSetLCBValuesErrorPDU();
        obj.encodeTest();
    }
}
