// Auto-generated by csasn1 v0.1.0: InnerSendGOOSEMessagePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSendGOOSEMessagePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSendGOOSEMessagePDU obj = new InnerSendGOOSEMessagePDU();
        obj.encodeTest();
    }
}
