// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: InnerGetEditSGValueResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetEditSGValueResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetEditSGValueResponsePDU obj = new InnerGetEditSGValueResponsePDU();
        obj.value = java.util.Collections.singletonList(new InnerData());
        obj.moreFollows = new InnerBoolean();
        byte[] data = obj.encodeTest();
        InnerGetEditSGValueResponsePDU d = InnerGetEditSGValueResponsePDU.decode(data);
        assertEquals(obj, d);
    }
}
