// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: InnerMSVCB
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerMSVCBTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerMSVCB obj = new InnerMSVCB();
        obj.svEna = new InnerBoolean();
        obj.msvID = "xx";
        obj.datSet = new InnerObjectReference();
        obj.datSet.value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        obj.confRev = new InnerInt32U();
        obj.smpMod = new InnerSmpMod();
        obj.smpRate = new InnerInt16U();
        obj.optFlds = new InnerMsvcbOptFlds();
        obj.dstAddress = new InnerPhyComAddr();
        obj.dstAddress.addr = new byte[6];
        byte[] data = obj.encodeTest();
        InnerMSVCB d = InnerMSVCB.decode(data);
        assertEquals(obj, d);
    }
}
