// Auto-generated by csasn1 v0.1.0: InnerAnonymousGetLogStatusValuesResponsePDULog
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetLogStatusValuesResponsePDULogTest {

    @Test
    public void testAlternativeerror() throws Exception {
        InnerAnonymousGetLogStatusValuesResponsePDULog obj = new InnerAnonymousGetLogStatusValuesResponsePDULog();
        obj._v.clear();
        obj._v.put("_choice", "error");
        obj._v.put("_", new InnerServiceError()._v);
        byte[] data = obj.encodeTest();
        InnerAnonymousGetLogStatusValuesResponsePDULog d = InnerAnonymousGetLogStatusValuesResponsePDULog.decode(data);
        assertEquals(obj._v.get("_choice"), d._v.get("_choice"));
    }

    @Test
    public void testAlternativevalue() throws Exception {
        InnerAnonymousGetLogStatusValuesResponsePDULog obj = new InnerAnonymousGetLogStatusValuesResponsePDULog();
        obj._v.clear();
        obj._v.put("_choice", "value");
        obj._v.put("_", new InnerAnonymousGetLogStatusValuesResponsePDULogValue()._v);
        byte[] data = obj.encodeTest();
        InnerAnonymousGetLogStatusValuesResponsePDULog d = InnerAnonymousGetLogStatusValuesResponsePDULog.decode(data);
        assertEquals(obj._v.get("_choice"), d._v.get("_choice"));
    }

}
