// Auto-generated by csasn1 v0.1.0 at 2026-07-28 04:52 UTC: InnerSetEditSGValueErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSetEditSGValueErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSetEditSGValueErrorPDU obj = new InnerSetEditSGValueErrorPDU();
        obj.result = java.util.Collections.singletonList(new InnerServiceError());
        byte[] data = obj.encodeTest();
        InnerSetEditSGValueErrorPDU d = InnerSetEditSGValueErrorPDU.decode(data);
        assertEquals(obj, d);
    }
}
