// Auto-generated by csasn1 v0.1.0: InnerAbortRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAbortRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAbortRequestPDU obj = new InnerAbortRequestPDU();
        obj.encodeTest();
    }
}
