// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: InnerGetGoReferenceResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetGoReferenceResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetGoReferenceResponsePDU obj = new InnerGetGoReferenceResponsePDU();
        obj.gocbReference = new InnerObjectReference();
        obj.gocbReference.value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        obj.confRev = new InnerInt32U();
        obj.datSet = new InnerObjectReference();
        obj.datSet.value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        obj.memberData = new InnerGetGoReferenceResponsePDUMemberData();
        obj.memberData.value = java.util.Collections.singletonList(new InnerAnonymousGetGoReferenceResponsePDUMemberData());
        byte[] data = obj.encodeTest();
        InnerGetGoReferenceResponsePDU d = InnerGetGoReferenceResponsePDU.decode(data);
        assertEquals(obj, d);
    }
}
