// Auto-generated by csasn1 v0.1.0 at 2026-07-28 09:11 UTC: InnerGetAllCBValuesRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetAllCBValuesRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetAllCBValuesRequestPDU obj = new InnerGetAllCBValuesRequestPDU();
        obj.reference = new InnerGetAllCBValuesRequestPDUReference();
        obj.reference._choice = "ldName";
        obj.reference.ldName = new InnerObjectName();
        obj.acsiClass = new InnerACSIClass();
        obj.referenceAfter = new InnerObjectReference();
        byte[] data = obj.encodeTest();
        InnerGetAllCBValuesRequestPDU d = InnerGetAllCBValuesRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
