// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: InnerLogEntryEntryData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerLogEntryEntryDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerLogEntryEntryData obj = new InnerLogEntryEntryData();
        obj.value = new java.util.ArrayList<>();
        byte[] data = obj.encodeTest();
        InnerLogEntryEntryData d = InnerLogEntryEntryData.decode(data);
        assertEquals(obj, d);
    }
}
