// Auto-generated by csasn1 v0.1.0 at 2026-07-28 01:34 UTC: InnerGetGoReferenceResponsePDUMemberData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetGoReferenceResponsePDUMemberDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetGoReferenceResponsePDUMemberData obj = new InnerGetGoReferenceResponsePDUMemberData();
        obj.value = new java.util.ArrayList<>();
        byte[] data = obj.encodeTest();
        InnerGetGoReferenceResponsePDUMemberData d = InnerGetGoReferenceResponsePDUMemberData.decode(data);
        assertEquals(obj, d);
    }
}
