// Auto-generated by csasn1 v0.1.0 at 2026-07-28 01:34 UTC: InnerRpcCallRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerRpcCallRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerRpcCallRequestPDU obj = new InnerRpcCallRequestPDU();
        obj.method = new DefaultInnerVisibleString();
        obj.req = new InnerRpcCallRequestPDUReq();
        obj.req._choice = "reqData";
        obj.req.reqData = new InnerData();
        byte[] data = obj.encodeTest();
        InnerRpcCallRequestPDU d = InnerRpcCallRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
