// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: InnerReleaseResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerReleaseResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerReleaseResponsePDU obj = new InnerReleaseResponsePDU();
        obj.associationId = new byte[2];
        obj.serviceError = new InnerServiceError();
        byte[] data = obj.encodeTest();
        InnerReleaseResponsePDU d = InnerReleaseResponsePDU.decode(data);
        assertEquals(obj, d);
    }
}
