// Auto-generated by csasn1 v0.1.0: InnerGetLogicalNodeDirectoryRequestPDUReference
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetLogicalNodeDirectoryRequestPDUReferenceTest {

    @Test
    public void testAlternativeldName() throws Exception {
        InnerGetLogicalNodeDirectoryRequestPDUReference obj = new InnerGetLogicalNodeDirectoryRequestPDUReference();
        obj._v.clear();
        obj._v.put("_choice", "ldName");
        obj._v.put("ldName", new InnerObjectName()._v);
        byte[] data = obj.encodeTest();
        InnerGetLogicalNodeDirectoryRequestPDUReference d = InnerGetLogicalNodeDirectoryRequestPDUReference.decode(data);
        assertEquals(obj._v.get("_choice"), d._v.get("_choice"));
    }

    @Test
    public void testAlternativelnReference() throws Exception {
        InnerGetLogicalNodeDirectoryRequestPDUReference obj = new InnerGetLogicalNodeDirectoryRequestPDUReference();
        obj._v.clear();
        obj._v.put("_choice", "lnReference");
        obj._v.put("lnReference", new InnerObjectReference()._v);
        byte[] data = obj.encodeTest();
        InnerGetLogicalNodeDirectoryRequestPDUReference d = InnerGetLogicalNodeDirectoryRequestPDUReference.decode(data);
        assertEquals(obj._v.get("_choice"), d._v.get("_choice"));
    }

}
