// Auto-generated by csasn1 v0.1.0 at 2026-07-27 08:06 UTC: InnerTimeActivatedOperateTerminationRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerTimeActivatedOperateTerminationRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerTimeActivatedOperateTerminationRequestPDU obj = new InnerTimeActivatedOperateTerminationRequestPDU();
        obj.reference = new InnerObjectReference();
        obj.reference.value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        obj.ctlVal = new InnerData();
        obj.ctlVal._choice = "error";
        obj.ctlVal.error = new InnerServiceError();
        obj.operTm = new InnerTimeStamp();
        obj.operTm.value = new byte[8];
        obj.origin = new InnerOriginator();
        obj.origin.orCat = 0;
        obj.ctlNum = new InnerInt8U();
        obj.t = new InnerTimeStamp();
        obj.t.value = new byte[8];
        obj.test = new InnerBoolean();
        obj.check = new InnerCheck();
        obj.addCause = new InnerAddCause();
        byte[] data = obj.encodeTest();
        InnerTimeActivatedOperateTerminationRequestPDU d = InnerTimeActivatedOperateTerminationRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
