// Auto-generated by csasn1 v0.1.0: InnerRpcCallResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerRpcCallResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerRpcCallResponsePDU obj = new InnerRpcCallResponsePDU();
        obj.encodeTest();
    }
}
