// Auto-generated by csasn1 v0.1.0: InnerGetLCBValuesResponsePDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetLCBValuesResponsePDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetLCBValuesResponsePDU obj = new InnerGetLCBValuesResponsePDU();
        obj.encodeTest();
    }
}
