// Auto-generated by csasn1 v0.1.0 at 2026-07-29 05:47 UTC: InnerGetDataDirectoryRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetDataDirectoryRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetDataDirectoryRequestPDU obj = new InnerGetDataDirectoryRequestPDU();
        obj.dataReference = new InnerObjectReference();
        obj.referenceAfter = new InnerObjectReference();
        byte[] data = obj.encodeTest();
        InnerGetDataDirectoryRequestPDU d = InnerGetDataDirectoryRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
