// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: InnerAnonymousSetMSVCBValuesErrorPDUResult
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousSetMSVCBValuesErrorPDUResultTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousSetMSVCBValuesErrorPDUResult obj = new InnerAnonymousSetMSVCBValuesErrorPDUResult();
        obj.encodeTest();
    }
}
