// Auto-generated by csasn1 v0.1.0 at 2026-07-28 01:34 UTC: InnerSetEditSGValueRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSetEditSGValueRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSetEditSGValueRequestPDU obj = new InnerSetEditSGValueRequestPDU();
        obj.data = new InnerSetEditSGValueRequestPDUData();
        obj.data.value = java.util.Collections.singletonList(new InnerAnonymousSetEditSGValueRequestPDUData());
        byte[] data = obj.encodeTest();
        InnerSetEditSGValueRequestPDU d = InnerSetEditSGValueRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
