// Auto-generated by csasn1 v0.1.0: InnerGetDataValuesErrorPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetDataValuesErrorPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetDataValuesErrorPDU obj = new InnerGetDataValuesErrorPDU(1);
        byte[] data = obj.encodeTest();
        InnerGetDataValuesErrorPDU d = InnerGetDataValuesErrorPDU.decode(data);
        assertEquals(obj, d);
    }
}
