// Auto-generated by csasn1 v0.1.0 at 2026-07-28 01:34 UTC: InnerQueryLogByTimeRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerQueryLogByTimeRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerQueryLogByTimeRequestPDU obj = new InnerQueryLogByTimeRequestPDU();
        obj.logReference = new InnerObjectReference();
        obj.startTime = new InnerEntryTime();
        obj.stopTime = new InnerEntryTime();
        obj.entryAfter = new InnerEntryID();
        byte[] data = obj.encodeTest();
        InnerQueryLogByTimeRequestPDU d = InnerQueryLogByTimeRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
