// Auto-generated by csasn1 v0.1.0: InnerAnonymousGetLogStatusValuesResponsePDULogValue
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetLogStatusValuesResponsePDULogValueTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousGetLogStatusValuesResponsePDULogValue obj = new InnerAnonymousGetLogStatusValuesResponsePDULogValue();
        obj.encodeTest();
    }
}
