// Auto-generated by csasn1 v0.1.0 at 2026-07-28 01:34 UTC: InnerGetLogicalDeviceDirectoryRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetLogicalDeviceDirectoryRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetLogicalDeviceDirectoryRequestPDU obj = new InnerGetLogicalDeviceDirectoryRequestPDU();
        obj.ldName = new InnerObjectName();
        obj.referenceAfter = new InnerObjectReference();
        byte[] data = obj.encodeTest();
        InnerGetLogicalDeviceDirectoryRequestPDU d = InnerGetLogicalDeviceDirectoryRequestPDU.decode(data);
        assertEquals(obj, d);
    }
}
