// Auto-generated by csasn1 v0.1.0: InnerGetEditSGValueRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetEditSGValueRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetEditSGValueRequestPDU obj = new InnerGetEditSGValueRequestPDU();
        obj.encodeTest();
    }
}
