// Auto-generated by csasn1 v0.1.0 at 2026-07-27 08:06 UTC: InnerAnonymousCreateDataSetRequestPDUMemberData
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousCreateDataSetRequestPDUMemberDataTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousCreateDataSetRequestPDUMemberData obj = new InnerAnonymousCreateDataSetRequestPDUMemberData();
        obj.reference = new InnerObjectReference();
        obj.reference.value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        obj.fc = new InnerFunctionalConstraint();
        obj.fc.value = "xx";
        byte[] data = obj.encodeTest();
        InnerAnonymousCreateDataSetRequestPDUMemberData d = InnerAnonymousCreateDataSetRequestPDUMemberData.decode(data);
        assertEquals(obj, d);
    }
}
