// Auto-generated by csasn1 v0.1.0 at 2026-07-29 05:47 UTC: InnerAnonymousSetGoCBValuesRequestPDUGocb
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousSetGoCBValuesRequestPDUGocbTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerAnonymousSetGoCBValuesRequestPDUGocb obj = new InnerAnonymousSetGoCBValuesRequestPDUGocb();
        obj.reference = new InnerObjectReference();
        obj.goEna = new InnerBoolean();
        obj.goID = new DefaultInnerVisibleString();
        obj.datSet = new InnerObjectReference();
        byte[] data = obj.encodeTest();
        InnerAnonymousSetGoCBValuesRequestPDUGocb d = InnerAnonymousSetGoCBValuesRequestPDUGocb.decode(data);
        assertEquals(obj, d);
    }
}
