// Auto-generated by csasn1 v0.1.0: InnerGetURCBValuesRequestPDU
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetURCBValuesRequestPDUTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerGetURCBValuesRequestPDU obj = new InnerGetURCBValuesRequestPDU();
        obj.encodeTest();
    }
}
