// Auto-generated by csasn1 v0.1.0 at 2026-07-23 14:23 UTC: InnerGetAllCBValuesRequestPDUReference
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerGetAllCBValuesRequestPDUReferenceTest {

    @Test
    public void testEncodeDecodeAperldName() throws Exception {
        InnerGetAllCBValuesRequestPDUReference obj = new InnerGetAllCBValuesRequestPDUReference();
        obj._choice = "ldName";
        obj.ldName = new InnerObjectName();
        byte[] data = obj.encodeTest();
        InnerGetAllCBValuesRequestPDUReference d = InnerGetAllCBValuesRequestPDUReference.decode(data);
        assertEquals(obj, d);
    }

    @Test
    public void testEncodeDecodeAperlnReference() throws Exception {
        InnerGetAllCBValuesRequestPDUReference obj = new InnerGetAllCBValuesRequestPDUReference();
        obj._choice = "lnReference";
        obj.lnReference = new InnerObjectReference();
        byte[] data = obj.encodeTest();
        InnerGetAllCBValuesRequestPDUReference d = InnerGetAllCBValuesRequestPDUReference.decode(data);
        assertEquals(obj, d);
    }

}
