// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: InnerQuality
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerQualityTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerQuality obj = new InnerQuality(1);
        byte[] data = obj.encodeTest();
        InnerQuality d = InnerQuality.decode(data);
        assertEquals(obj, d);
    }
}
