// Auto-generated by csasn1 v0.1.0: InnerAnonymousGetRpcMethodDefinitionResponsePDUReference
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerAnonymousGetRpcMethodDefinitionResponsePDUReferenceTest {

    @Test
    public void testAlternativeerror() throws Exception {
        InnerAnonymousGetRpcMethodDefinitionResponsePDUReference obj = new InnerAnonymousGetRpcMethodDefinitionResponsePDUReference();
        obj._v.clear();
        obj._v.put("_choice", "error");
        obj._v.put("error", new InnerServiceError()._v);
        byte[] data = obj.encodeTest();
        InnerAnonymousGetRpcMethodDefinitionResponsePDUReference d = InnerAnonymousGetRpcMethodDefinitionResponsePDUReference.decode(data);
        assertEquals(obj._v.get("_choice"), d._v.get("_choice"));
    }

    @Test
    public void testAlternativemethod() throws Exception {
        InnerAnonymousGetRpcMethodDefinitionResponsePDUReference obj = new InnerAnonymousGetRpcMethodDefinitionResponsePDUReference();
        obj._v.clear();
        obj._v.put("_choice", "method");
        obj._v.put("method", new InnerAnonymousGetRpcMethodDefinitionResponsePDUReferenceMethod()._v);
        byte[] data = obj.encodeTest();
        InnerAnonymousGetRpcMethodDefinitionResponsePDUReference d = InnerAnonymousGetRpcMethodDefinitionResponsePDUReference.decode(data);
        assertEquals(obj._v.get("_choice"), d._v.get("_choice"));
    }

}
