// Auto-generated by csasn1 v0.1.0: InnerReportPDUEntry
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerReportPDUEntryTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerReportPDUEntry obj = new InnerReportPDUEntry();
        obj.encodeTest();
    }
}
