// Auto-generated by csasn1 v0.1.0 at 2026-07-28 03:54 UTC: InnerInt32
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerInt32Test {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerInt32 obj = new InnerInt32(1);
        byte[] data = obj.encodeTest();
        InnerInt32 d = InnerInt32.decode(data);
        assertEquals(obj, d);
    }
}
