// Auto-generated by csasn1 v0.1.0 at 2026-07-30 09:33 UTC: InnerSetGoCBValuesRequestPDUGocb
//

package com.ysh.jcms.data;

import org.junit.Test;
import static org.junit.Assert.*;

public class InnerSetGoCBValuesRequestPDUGocbTest {

    @Test
    public void testEncodeDecodeAper() throws Exception {
        InnerSetGoCBValuesRequestPDUGocb obj = new InnerSetGoCBValuesRequestPDUGocb();
        obj._v.put("_", java.util.Collections.singletonList(new InnerAnonymousSetGoCBValuesRequestPDUGocb()));
        byte[] data = obj.encodeTest();
        InnerSetGoCBValuesRequestPDUGocb d = InnerSetGoCBValuesRequestPDUGocb.decode(data);
        assertEquals(obj, d);
    }
}
