server:
  port: 8102
  sslPort: 9102
  testSclFiles:
    - config/sample-scd-full.scd
  sclFiles:
    - /Users/charles/Downloads/big.scd
    - C:\Users\17428\Downloads\longyang\big-file.scd

client:
  defaultIedName: C_B5041X
  defaultAccessPoint: S1
  defaultSecure: false
  connectTimeoutMs: 5000
  requestTimeoutMs: 5000

negotiate:
  apduSize: 65535
  asduSize: 65531
  protocolVersion: 1
  modelVersion: "1.0"

keepalive:
  idleTimeoutMs: 30000
  retryIntervalMs: 5000
  maxRetries: 4

security:
  enabled: false
  keystore:
    path: certs/server.pfx
    password: changeit
  truststore:
    path: certs/ca.cer
    password: changeit

protocol:
  pi: 1
  maxAsduSize: 65531
  defaultArrayCapacity: 256

file:
  rootPath: config/files

cli:
  tracePdu: false
  autoExec: ""
  showAutoExec: true
  showConnectHint: true
  apiEnabled: true
  apiPort: 7899

setting:
  numOfSG: 4
  sgDefaultEnabled: true
  sgDefaultName: SG1