// Auto-generated by csasn1 v0.1.0: Int64U
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * Int64U ::= INTEGER (0..18446744073709551615)
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerInt64U extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerInt64U() { _v.put("_", 1L); }
    @JsonCreator
    public static InnerInt64U fromJson(long v) { InnerInt64U r = new InnerInt64U(); r._v.put("_", v); return r; }
    public InnerInt64U(Long v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("Int64U", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("Int64U", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public static InnerInt64U decode(byte[] data) {
        try {
            String json = InnerNative.decode("Int64U", DEFAULT_ENCODING, data);
            InnerInt64U r = new InnerInt64U();
            r._v.put("_", MAPPER.readTree(json).asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
