// Auto-generated by csasn1 v0.1.0: SmpMod
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * SmpMod ::= INTEGER {
 *     samples-per-nominal-period    (0),
 *     samples-per-second            (1),
 *     seconds-per-sample            (2)
 * } (0..2)
 * }</pre>
 */
public class InnerSmpMod extends InnerBase {
    public InnerSmpMod() { _v.put("_", 1); }
    @JsonCreator
    public static InnerSmpMod fromJson(int v) { InnerSmpMod r = new InnerSmpMod(); r._v.put("_", v); return r; }
    public InnerSmpMod(Integer v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("SmpMod", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("SmpMod", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public static InnerSmpMod decode(byte[] data) {
        try {
            String json = InnerNative.decode("SmpMod", DEFAULT_ENCODING, data);
            InnerSmpMod r = new InnerSmpMod();
            com.fasterxml.jackson.databind.JsonNode _node = InnerBase.MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", _node.asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
