// Auto-generated by csasn1 v0.1.0: AnonymousSetLCBValuesRequestPDULcb
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * (inline type within SetLCBValues-RequestPDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerAnonymousSetLCBValuesRequestPDULcb extends InnerBase {
    public InnerAnonymousSetLCBValuesRequestPDULcb() {
        _v.put("reference", new InnerObjectReference()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "AnonymousSetLCBValuesRequestPDULcb"; }
    public static InnerAnonymousSetLCBValuesRequestPDULcb decode(byte[] data) {
        return InnerBase.decode(InnerAnonymousSetLCBValuesRequestPDULcb.class, "AnonymousSetLCBValuesRequestPDULcb", data);
    }
}
