// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: GetLogicalDeviceDirectoryRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetLogicalDeviceDirectory-RequestPDU ::= SEQUENCE {
 *     ldName            [0] IMPLICIT ObjectName OPTIONAL,
 *     referenceAfter    [1] IMPLICIT ObjectReference OPTIONAL
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetLogicalDeviceDirectoryRequestPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerObjectName ldName = new InnerObjectName();
    public InnerObjectReference referenceAfter = new InnerObjectReference();
    @com.fasterxml.jackson.annotation.JsonIgnore
    @lombok.EqualsAndHashCode.Exclude
    public transient java.util.Set<String> _set = new java.util.HashSet<>();
    public InnerGetLogicalDeviceDirectoryRequestPDU ldName(InnerObjectName value) {
        this.ldName = value;
        this._set.add("ldName");
        return this;
    }
    public InnerGetLogicalDeviceDirectoryRequestPDU referenceAfter(InnerObjectReference value) {
        this.referenceAfter = value;
        this._set.add("referenceAfter");
        return this;
    }
    public byte[] encode() {
        try {
            com.fasterxml.jackson.databind.node.ObjectNode _root = MAPPER.valueToTree(this);
            if (!_set.contains("ldName")) _root.remove("ldName");
            if (!_set.contains("referenceAfter")) _root.remove("referenceAfter");
            String _json = MAPPER.writeValueAsString(_root);
            return InnerNative.encode("GetLogicalDeviceDirectoryRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetLogicalDeviceDirectoryRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetLogicalDeviceDirectoryRequestPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetLogicalDeviceDirectoryRequestPDU", DEFAULT_ENCODING, data), InnerGetLogicalDeviceDirectoryRequestPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
