// Auto-generated by csasn1 v0.1.0: GetSGCBValuesResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetSGCBValues-ResponsePDU ::= SEQUENCE {
 *     sgscb          [0] IMPLICIT SEQUENCE OF CHOICE {
 *         error       [0] IMPLICIT ServiceError,
 *         value       [1] IMPLICIT SGCB
 *     },
 *     moreFollows    [1] IMPLICIT Boolean DEFAULT 1
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerGetSGCBValuesResponsePDU extends InnerBase {
    public InnerGetSGCBValuesResponsePDU() {
        _v.put("sgscb", new InnerGetSGCBValuesResponsePDUSgscb()._v);
        _v.put("moreFollows", new InnerBoolean()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "GetSGCBValuesResponsePDU"; }
    public static InnerGetSGCBValuesResponsePDU decode(byte[] data) {
        return InnerBase.decode(InnerGetSGCBValuesResponsePDU.class, "GetSGCBValuesResponsePDU", data);
    }
}
