// Auto-generated by csasn1 v0.1.0: LogEntryEntryData
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

public class InnerLogEntryEntryData extends InnerBase {
    public InnerLogEntryEntryData() { _v.put("_", new java.util.ArrayList<>()); }
    @JsonCreator
    public static InnerLogEntryEntryData fromJson(Object v) { InnerLogEntryEntryData r = new InnerLogEntryEntryData(); r._v.put("_", InnerBase.MAPPER.convertValue(v, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousLogEntryEntryData>>() {})); return r; }
    public InnerLogEntryEntryData(java.util.List<InnerAnonymousLogEntryEntryData> v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        try {
            return InnerNative.encode("LogEntryEntryData", DEFAULT_ENCODING, InnerBase.MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("LogEntryEntryData", DEFAULT_ENCODING, InnerBase.MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerLogEntryEntryData decode(byte[] data) {
        try {
            String json = InnerNative.decode("LogEntryEntryData", DEFAULT_ENCODING, data);
            InnerLogEntryEntryData r = new InnerLogEntryEntryData();
            com.fasterxml.jackson.databind.JsonNode _node = InnerBase.MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", InnerBase.MAPPER.convertValue(_node, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousLogEntryEntryData>>() {}));
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
