// Auto-generated by csasn1 v0.1.0: SetDataValuesErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * SetDataValues-ErrorPDU ::= SEQUENCE {
 *     result           [0] IMPLICIT SEQUENCE OF ServiceError
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerSetDataValuesErrorPDU extends InnerBase {
    public InnerSetDataValuesErrorPDU() {
        _v.put("result", new java.util.ArrayList<>());
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "SetDataValuesErrorPDU"; }
    public static InnerSetDataValuesErrorPDU decode(byte[] data) {
        return InnerBase.decode(InnerSetDataValuesErrorPDU.class, "SetDataValuesErrorPDU", data);
    }
}
