// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: AnonymousSetLCBValuesErrorPDUResult
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * (inline type within SetLCBValues-ErrorPDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerAnonymousSetLCBValuesErrorPDUResult extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerAnonymousSetLCBValuesErrorPDUResult() {
        _v.put("error", new InnerServiceError()._v);
        _v.put("logEna", new InnerServiceError()._v);
        _v.put("datSet", new InnerServiceError()._v);
        _v.put("trgOps", new InnerServiceError()._v);
        _v.put("intgPd", new InnerServiceError()._v);
        _v.put("logRef", new InnerServiceError()._v);
        _v.put("optFlds", new InnerServiceError()._v);
        _v.put("bufTm", new InnerServiceError()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    public byte[] encode() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            return InnerNative.encode("AnonymousSetLCBValuesErrorPDUResult", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encode AnonymousSetLCBValuesErrorPDUResult failed, json=" + _json, e);
        }
    }
    public byte[] encodeTest() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            System.err.println("JSON: " + _json);
            return new byte[0];
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerAnonymousSetLCBValuesErrorPDUResult decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("AnonymousSetLCBValuesErrorPDUResult", DEFAULT_ENCODING, data), InnerAnonymousSetLCBValuesErrorPDUResult.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
