// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: GetGoReferenceResponsePDUMemberData
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetGoReferenceResponsePDUMemberData extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetGoReferenceResponsePDUMemberData() { _v.put("_", new java.util.ArrayList<>()); }
    @JsonCreator
    public static InnerGetGoReferenceResponsePDUMemberData fromJson(Object v) { InnerGetGoReferenceResponsePDUMemberData r = new InnerGetGoReferenceResponsePDUMemberData(); r._v.put("_", MAPPER.convertValue(v, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetGoReferenceResponsePDUMemberData>>() {})); return r; }
    public InnerGetGoReferenceResponsePDUMemberData(java.util.List<InnerAnonymousGetGoReferenceResponsePDUMemberData> v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        try {
            return InnerNative.encode("GetGoReferenceResponsePDUMemberData", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("GetGoReferenceResponsePDUMemberData", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetGoReferenceResponsePDUMemberData decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetGoReferenceResponsePDUMemberData", DEFAULT_ENCODING, data);
            InnerGetGoReferenceResponsePDUMemberData r = new InnerGetGoReferenceResponsePDUMemberData();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            r._v.put("_", MAPPER.convertValue(_node.isArray() ? _node : _node.elements().next(), new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetGoReferenceResponsePDUMemberData>>() {}));
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
