// Auto-generated by csasn1 v0.1.0: Tcmd
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * Tcmd ::= BIT STRING (SIZE(2))
 * }</pre>
 */
public class InnerTcmd extends InnerBase {
    public InnerTcmd() { _v.put("_", "00"); }
    public InnerTcmd(int v) { this(); _v.put("_", InnerBase.bitStringHex(v, 2)); }
    @JsonValue
    @Override
    public Object toJsonValue() { return _v.get("_"); }
    @JsonCreator
    public static InnerTcmd fromJson(String hex) { return new InnerTcmd(hex); }
    public InnerTcmd(String hex) { this(); _v.put("_", hex); }
    public byte[] encode() {
        try {
            return InnerNative.encode("Tcmd", DEFAULT_ENCODING, InnerBase.MAPPER.writeValueAsString(_v.get("_")));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("Tcmd", DEFAULT_ENCODING, InnerBase.MAPPER.writeValueAsString(_v.get("_")));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerTcmd decode(byte[] data) {
        try {
            String json = InnerNative.decode("Tcmd", DEFAULT_ENCODING, data);
            InnerTcmd r = new InnerTcmd();
            com.fasterxml.jackson.databind.JsonNode _node = InnerBase.MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", _node.asText());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
