// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: GetAllDataValuesResponsePDUData
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetAllDataValuesResponsePDUData extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public java.util.List<InnerAnonymousGetAllDataValuesResponsePDUData> value = new java.util.ArrayList<>();
    public InnerGetAllDataValuesResponsePDUData() {}
    @JsonCreator
    public InnerGetAllDataValuesResponsePDUData(java.util.List<InnerAnonymousGetAllDataValuesResponsePDUData> value) { this.value = value; }
    public byte[] encode() {
        try {
            return InnerNative.encode("GetAllDataValuesResponsePDUData", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("GetAllDataValuesResponsePDUData", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetAllDataValuesResponsePDUData decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetAllDataValuesResponsePDUData", DEFAULT_ENCODING, data);
            InnerGetAllDataValuesResponsePDUData r = new InnerGetAllDataValuesResponsePDUData();
            r.value = MAPPER.convertValue(MAPPER.readTree(json).get("value"), new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetAllDataValuesResponsePDUData>>() {});
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
