// Auto-generated by csasn1 v0.1.0: GetAllDataValuesRequestPDUReference
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerGetAllDataValuesRequestPDUReference extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.MAPPER;
    public InnerGetAllDataValuesRequestPDUReference() {
        _v.put("_choice", "ldName");
        _v.put("_", new InnerObjectName()._v);
    }
    @JsonSetter("ldName")
    public void setLdName(Object v) {
        _v.put("_choice", "ldName");
        if (v instanceof java.util.Map) { _v.put("_", v); } else { java.util.LinkedHashMap<String, Object> _w = new java.util.LinkedHashMap<>(); _w.put("_", v); _v.put("_", _w); }
    }
    @JsonSetter("lnReference")
    public void setLnReference(Object v) {
        _v.put("_choice", "lnReference");
        if (v instanceof java.util.Map) { _v.put("_", v); } else { java.util.LinkedHashMap<String, Object> _w = new java.util.LinkedHashMap<>(); _w.put("_", v); _v.put("_", _w); }
    }
    public byte[] encode() {
        String _json = null;
        String _vStr = null;
        try {
            _vStr = MAPPER.writeValueAsString(_v);
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            return InnerNative.encode("GetAllDataValuesRequestPDUReference", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encode GetAllDataValuesRequestPDUReference failed, _v=" + _vStr + ", json=" + _json, e);
        }
    }
    public byte[] encodeTest() {
        String _json = null;
        String _vStr = null;
        try {
            _vStr = MAPPER.writeValueAsString(_v);
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            System.err.println("_v: " + _vStr);
            System.err.println("JSON: " + _json);
            return InnerNative.encode("GetAllDataValuesRequestPDUReference", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encodeTest GetAllDataValuesRequestPDUReference failed, _v=" + _vStr + ", json=" + _json, e);
        }
    }
    public static InnerGetAllDataValuesRequestPDUReference decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetAllDataValuesRequestPDUReference", DEFAULT_ENCODING, data), InnerGetAllDataValuesRequestPDUReference.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
