// Auto-generated by csasn1 v0.1.0: SetURCBValuesRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * SetURCBValues-RequestPDU ::= SEQUENCE {
 *     urcb            [0] IMPLICIT SEQUENCE OF SEQUENCE {
 *         reference   [0] IMPLICIT ObjectReference,
 *         rptID       [1] IMPLICIT VisibleString (SIZE (0..129)) OPTIONAL,
 *         rptEna      [2] IMPLICIT Boolean OPTIONAL,
 *         datSet      [3] IMPLICIT ObjectReference OPTIONAL,
 *         optFlds     [5] IMPLICIT RcbOptFlds OPTIONAL,
 *         bufTm       [6] IMPLICIT Int32U OPTIONAL,
 *         trgOps      [8] IMPLICIT TriggerConditions OPTIONAL,
 *         intgPd      [9] IMPLICIT Int32U OPTIONAL,
 *         gi          [10] IMPLICIT Boolean OPTIONAL,
 *         resv        [13] IMPLICIT Boolean OPTIONAL
 *     }
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerSetURCBValuesRequestPDU extends InnerBase {
    public InnerSetURCBValuesRequestPDU() {
        _v.put("urcb", new InnerSetURCBValuesRequestPDUUrcb()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "SetURCBValuesRequestPDU"; }
    public static InnerSetURCBValuesRequestPDU decode(byte[] data) {
        return InnerBase.decode(InnerSetURCBValuesRequestPDU.class, "SetURCBValuesRequestPDU", data);
    }
}
