// Auto-generated by csasn1 v0.1.0: SelectErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * Select-ErrorPDU ::= SEQUENCE {
 *     reference       [0] IMPLICIT ObjectReference
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerSelectErrorPDU extends InnerBase {
    public InnerSelectErrorPDU() {
        _v.put("reference", new InnerObjectReference()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "SelectErrorPDU"; }
    public static InnerSelectErrorPDU decode(byte[] data) {
        return InnerBase.decode(InnerSelectErrorPDU.class, "SelectErrorPDU", data);
    }
}
