// Auto-generated by csasn1 v0.1.0 at 2026-07-27 08:06 UTC: GetSGCBValuesResponsePDUSgscb
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetSGCBValuesResponsePDUSgscb extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public java.util.List<InnerAnonymousGetSGCBValuesResponsePDUSgscb> value = new java.util.ArrayList<>();
    public InnerGetSGCBValuesResponsePDUSgscb() {}
    @JsonCreator
    public InnerGetSGCBValuesResponsePDUSgscb(java.util.List<InnerAnonymousGetSGCBValuesResponsePDUSgscb> value) { this.value = value; }
    public byte[] encode() {
        try {
            return InnerNative.encode("GetSGCBValuesResponsePDUSgscb", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("GetSGCBValuesResponsePDUSgscb", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetSGCBValuesResponsePDUSgscb decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetSGCBValuesResponsePDUSgscb", DEFAULT_ENCODING, data);
            InnerGetSGCBValuesResponsePDUSgscb r = new InnerGetSGCBValuesResponsePDUSgscb();
            r.value = MAPPER.convertValue(MAPPER.readTree(json).get("value"), new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetSGCBValuesResponsePDUSgscb>>() {});
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
