// Auto-generated by csasn1 v0.1.0: RpcCallRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * RpcCall-RequestPDU ::= SEQUENCE {
 *     method          [0] IMPLICIT VisibleString,
 *     req             [1] IMPLICIT CHOICE {
 *         reqData     [0] IMPLICIT Data,
 *         callID      [1] IMPLICIT OCTET STRING
 *     }
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerRpcCallRequestPDU extends InnerBase {
    public InnerRpcCallRequestPDU() {
        _v.put("method", new DefaultInnerVisibleString("x"));
        _v.put("req", new InnerRpcCallRequestPDUReq()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "RpcCallRequestPDU"; }
    public static InnerRpcCallRequestPDU decode(byte[] data) {
        return InnerBase.decode(InnerRpcCallRequestPDU.class, "RpcCallRequestPDU", data);
    }
}
