// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: AnonymousGetBRCBValuesResponsePDUBrcb
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * (inline type within GetBRCBValues-ResponsePDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerAnonymousGetBRCBValuesResponsePDUBrcb extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerAnonymousGetBRCBValuesResponsePDUBrcb() {
        _v.put("_choice", "error");
        _v.put("error", new InnerServiceError()._v);
    }
    @JsonSetter("error")
    public void setError(Object v) {
        _v.put("_choice", "error");
        if (v instanceof java.util.Map) { _v.put("error", v); } else { java.util.LinkedHashMap<String, Object> _w = new java.util.LinkedHashMap<>(); _w.put("_", v); _v.put("error", _w); }
    }
    @JsonSetter("value")
    public void setValue(Object v) {
        _v.put("_choice", "value");
        if (v instanceof java.util.Map) { _v.put("value", v); } else { java.util.LinkedHashMap<String, Object> _w = new java.util.LinkedHashMap<>(); _w.put("_", v); _v.put("value", _w); }
    }
    public byte[] encode() {
        String _json = null;
        String _vStr = null;
        try {
            _vStr = MAPPER.writeValueAsString(_v);
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            return InnerNative.encode("AnonymousGetBRCBValuesResponsePDUBrcb", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encode AnonymousGetBRCBValuesResponsePDUBrcb failed, _v=" + _vStr + ", json=" + _json, e);
        }
    }
    public byte[] encodeTest() {
        String _json = null;
        String _vStr = null;
        try {
            _vStr = MAPPER.writeValueAsString(_v);
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            System.err.println("_v: " + _vStr);
            System.err.println("JSON: " + _json);
            return InnerNative.encode("AnonymousGetBRCBValuesResponsePDUBrcb", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encodeTest AnonymousGetBRCBValuesResponsePDUBrcb failed, _v=" + _vStr + ", json=" + _json, e);
        }
    }
    public static InnerAnonymousGetBRCBValuesResponsePDUBrcb decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("AnonymousGetBRCBValuesResponsePDUBrcb", DEFAULT_ENCODING, data), InnerAnonymousGetBRCBValuesResponsePDUBrcb.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        InnerAnonymousGetBRCBValuesResponsePDUBrcb that = (InnerAnonymousGetBRCBValuesResponsePDUBrcb) o;
        String _c = (String) _v.get("_choice");
        String _tc = (String) that._v.get("_choice");
        if (!java.util.Objects.equals(_c, _tc)) return false;
        if (_c == null) return false;
        if ("error".equals(_c)) return java.util.Objects.equals(_v.get("error"), that._v.get("error"));
        if ("value".equals(_c)) return java.util.Objects.equals(_v.get("value"), that._v.get("value"));
        return false;
    }
    @Override
    public int hashCode() {
        return java.util.Objects.hash(_v.get("_choice"));
    }
}
