// Auto-generated by csasn1 v0.1.0: DeleteFileRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * DeleteFile-RequestPDU ::= SEQUENCE {
 *     filename        [0] IMPLICIT VisibleString (SIZE (0..255))
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerDeleteFileRequestPDU extends InnerBase {
    public InnerDeleteFileRequestPDU() {
        _v.put("filename", new DefaultInnerVisibleString("x"));
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "DeleteFileRequestPDU"; }
    public static InnerDeleteFileRequestPDU decode(byte[] data) {
        return InnerBase.decode(InnerDeleteFileRequestPDU.class, "DeleteFileRequestPDU", data);
    }
}
