// Auto-generated by csasn1 v0.1.0: GetFileResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetFile-ResponsePDU ::= SEQUENCE {
 *     fileData        [0] IMPLICIT OCTET STRING,
 *     endOfFile       [1] IMPLICIT Boolean DEFAULT 0
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerGetFileResponsePDU extends InnerBase {
    public InnerGetFileResponsePDU() {
        _v.put("fileData", new DefaultInnerOctetString(new byte[]{ 1 }));
        _v.put("endOfFile", new InnerBoolean()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "GetFileResponsePDU"; }
    public static InnerGetFileResponsePDU decode(byte[] data) {
        return InnerBase.decode(InnerGetFileResponsePDU.class, "GetFileResponsePDU", data);
    }
}
