// Auto-generated by csasn1 v0.1.0 at 2026-07-28 04:52 UTC: SendGOOSEMessagePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * SendGOOSEMessage-PDU ::= SEQUENCE {
 *     goID            [0] IMPLICIT VisibleString (SIZE (0..129)),
 *     datSet          [1] IMPLICIT ObjectReference OPTIONAL,
 *     goRef           [2] IMPLICIT ObjectReference OPTIONAL,
 *     t               [3] IMPLICIT TimeStamp,
 *     stNum           [4] IMPLICIT Int32U,
 *     sqNum           [5] IMPLICIT Int32U,
 *     simulation      [6] IMPLICIT Boolean,
 *     confRev         [7] IMPLICIT Int32U,
 *     ndsCom          [8] IMPLICIT Boolean,
 *     data            [9] IMPLICIT SEQUENCE OF Data
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerSendGOOSEMessagePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public DefaultInnerVisibleString goID = new DefaultInnerVisibleString();
    public InnerObjectReference datSet = new InnerObjectReference();
    public InnerObjectReference goRef = new InnerObjectReference();
    public InnerTimeStamp t = new InnerTimeStamp();
    public InnerInt32U stNum = new InnerInt32U();
    public InnerInt32U sqNum = new InnerInt32U();
    public InnerBoolean simulation = new InnerBoolean();
    public InnerInt32U confRev = new InnerInt32U();
    public InnerBoolean ndsCom = new InnerBoolean();
    public java.util.List<InnerData> data = new java.util.ArrayList<>();
    @com.fasterxml.jackson.annotation.JsonIgnore
    @lombok.EqualsAndHashCode.Exclude
    public transient java.util.Set<String> _set = new java.util.HashSet<>();
    public InnerSendGOOSEMessagePDU datSet(InnerObjectReference value) {
        this.datSet = value;
        this._set.add("datSet");
        return this;
    }
    public InnerSendGOOSEMessagePDU goRef(InnerObjectReference value) {
        this.goRef = value;
        this._set.add("goRef");
        return this;
    }
    public byte[] encode() {
        try {
            com.fasterxml.jackson.databind.node.ObjectNode _root = MAPPER.valueToTree(this);
            if (!_set.contains("datSet")) _root.remove("datSet");
            if (!_set.contains("goRef")) _root.remove("goRef");
            String _json = MAPPER.writeValueAsString(_root);
            return InnerNative.encode("SendGOOSEMessagePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("SendGOOSEMessagePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerSendGOOSEMessagePDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("SendGOOSEMessagePDU", DEFAULT_ENCODING, data), InnerSendGOOSEMessagePDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
