// Auto-generated by csasn1 v0.1.0: SGCB
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * SGCB ::= SEQUENCE {
 *     numOfSG       [1] IMPLICIT Int8U,
 *     actSG         [2] IMPLICIT Int8U,
 *     editSG        [3] IMPLICIT Int8U,
 *     tActEdt       [4] IMPLICIT TimeStamp,
 *     resvTms       [5] IMPLICIT Int16U OPTIONAL
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerSGCB extends InnerBase {
    public InnerSGCB() {
        _v.put("numOfSG", new InnerInt8U()._v);
        _v.put("actSG", new InnerInt8U()._v);
        _v.put("editSG", new InnerInt8U()._v);
        _v.put("tActEdt", new InnerTimeStamp()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "SGCB"; }
    public static InnerSGCB decode(byte[] data) {
        return InnerBase.decode(InnerSGCB.class, "SGCB", data);
    }
}
