// Auto-generated by csasn1 v0.1.0: GetDataDirectoryRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetDataDirectory-RequestPDU ::= SEQUENCE {
 *     dataReference    [0] IMPLICIT ObjectReference,
 *     referenceAfter   [1] IMPLICIT ObjectReference OPTIONAL
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetDataDirectoryRequestPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetDataDirectoryRequestPDU() {
        _v.put("dataReference", new InnerObjectReference()._v);
        _v.put("referenceAfter", new InnerObjectReference()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    public byte[] encode() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            return InnerNative.encode("GetDataDirectoryRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encode GetDataDirectoryRequestPDU failed, json=" + _json, e);
        }
    }
    public byte[] encodeTest() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            System.err.println("JSON: " + _json);
            return new byte[0];
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetDataDirectoryRequestPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetDataDirectoryRequestPDU", DEFAULT_ENCODING, data), InnerGetDataDirectoryRequestPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
