// Auto-generated by csasn1 v0.1.0 at 2026-07-30 09:33 UTC: ConfirmEditSGValuesErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * ConfirmEditSGValues-ErrorPDU ::= ServiceError
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerConfirmEditSGValuesErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerConfirmEditSGValuesErrorPDU() { _v.put("_", 1); }
    @JsonCreator
    public static InnerConfirmEditSGValuesErrorPDU fromJson(int v) { InnerConfirmEditSGValuesErrorPDU r = new InnerConfirmEditSGValuesErrorPDU(); r._v.put("_", v); return r; }
    public InnerConfirmEditSGValuesErrorPDU(Integer v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("ConfirmEditSGValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("ConfirmEditSGValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public static InnerConfirmEditSGValuesErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("ConfirmEditSGValuesErrorPDU", DEFAULT_ENCODING, data);
            InnerConfirmEditSGValuesErrorPDU r = new InnerConfirmEditSGValuesErrorPDU();
            r._v.put("_", MAPPER.readTree(json).asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
