// Auto-generated by csasn1 v0.1.0: SetLCBValuesErrorPDUResult
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

public class InnerSetLCBValuesErrorPDUResult extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.MAPPER;
    public InnerSetLCBValuesErrorPDUResult() { _v.put("_", new java.util.ArrayList<>()); }
    @JsonCreator
    public static InnerSetLCBValuesErrorPDUResult fromJson(Object v) { InnerSetLCBValuesErrorPDUResult r = new InnerSetLCBValuesErrorPDUResult(); r._v.put("_", MAPPER.convertValue(v, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousSetLCBValuesErrorPDUResult>>() {})); return r; }
    public InnerSetLCBValuesErrorPDUResult(java.util.List<InnerAnonymousSetLCBValuesErrorPDUResult> v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        try {
            return InnerNative.encode("SetLCBValuesErrorPDUResult", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("SetLCBValuesErrorPDUResult", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerSetLCBValuesErrorPDUResult decode(byte[] data) {
        try {
            String json = InnerNative.decode("SetLCBValuesErrorPDUResult", DEFAULT_ENCODING, data);
            InnerSetLCBValuesErrorPDUResult r = new InnerSetLCBValuesErrorPDUResult();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", MAPPER.convertValue(_node, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousSetLCBValuesErrorPDUResult>>() {}));
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
