// Auto-generated by csasn1 v0.1.0: SetEditSGValueRequestPDUData
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerSetEditSGValueRequestPDUData extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerSetEditSGValueRequestPDUData() { _v.put("_", new java.util.ArrayList<>()); }
    @JsonCreator
    public static InnerSetEditSGValueRequestPDUData fromJson(Object v) { InnerSetEditSGValueRequestPDUData r = new InnerSetEditSGValueRequestPDUData(); r._v.put("_", MAPPER.convertValue(v, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousSetEditSGValueRequestPDUData>>() {})); return r; }
    public InnerSetEditSGValueRequestPDUData(java.util.List<InnerAnonymousSetEditSGValueRequestPDUData> v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        try {
            return InnerNative.encode("SetEditSGValueRequestPDUData", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("SetEditSGValueRequestPDUData", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerSetEditSGValueRequestPDUData decode(byte[] data) {
        try {
            String json = InnerNative.decode("SetEditSGValueRequestPDUData", DEFAULT_ENCODING, data);
            InnerSetEditSGValueRequestPDUData r = new InnerSetEditSGValueRequestPDUData();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            r._v.put("_", MAPPER.convertValue(_node.isArray() ? _node : _node.elements().next(), new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousSetEditSGValueRequestPDUData>>() {}));
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
