// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: GetGoCbValuesErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetGoCbValues-ErrorPDU ::= ServiceError
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetGoCbValuesErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetGoCbValuesErrorPDU() { _v.put("_", 1); }
    @JsonCreator
    public static InnerGetGoCbValuesErrorPDU fromJson(int v) { InnerGetGoCbValuesErrorPDU r = new InnerGetGoCbValuesErrorPDU(); r._v.put("_", v); return r; }
    public InnerGetGoCbValuesErrorPDU(Integer v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("GetGoCbValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetGoCbValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public static InnerGetGoCbValuesErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetGoCbValuesErrorPDU", DEFAULT_ENCODING, data);
            InnerGetGoCbValuesErrorPDU r = new InnerGetGoCbValuesErrorPDU();
            r._v.put("_", MAPPER.readTree(json).asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
