// Auto-generated by csasn1 v0.1.0 at 2026-07-28 01:34 UTC: GetBRCBValuesErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetBRCBValues-ErrorPDU ::= ServiceError
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetBRCBValuesErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public Integer value;
    public InnerGetBRCBValuesErrorPDU() {}
    @JsonCreator
    public InnerGetBRCBValuesErrorPDU(Integer value) { this.value = value; }
    public byte[] encode() {
        return InnerNative.encode("GetBRCBValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetBRCBValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public static InnerGetBRCBValuesErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetBRCBValuesErrorPDU", DEFAULT_ENCODING, data);
            InnerGetBRCBValuesErrorPDU r = new InnerGetBRCBValuesErrorPDU();
            r.value = MAPPER.readValue(json.trim(), Integer.class);
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
