// Auto-generated by csasn1 v0.1.0 at 2026-07-28 04:52 UTC: GetLogStatusValuesResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetLogStatusValues-ResponsePDU ::= SEQUENCE {
 *     log             [0] IMPLICIT SEQUENCE OF CHOICE {
 *         error       [0] IMPLICIT ServiceError,
 *         value       [1] IMPLICIT SEQUENCE {
 *             oldEntrTm   [0] IMPLICIT EntryTime,
 *             newEntrTm   [1] IMPLICIT EntryTime,
 *             oldEntr     [2] IMPLICIT EntryID,
 *             newEntr     [3] IMPLICIT EntryID
 *         }
 *     },
 *     moreFollows     [1] IMPLICIT Boolean DEFAULT 1
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetLogStatusValuesResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetLogStatusValuesResponsePDULog log = new InnerGetLogStatusValuesResponsePDULog();
    public InnerBoolean moreFollows = new InnerBoolean();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetLogStatusValuesResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetLogStatusValuesResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetLogStatusValuesResponsePDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetLogStatusValuesResponsePDU", DEFAULT_ENCODING, data), InnerGetLogStatusValuesResponsePDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
