// Auto-generated by csasn1 v0.1.0 at 2026-07-29 05:47 UTC: GetFileRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetFile-RequestPDU ::= SEQUENCE {
 *     filename        [0] IMPLICIT VisibleString (SIZE (0..255)),
 *     startPosition   [1] IMPLICIT Int32U
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetFileRequestPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public DefaultInnerVisibleString filename = new DefaultInnerVisibleString();
    public InnerInt32U startPosition = new InnerInt32U();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetFileRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetFileRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetFileRequestPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetFileRequestPDU", DEFAULT_ENCODING, data), InnerGetFileRequestPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
