// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: SetMSVCBValuesRequestPDUMsvcb
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerSetMSVCBValuesRequestPDUMsvcb extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerSetMSVCBValuesRequestPDUMsvcb() { _v.put("_", new java.util.ArrayList<>()); }
    @JsonCreator
    public static InnerSetMSVCBValuesRequestPDUMsvcb fromJson(Object v) { InnerSetMSVCBValuesRequestPDUMsvcb r = new InnerSetMSVCBValuesRequestPDUMsvcb(); r._v.put("_", MAPPER.convertValue(v, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousSetMSVCBValuesRequestPDUMsvcb>>() {})); return r; }
    public InnerSetMSVCBValuesRequestPDUMsvcb(java.util.List<InnerAnonymousSetMSVCBValuesRequestPDUMsvcb> v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        try {
            return InnerNative.encode("SetMSVCBValuesRequestPDUMsvcb", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("SetMSVCBValuesRequestPDUMsvcb", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerSetMSVCBValuesRequestPDUMsvcb decode(byte[] data) {
        try {
            String json = InnerNative.decode("SetMSVCBValuesRequestPDUMsvcb", DEFAULT_ENCODING, data);
            InnerSetMSVCBValuesRequestPDUMsvcb r = new InnerSetMSVCBValuesRequestPDUMsvcb();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            r._v.put("_", MAPPER.convertValue(_node.isArray() ? _node : _node.elements().next(), new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousSetMSVCBValuesRequestPDUMsvcb>>() {}));
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
