// Auto-generated by csasn1 v0.1.0: GetAllDataValuesResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetAllDataValues-ResponsePDU ::= SEQUENCE {
 *     data             [0] IMPLICIT SEQUENCE OF SEQUENCE {
 *         reference     [0] IMPLICIT SubReference,
 *         value         [1] IMPLICIT Data
 *     },
 *     moreFollows      [1] IMPLICIT Boolean DEFAULT 1
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerGetAllDataValuesResponsePDU extends InnerBase {
    public InnerGetAllDataValuesResponsePDU() {
        _v.put("data", new InnerGetAllDataValuesResponsePDUData()._v);
        _v.put("moreFollows", new InnerBoolean()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "GetAllDataValuesResponsePDU"; }
    public static InnerGetAllDataValuesResponsePDU decode(byte[] data) {
        return InnerBase.decode(InnerGetAllDataValuesResponsePDU.class, "GetAllDataValuesResponsePDU", data);
    }
}
