// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: AnonymousCreateDataSetRequestPDUMemberData
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * (inline type within CreateDataSet-RequestPDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerAnonymousCreateDataSetRequestPDUMemberData extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerAnonymousCreateDataSetRequestPDUMemberData() {
        _v.put("reference", new InnerObjectReference()._v);
        _v.put("fc", new InnerFunctionalConstraint()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    public byte[] encode() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            return InnerNative.encode("AnonymousCreateDataSetRequestPDUMemberData", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encode AnonymousCreateDataSetRequestPDUMemberData failed, json=" + _json, e);
        }
    }
    public byte[] encodeTest() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            System.err.println("JSON: " + _json);
            return new byte[0];
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerAnonymousCreateDataSetRequestPDUMemberData decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("AnonymousCreateDataSetRequestPDUMemberData", DEFAULT_ENCODING, data), InnerAnonymousCreateDataSetRequestPDUMemberData.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
