// Auto-generated by csasn1 v0.1.0: GetDataDefinitionRequestPDUData
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

public class InnerGetDataDefinitionRequestPDUData extends InnerBase {
    public InnerGetDataDefinitionRequestPDUData() { _v.put("_", new java.util.ArrayList<>()); }
    @JsonCreator
    public static InnerGetDataDefinitionRequestPDUData fromJson(Object v) { InnerGetDataDefinitionRequestPDUData r = new InnerGetDataDefinitionRequestPDUData(); r._v.put("_", InnerBase.MAPPER.convertValue(v, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetDataDefinitionRequestPDUData>>() {})); return r; }
    public InnerGetDataDefinitionRequestPDUData(java.util.List<InnerAnonymousGetDataDefinitionRequestPDUData> v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        try {
            return InnerNative.encode("GetDataDefinitionRequestPDUData", DEFAULT_ENCODING, InnerBase.MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("GetDataDefinitionRequestPDUData", DEFAULT_ENCODING, InnerBase.MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetDataDefinitionRequestPDUData decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetDataDefinitionRequestPDUData", DEFAULT_ENCODING, data);
            InnerGetDataDefinitionRequestPDUData r = new InnerGetDataDefinitionRequestPDUData();
            com.fasterxml.jackson.databind.JsonNode _node = InnerBase.MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", InnerBase.MAPPER.convertValue(_node, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetDataDefinitionRequestPDUData>>() {}));
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
