// Auto-generated by csasn1 v0.1.0: DeleteFileResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * DeleteFile-ResponsePDU ::= NULL
 * }</pre>
 */
public class InnerDeleteFileResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerDeleteFileResponsePDU() { _v.put("_", null); }
    @JsonCreator
    public static InnerDeleteFileResponsePDU fromJson(String v) { InnerDeleteFileResponsePDU r = new InnerDeleteFileResponsePDU(); r._v.put("_", v); return r; }
    public InnerDeleteFileResponsePDU(Object v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("DeleteFileResponsePDU", DEFAULT_ENCODING, "null");
    }
    public byte[] encodeTest() {
        return InnerNative.encode("DeleteFileResponsePDU", DEFAULT_ENCODING, "null");
    }
    public static InnerDeleteFileResponsePDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("DeleteFileResponsePDU", DEFAULT_ENCODING, data);
            InnerDeleteFileResponsePDU r = new InnerDeleteFileResponsePDU();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", null);
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
