// Auto-generated by csasn1 v0.1.0: GetLCBValuesErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetLCBValues-ErrorPDU ::= ServiceError
 * }</pre>
 */
public class InnerGetLCBValuesErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.MAPPER;
    public InnerGetLCBValuesErrorPDU() { _v.put("_", 1); }
    @JsonCreator
    public static InnerGetLCBValuesErrorPDU fromJson(int v) { InnerGetLCBValuesErrorPDU r = new InnerGetLCBValuesErrorPDU(); r._v.put("_", v); return r; }
    public InnerGetLCBValuesErrorPDU(Integer v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("GetLCBValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetLCBValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public static InnerGetLCBValuesErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetLCBValuesErrorPDU", DEFAULT_ENCODING, data);
            InnerGetLCBValuesErrorPDU r = new InnerGetLCBValuesErrorPDU();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", _node.asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
