// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: GetAllCBValuesRequestPDUReference
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetAllCBValuesRequestPDUReference extends InnerBase {
    @JsonIgnore public String _choice;
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetAllCBValuesRequestPDUReference() {
        this._choice = "ldName";
        this.ldName = new InnerObjectName();
    }
    @JsonIgnore public InnerObjectName ldName;
    @JsonIgnore public InnerObjectReference lnReference;
    @JsonAnyGetter
    public java.util.Map<String, Object> serializeChoice() {
        java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
        if (_choice != null) {
            if ("ldName".equals(_choice)) map.put("ldName", ldName);
            if ("lnReference".equals(_choice)) map.put("lnReference", lnReference);
        }
        return map;
    }
    @JsonAnySetter
    public void deserializeChoice(String key, Object value) {
        if ("_choice".equals(key)) return;
        this._choice = key;
        if ("ldName".equals(key)) {
            this.ldName = MAPPER.convertValue(value, InnerObjectName.class);
        }
        if ("lnReference".equals(key)) {
            this.lnReference = MAPPER.convertValue(value, InnerObjectReference.class);
        }
    }
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetAllCBValuesRequestPDUReference", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetAllCBValuesRequestPDUReference", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetAllCBValuesRequestPDUReference decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetAllCBValuesRequestPDUReference", DEFAULT_ENCODING, data), InnerGetAllCBValuesRequestPDUReference.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
