// Auto-generated by csasn1 v0.1.0: GetDataSetDirectoryResponsePDUMemberData
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetDataSetDirectoryResponsePDUMemberData extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetDataSetDirectoryResponsePDUMemberData() { _v.put("_", new java.util.ArrayList<>()); }
    @JsonCreator
    public static InnerGetDataSetDirectoryResponsePDUMemberData fromJson(Object v) { InnerGetDataSetDirectoryResponsePDUMemberData r = new InnerGetDataSetDirectoryResponsePDUMemberData(); r._v.put("_", MAPPER.convertValue(v, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetDataSetDirectoryResponsePDUMemberData>>() {})); return r; }
    public InnerGetDataSetDirectoryResponsePDUMemberData(java.util.List<InnerAnonymousGetDataSetDirectoryResponsePDUMemberData> v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        try {
            return InnerNative.encode("GetDataSetDirectoryResponsePDUMemberData", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("GetDataSetDirectoryResponsePDUMemberData", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetDataSetDirectoryResponsePDUMemberData decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetDataSetDirectoryResponsePDUMemberData", DEFAULT_ENCODING, data);
            InnerGetDataSetDirectoryResponsePDUMemberData r = new InnerGetDataSetDirectoryResponsePDUMemberData();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            r._v.put("_", MAPPER.convertValue(_node.isArray() ? _node : _node.elements().next(), new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetDataSetDirectoryResponsePDUMemberData>>() {}));
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
