// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: GetServerDirectoryRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetServerDirectory-RequestPDU ::= SEQUENCE {
 *     objectClass      [0] IMPLICIT INTEGER {
 *         reserved        (0),
 *         logical-device  (1),
 *         file-system     (2)
 *     } (0..2),
 *     referenceAfter   [1] IMPLICIT ObjectReference OPTIONAL
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetServerDirectoryRequestPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetServerDirectoryRequestPDU() {
        _v.put("objectClass", 1);
        _v.put("referenceAfter", new InnerObjectReference()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    public byte[] encode() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            return InnerNative.encode("GetServerDirectoryRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encode GetServerDirectoryRequestPDU failed, json=" + _json, e);
        }
    }
    public byte[] encodeTest() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            System.err.println("JSON: " + _json);
            return new byte[0];
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetServerDirectoryRequestPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetServerDirectoryRequestPDU", DEFAULT_ENCODING, data), InnerGetServerDirectoryRequestPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
