// Auto-generated by csasn1 v0.1.0 at 2026-07-28 01:34 UTC: SelectActiveSGRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * SelectActiveSG-RequestPDU ::= SEQUENCE {
 *     sgcbReference       [0] IMPLICIT ObjectReference,
 *     settingGroupNumber  [1] IMPLICIT Int8U
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerSelectActiveSGRequestPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerObjectReference sgcbReference = new InnerObjectReference();
    public InnerInt8U settingGroupNumber = new InnerInt8U();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("SelectActiveSGRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("SelectActiveSGRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerSelectActiveSGRequestPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("SelectActiveSGRequestPDU", DEFAULT_ENCODING, data), InnerSelectActiveSGRequestPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
