// Auto-generated by csasn1 v0.1.0 at 2026-07-28 09:11 UTC: GetGOOSEElementNumberRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetGOOSEElementNumber-RequestPDU ::= SEQUENCE {
 *     gocbReference   [0] IMPLICIT ObjectReference,
 *     memberData      [1] IMPLICIT SEQUENCE OF SEQUENCE {
 *         reference   [0] IMPLICIT ObjectReference,
 *         fc          [1] IMPLICIT FunctionalConstraint
 *     }
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetGOOSEElementNumberRequestPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerObjectReference gocbReference = new InnerObjectReference();
    public InnerGetGOOSEElementNumberRequestPDUMemberData memberData = new InnerGetGOOSEElementNumberRequestPDUMemberData();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetGOOSEElementNumberRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetGOOSEElementNumberRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetGOOSEElementNumberRequestPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetGOOSEElementNumberRequestPDU", DEFAULT_ENCODING, data), InnerGetGOOSEElementNumberRequestPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
