// Auto-generated by csasn1 v0.1.0 at 2026-07-28 04:52 UTC: SetLCBValuesRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * SetLCBValues-RequestPDU ::= SEQUENCE {
 *     lcb             [0] IMPLICIT SEQUENCE OF SEQUENCE {
 *         reference   [0] IMPLICIT ObjectReference,
 *         logEna      [1] IMPLICIT Boolean OPTIONAL,
 *         datSet      [2] IMPLICIT ObjectReference OPTIONAL,
 *         trgOps      [3] IMPLICIT TriggerConditions OPTIONAL,
 *         intgPd      [4] IMPLICIT Int32U OPTIONAL,
 *         logRef      [5] IMPLICIT ObjectReference OPTIONAL,
 *         optFlds     [6] IMPLICIT LcbOptFlds OPTIONAL,
 *         bufTm       [7] IMPLICIT Int32U OPTIONAL
 *     }
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerSetLCBValuesRequestPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerSetLCBValuesRequestPDULcb lcb = new InnerSetLCBValuesRequestPDULcb();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("SetLCBValuesRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("SetLCBValuesRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerSetLCBValuesRequestPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("SetLCBValuesRequestPDU", DEFAULT_ENCODING, data), InnerSetLCBValuesRequestPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
