// Auto-generated by csasn1 v0.1.0 at 2026-07-28 03:54 UTC: GetAllCBValuesErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetAllCBValues-ErrorPDU ::= ServiceError
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetAllCBValuesErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public Integer value = 0;
    public InnerGetAllCBValuesErrorPDU() {}
    @JsonCreator
    public InnerGetAllCBValuesErrorPDU(Integer value) { this.value = value; }
    public byte[] encode() {
        return InnerNative.encode("GetAllCBValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetAllCBValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public static InnerGetAllCBValuesErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetAllCBValuesErrorPDU", DEFAULT_ENCODING, data);
            InnerGetAllCBValuesErrorPDU r = new InnerGetAllCBValuesErrorPDU();
            r.value = MAPPER.readTree(json).get("value").asInt();
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
