// Auto-generated by csasn1 v0.1.0: AnonymousGetGOOSEElementNumberRequestPDUMemberData
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * (inline type within GetGOOSEElementNumber-RequestPDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerAnonymousGetGOOSEElementNumberRequestPDUMemberData extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.MAPPER;
    public InnerAnonymousGetGOOSEElementNumberRequestPDUMemberData() {
        _v.put("reference", new InnerObjectReference()._v);
        _v.put("fc", new InnerFunctionalConstraint()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    public byte[] encode() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            return InnerNative.encode("AnonymousGetGOOSEElementNumberRequestPDUMemberData", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encode AnonymousGetGOOSEElementNumberRequestPDUMemberData failed, json=" + _json, e);
        }
    }
    public byte[] encodeTest() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            System.err.println("JSON: " + _json);
            return new byte[0];
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerAnonymousGetGOOSEElementNumberRequestPDUMemberData decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("AnonymousGetGOOSEElementNumberRequestPDUMemberData", DEFAULT_ENCODING, data), InnerAnonymousGetGOOSEElementNumberRequestPDUMemberData.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
