// Auto-generated by csasn1 v0.1.0 at 2026-07-28 09:11 UTC: GetAllCBValuesResponsePDUCbValue
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetAllCBValuesResponsePDUCbValue extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public java.util.List<InnerAnonymousGetAllCBValuesResponsePDUCbValue> value = new java.util.ArrayList<>();
    public InnerGetAllCBValuesResponsePDUCbValue() {}
    @JsonCreator
    public InnerGetAllCBValuesResponsePDUCbValue(java.util.List<InnerAnonymousGetAllCBValuesResponsePDUCbValue> value) { this.value = value; }
    public byte[] encode() {
        try {
            return InnerNative.encode("GetAllCBValuesResponsePDUCbValue", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("GetAllCBValuesResponsePDUCbValue", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetAllCBValuesResponsePDUCbValue decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetAllCBValuesResponsePDUCbValue", DEFAULT_ENCODING, data);
            InnerGetAllCBValuesResponsePDUCbValue r = new InnerGetAllCBValuesResponsePDUCbValue();
            r.value = MAPPER.convertValue(MAPPER.readTree(json).get("value"), new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetAllCBValuesResponsePDUCbValue>>() {});
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
