// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: GetLogicalDeviceDirectoryResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetLogicalDeviceDirectory-ResponsePDU ::= SEQUENCE {
 *     lnReference       [0] IMPLICIT SEQUENCE OF SubReference,
 *     moreFollows       [1] IMPLICIT Boolean DEFAULT 1
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetLogicalDeviceDirectoryResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public java.util.List<InnerSubReference> lnReference = new java.util.ArrayList<>();
    public InnerBoolean moreFollows = new InnerBoolean();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetLogicalDeviceDirectoryResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetLogicalDeviceDirectoryResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetLogicalDeviceDirectoryResponsePDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetLogicalDeviceDirectoryResponsePDU", DEFAULT_ENCODING, data), InnerGetLogicalDeviceDirectoryResponsePDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
