// Auto-generated by csasn1 v0.1.0 at 2026-07-30 09:33 UTC: SetDataValuesRequestPDUData
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerSetDataValuesRequestPDUData extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerSetDataValuesRequestPDUData() { _v.put("_", new java.util.ArrayList<>()); }
    @JsonCreator
    public static InnerSetDataValuesRequestPDUData fromJson(Object v) { InnerSetDataValuesRequestPDUData r = new InnerSetDataValuesRequestPDUData(); r._v.put("_", MAPPER.convertValue(v, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousSetDataValuesRequestPDUData>>() {})); return r; }
    public InnerSetDataValuesRequestPDUData(java.util.List<InnerAnonymousSetDataValuesRequestPDUData> v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        try {
            return InnerNative.encode("SetDataValuesRequestPDUData", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("SetDataValuesRequestPDUData", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerSetDataValuesRequestPDUData decode(byte[] data) {
        try {
            String json = InnerNative.decode("SetDataValuesRequestPDUData", DEFAULT_ENCODING, data);
            InnerSetDataValuesRequestPDUData r = new InnerSetDataValuesRequestPDUData();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            r._v.put("_", MAPPER.convertValue(_node.isArray() ? _node : _node.elements().next(), new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousSetDataValuesRequestPDUData>>() {}));
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
