// Auto-generated by csasn1 v0.1.0 at 2026-07-27 08:06 UTC: GetDataDirectoryErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetDataDirectory-ErrorPDU ::= ServiceError
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetDataDirectoryErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public Integer value;
    public InnerGetDataDirectoryErrorPDU() {}
    @JsonCreator
    public InnerGetDataDirectoryErrorPDU(Integer value) { this.value = value; }
    public byte[] encode() {
        return InnerNative.encode("GetDataDirectoryErrorPDU", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetDataDirectoryErrorPDU", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public static InnerGetDataDirectoryErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetDataDirectoryErrorPDU", DEFAULT_ENCODING, data);
            InnerGetDataDirectoryErrorPDU r = new InnerGetDataDirectoryErrorPDU();
            r.value = MAPPER.readValue(json.trim(), Integer.class);
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
