// Auto-generated by csasn1 v0.1.0 at 2026-07-27 08:06 UTC: SetFileErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * SetFile-ErrorPDU ::= ServiceError
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerSetFileErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public Integer value;
    public InnerSetFileErrorPDU() {}
    @JsonCreator
    public InnerSetFileErrorPDU(Integer value) { this.value = value; }
    public byte[] encode() {
        return InnerNative.encode("SetFileErrorPDU", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("SetFileErrorPDU", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public static InnerSetFileErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("SetFileErrorPDU", DEFAULT_ENCODING, data);
            InnerSetFileErrorPDU r = new InnerSetFileErrorPDU();
            r.value = MAPPER.readValue(json.trim(), Integer.class);
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
