// Auto-generated by csasn1 v0.1.0: DeleteDataSetResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * DeleteDataSet-ResponsePDU ::= NULL
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerDeleteDataSetResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerDeleteDataSetResponsePDU() { _v.put("_", new Object()); }
    @JsonCreator
    public static InnerDeleteDataSetResponsePDU fromJson(String v) { InnerDeleteDataSetResponsePDU r = new InnerDeleteDataSetResponsePDU(); r._v.put("_", v); return r; }
    public InnerDeleteDataSetResponsePDU(Object v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("DeleteDataSetResponsePDU", DEFAULT_ENCODING, "null");
    }
    public byte[] encodeTest() {
        return InnerNative.encode("DeleteDataSetResponsePDU", DEFAULT_ENCODING, "null");
    }
    public static InnerDeleteDataSetResponsePDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("DeleteDataSetResponsePDU", DEFAULT_ENCODING, data);
            InnerDeleteDataSetResponsePDU r = new InnerDeleteDataSetResponsePDU();
            r._v.put("_", null);
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
