// Auto-generated by csasn1 v0.1.0: SetDataSetValuesRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * SetDataSetValues-RequestPDU ::= SEQUENCE {
 *     datasetReference    [0] IMPLICIT ObjectReference,
 *     referenceAfter      [1] IMPLICIT ObjectReference OPTIONAL,
 *     value               [2] IMPLICIT SEQUENCE OF Data
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerSetDataSetValuesRequestPDU extends InnerBase {
    public InnerSetDataSetValuesRequestPDU() {
        _v.put("datasetReference", new InnerObjectReference()._v);
        _v.put("value", new java.util.ArrayList<>());
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "SetDataSetValuesRequestPDU"; }
    public static InnerSetDataSetValuesRequestPDU decode(byte[] data) {
        return InnerBase.decode(InnerSetDataSetValuesRequestPDU.class, "SetDataSetValuesRequestPDU", data);
    }
}
