// Auto-generated by csasn1 v0.1.0 at 2026-07-23 14:23 UTC: UtcTime
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * UtcTime ::= OCTET STRING (SIZE(8))
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerUtcTime extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public byte[] value = new byte[8];
    public InnerUtcTime() {}
    @JsonCreator
    public InnerUtcTime(byte[] value) { this.value = value; }
    public byte[] encode() {
        try {
            return InnerNative.encode("UtcTime", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.hex(this.value)));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("UtcTime", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.hex(this.value)));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerUtcTime decode(byte[] data) {
        try {
            String json = InnerNative.decode("UtcTime", DEFAULT_ENCODING, data);
            InnerUtcTime r = new InnerUtcTime();
            r.value = InnerBase.unhex(MAPPER.readTree(json).get("value").asText());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
