// Auto-generated by csasn1 v0.1.0 at 2026-07-23 14:23 UTC: AnonymousGetAllCBValuesResponsePDUCbValueValue
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * (inline type within GetAllCBValues-ResponsePDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerAnonymousGetAllCBValuesResponsePDUCbValueValue extends InnerBase {
    @JsonIgnore public String _choice;
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerAnonymousGetAllCBValuesResponsePDUCbValueValue() {
        this._choice = "brcb";
        this.brcb = new InnerBRCB();
    }
    @JsonIgnore public InnerBRCB brcb;
    @JsonIgnore public InnerURCB urcb;
    @JsonIgnore public InnerLCB lcb;
    @JsonIgnore public InnerSGCB sgcb;
    @JsonIgnore public InnerGoCB gocb;
    @JsonIgnore public InnerMSVCB msvcb;
    @JsonAnyGetter
    public java.util.Map<String, Object> serializeChoice() {
        java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
        if (_choice != null) {
            if ("brcb".equals(_choice)) map.put("brcb", brcb);
            if ("urcb".equals(_choice)) map.put("urcb", urcb);
            if ("lcb".equals(_choice)) map.put("lcb", lcb);
            if ("sgcb".equals(_choice)) map.put("sgcb", sgcb);
            if ("gocb".equals(_choice)) map.put("gocb", gocb);
            if ("msvcb".equals(_choice)) map.put("msvcb", msvcb);
        }
        return map;
    }
    @JsonAnySetter
    public void deserializeChoice(String key, Object value) {
        if ("_choice".equals(key)) return;
        this._choice = key;
        if ("brcb".equals(key)) {
            this.brcb = MAPPER.convertValue(value, InnerBRCB.class);
        }
        if ("urcb".equals(key)) {
            this.urcb = MAPPER.convertValue(value, InnerURCB.class);
        }
        if ("lcb".equals(key)) {
            this.lcb = MAPPER.convertValue(value, InnerLCB.class);
        }
        if ("sgcb".equals(key)) {
            this.sgcb = MAPPER.convertValue(value, InnerSGCB.class);
        }
        if ("gocb".equals(key)) {
            this.gocb = MAPPER.convertValue(value, InnerGoCB.class);
        }
        if ("msvcb".equals(key)) {
            this.msvcb = MAPPER.convertValue(value, InnerMSVCB.class);
        }
    }
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AnonymousGetAllCBValuesResponsePDUCbValueValue", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AnonymousGetAllCBValuesResponsePDUCbValueValue", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerAnonymousGetAllCBValuesResponsePDUCbValueValue decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("AnonymousGetAllCBValuesResponsePDUCbValueValue", DEFAULT_ENCODING, data), InnerAnonymousGetAllCBValuesResponsePDUCbValueValue.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
