// Auto-generated by csasn1 v0.1.0 at 2026-07-28 01:34 UTC: GetRpcInterfaceDefinitionResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetRpcInterfaceDefinition-ResponsePDU ::= SEQUENCE {
 *     method          [0] IMPLICIT SEQUENCE OF SEQUENCE {
 *         name        [0] IMPLICIT VisibleString,
 *         version     [1] IMPLICIT Int32U,
 *         timeout     [2] IMPLICIT Int32U,
 *         request     [3] IMPLICIT DataDefinition,
 *         response    [4] IMPLICIT DataDefinition
 *     },
 *     moreFollows     [1] IMPLICIT Boolean DEFAULT 1
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetRpcInterfaceDefinitionResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetRpcInterfaceDefinitionResponsePDUMethod method = new InnerGetRpcInterfaceDefinitionResponsePDUMethod();
    public InnerBoolean moreFollows = new InnerBoolean();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetRpcInterfaceDefinitionResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetRpcInterfaceDefinitionResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetRpcInterfaceDefinitionResponsePDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetRpcInterfaceDefinitionResponsePDU", DEFAULT_ENCODING, data), InnerGetRpcInterfaceDefinitionResponsePDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
