// Auto-generated by csasn1 v0.1.0 at 2026-07-23 14:23 UTC: AnonymousSetLCBValuesRequestPDULcb
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * (inline type within SetLCBValues-RequestPDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerAnonymousSetLCBValuesRequestPDULcb extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerObjectReference reference = new InnerObjectReference();
    public InnerBoolean logEna = new InnerBoolean();
    public InnerObjectReference datSet = new InnerObjectReference();
    public InnerTriggerConditions trgOps = new InnerTriggerConditions();
    public InnerInt32U intgPd = new InnerInt32U();
    public InnerObjectReference logRef = new InnerObjectReference();
    public InnerLcbOptFlds optFlds = new InnerLcbOptFlds();
    public InnerInt32U bufTm = new InnerInt32U();
    @com.fasterxml.jackson.annotation.JsonIgnore
    @lombok.EqualsAndHashCode.Exclude
    public transient java.util.Set<String> _set = new java.util.HashSet<>();
    public InnerAnonymousSetLCBValuesRequestPDULcb logEna(InnerBoolean value) {
        this.logEna = value;
        this._set.add("logEna");
        return this;
    }
    public InnerAnonymousSetLCBValuesRequestPDULcb datSet(InnerObjectReference value) {
        this.datSet = value;
        this._set.add("datSet");
        return this;
    }
    public InnerAnonymousSetLCBValuesRequestPDULcb trgOps(InnerTriggerConditions value) {
        this.trgOps = value;
        this._set.add("trgOps");
        return this;
    }
    public InnerAnonymousSetLCBValuesRequestPDULcb intgPd(InnerInt32U value) {
        this.intgPd = value;
        this._set.add("intgPd");
        return this;
    }
    public InnerAnonymousSetLCBValuesRequestPDULcb logRef(InnerObjectReference value) {
        this.logRef = value;
        this._set.add("logRef");
        return this;
    }
    public InnerAnonymousSetLCBValuesRequestPDULcb optFlds(InnerLcbOptFlds value) {
        this.optFlds = value;
        this._set.add("optFlds");
        return this;
    }
    public InnerAnonymousSetLCBValuesRequestPDULcb bufTm(InnerInt32U value) {
        this.bufTm = value;
        this._set.add("bufTm");
        return this;
    }
    public byte[] encode() {
        try {
            com.fasterxml.jackson.databind.node.ObjectNode _root = MAPPER.valueToTree(this);
            if (!_set.contains("logEna")) _root.remove("logEna");
            if (!_set.contains("datSet")) _root.remove("datSet");
            if (!_set.contains("trgOps")) _root.remove("trgOps");
            if (!_set.contains("intgPd")) _root.remove("intgPd");
            if (!_set.contains("logRef")) _root.remove("logRef");
            if (!_set.contains("optFlds")) _root.remove("optFlds");
            if (!_set.contains("bufTm")) _root.remove("bufTm");
            String _json = MAPPER.writeValueAsString(_root);
            return InnerNative.encode("AnonymousSetLCBValuesRequestPDULcb", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AnonymousSetLCBValuesRequestPDULcb", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerAnonymousSetLCBValuesRequestPDULcb decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("AnonymousSetLCBValuesRequestPDULcb", DEFAULT_ENCODING, data), InnerAnonymousSetLCBValuesRequestPDULcb.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
