// Auto-generated by csasn1 v0.1.0: SetDataValuesResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * SetDataValues-ResponsePDU ::= NULL
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerSetDataValuesResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerSetDataValuesResponsePDU() { _v.put("_", new Object()); }
    @JsonCreator
    public static InnerSetDataValuesResponsePDU fromJson(String v) { InnerSetDataValuesResponsePDU r = new InnerSetDataValuesResponsePDU(); r._v.put("_", v); return r; }
    public InnerSetDataValuesResponsePDU(Object v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("SetDataValuesResponsePDU", DEFAULT_ENCODING, "null");
    }
    public byte[] encodeTest() {
        return InnerNative.encode("SetDataValuesResponsePDU", DEFAULT_ENCODING, "null");
    }
    public static InnerSetDataValuesResponsePDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("SetDataValuesResponsePDU", DEFAULT_ENCODING, data);
            InnerSetDataValuesResponsePDU r = new InnerSetDataValuesResponsePDU();
            r._v.put("_", null);
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
