// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: GetFileAttributeValuesResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetFileAttributeValues-ResponsePDU ::= FileEntry
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetFileAttributeValuesResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetFileAttributeValuesResponsePDU() { _v.put("_", new InnerFileEntry()); }
    @JsonCreator
    public static InnerGetFileAttributeValuesResponsePDU fromJson(String v) { InnerGetFileAttributeValuesResponsePDU r = new InnerGetFileAttributeValuesResponsePDU(); r._v.put("_", v); return r; }
    public InnerGetFileAttributeValuesResponsePDU(InnerFileEntry v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        try {
            return InnerNative.encode("GetFileAttributeValuesResponsePDU", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("GetFileAttributeValuesResponsePDU", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetFileAttributeValuesResponsePDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetFileAttributeValuesResponsePDU", DEFAULT_ENCODING, data);
            InnerGetFileAttributeValuesResponsePDU r = new InnerGetFileAttributeValuesResponsePDU();
            r._v.put("_", MAPPER.readValue(json.trim(), InnerFileEntry.class));
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
