// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: GetAllDataDefinitionErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetAllDataDefinition-ErrorPDU ::= ServiceError
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetAllDataDefinitionErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public int value;
    public InnerGetAllDataDefinitionErrorPDU() {}
    @JsonCreator
    public InnerGetAllDataDefinitionErrorPDU(int value) { this.value = value; }
    public byte[] encode() {
        return InnerNative.encode("GetAllDataDefinitionErrorPDU", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetAllDataDefinitionErrorPDU", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public static InnerGetAllDataDefinitionErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetAllDataDefinitionErrorPDU", DEFAULT_ENCODING, data);
            InnerGetAllDataDefinitionErrorPDU r = new InnerGetAllDataDefinitionErrorPDU();
            r.value = MAPPER.readTree(json).get("value").asInt();
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
