// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: GetDataSetValuesErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetDataSetValues-ErrorPDU ::= ServiceError
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetDataSetValuesErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public int value;
    public InnerGetDataSetValuesErrorPDU() {}
    @JsonCreator
    public InnerGetDataSetValuesErrorPDU(int value) { this.value = value; }
    public byte[] encode() {
        return InnerNative.encode("GetDataSetValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetDataSetValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public static InnerGetDataSetValuesErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetDataSetValuesErrorPDU", DEFAULT_ENCODING, data);
            InnerGetDataSetValuesErrorPDU r = new InnerGetDataSetValuesErrorPDU();
            r.value = MAPPER.readTree(json).get("value").asInt();
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
