// Auto-generated by csasn1 v0.1.0 at 2026-07-28 09:11 UTC: SetBRCBValuesErrorPDUResult
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerSetBRCBValuesErrorPDUResult extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public java.util.List<InnerAnonymousSetBRCBValuesErrorPDUResult> value = new java.util.ArrayList<>();
    public InnerSetBRCBValuesErrorPDUResult() {}
    @JsonCreator
    public InnerSetBRCBValuesErrorPDUResult(java.util.List<InnerAnonymousSetBRCBValuesErrorPDUResult> value) { this.value = value; }
    public byte[] encode() {
        try {
            return InnerNative.encode("SetBRCBValuesErrorPDUResult", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("SetBRCBValuesErrorPDUResult", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerSetBRCBValuesErrorPDUResult decode(byte[] data) {
        try {
            String json = InnerNative.decode("SetBRCBValuesErrorPDUResult", DEFAULT_ENCODING, data);
            InnerSetBRCBValuesErrorPDUResult r = new InnerSetBRCBValuesErrorPDUResult();
            r.value = MAPPER.convertValue(MAPPER.readTree(json).get("value"), new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousSetBRCBValuesErrorPDUResult>>() {});
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
