// Auto-generated by csasn1 v0.1.0 at 2026-07-28 09:11 UTC: ObjectName
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * ObjectName ::= VisibleString (SIZE(0..64))
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerObjectName extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public DefaultInnerVisibleString value = new DefaultInnerVisibleString("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    public InnerObjectName() {}
    @JsonCreator
    public InnerObjectName(DefaultInnerVisibleString value) { this.value = value; }
    public byte[] encode() {
        try {
            return InnerNative.encode("ObjectName", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("ObjectName", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerObjectName decode(byte[] data) {
        try {
            String json = InnerNative.decode("ObjectName", DEFAULT_ENCODING, data);
            InnerObjectName r = new InnerObjectName();
            r.value = new DefaultInnerVisibleString(MAPPER.readTree(json).get("value").asText());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
