// Auto-generated by csasn1 v0.1.0: SetLCBValuesResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * SetLCBValues-ResponsePDU ::= NULL
 * }</pre>
 */
public class InnerSetLCBValuesResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerSetLCBValuesResponsePDU() { _v.put("_", null); }
    @JsonCreator
    public static InnerSetLCBValuesResponsePDU fromJson(String v) { InnerSetLCBValuesResponsePDU r = new InnerSetLCBValuesResponsePDU(); r._v.put("_", v); return r; }
    public InnerSetLCBValuesResponsePDU(Object v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("SetLCBValuesResponsePDU", DEFAULT_ENCODING, "null");
    }
    public byte[] encodeTest() {
        return InnerNative.encode("SetLCBValuesResponsePDU", DEFAULT_ENCODING, "null");
    }
    public static InnerSetLCBValuesResponsePDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("SetLCBValuesResponsePDU", DEFAULT_ENCODING, data);
            InnerSetLCBValuesResponsePDU r = new InnerSetLCBValuesResponsePDU();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", null);
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
