// Auto-generated by csasn1 v0.1.0 at 2026-07-27 08:06 UTC: ReleaseRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * Release-RequestPDU ::= SEQUENCE {
 *     associationId    [0] IMPLICIT OCTET STRING (SIZE (0..64))
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerReleaseRequestPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public byte[] associationId = new byte[0];
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("ReleaseRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("ReleaseRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerReleaseRequestPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("ReleaseRequestPDU", DEFAULT_ENCODING, data), InnerReleaseRequestPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
