// Auto-generated by csasn1 v0.1.0 at 2026-07-23 14:23 UTC: QueryLogAfterRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * QueryLogAfter-RequestPDU ::= SEQUENCE {
 *     logReference    [0] IMPLICIT ObjectReference,
 *     startTime       [1] IMPLICIT EntryTime OPTIONAL,
 *     entry           [2] IMPLICIT EntryID
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerQueryLogAfterRequestPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerObjectReference logReference = new InnerObjectReference();
    public InnerEntryTime startTime = new InnerEntryTime();
    public InnerEntryID entry = new InnerEntryID();
    @com.fasterxml.jackson.annotation.JsonIgnore
    @lombok.EqualsAndHashCode.Exclude
    public transient java.util.Set<String> _set = new java.util.HashSet<>();
    public InnerQueryLogAfterRequestPDU startTime(InnerEntryTime value) {
        this.startTime = value;
        this._set.add("startTime");
        return this;
    }
    public byte[] encode() {
        try {
            com.fasterxml.jackson.databind.node.ObjectNode _root = MAPPER.valueToTree(this);
            if (!_set.contains("startTime")) _root.remove("startTime");
            String _json = MAPPER.writeValueAsString(_root);
            return InnerNative.encode("QueryLogAfterRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("QueryLogAfterRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerQueryLogAfterRequestPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("QueryLogAfterRequestPDU", DEFAULT_ENCODING, data), InnerQueryLogAfterRequestPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
