// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: ReasonCode
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * ReasonCode ::= BIT STRING {
 *     reserved                    (0),
 *     data-change                 (1),
 *     quality-change              (2),
 *     data-update                 (3),
 *     integrity                   (4),
 *     general-interrogation       (5),
 *     application-trigger         (6)
 * } (SIZE(7))
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerReasonCode extends InnerBase {
    public static final int RESERVED = 0;
    public static final int DATA_CHANGE = 1;
    public static final int QUALITY_CHANGE = 2;
    public static final int DATA_UPDATE = 3;
    public static final int INTEGRITY = 4;
    public static final int GENERAL_INTERROGATION = 5;
    public static final int APPLICATION_TRIGGER = 6;
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerReasonCode() { _v.put("_", "00"); }
    public InnerReasonCode(int v) { this(); _v.put("_", InnerBase.bitStringHex(v, 7)); }
    @JsonValue
    @Override
    public Object toJsonValue() { return _v.get("_"); }
    @JsonCreator
    public static InnerReasonCode fromJson(String hex) { return new InnerReasonCode(hex); }
    public InnerReasonCode(String hex) { this(); _v.put("_", hex); }
    public byte[] encode() {
        try {
            return InnerNative.encode("ReasonCode", DEFAULT_ENCODING, MAPPER.writeValueAsString(_v.get("_")));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("ReasonCode", DEFAULT_ENCODING, MAPPER.writeValueAsString(_v.get("_")));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerReasonCode decode(byte[] data) {
        try {
            String json = InnerNative.decode("ReasonCode", DEFAULT_ENCODING, data);
            InnerReasonCode r = new InnerReasonCode();
            r._v.put("_", InnerBase.parseBitStringHex(MAPPER.readTree(json).asText(), 7));
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
