// Auto-generated by csasn1 v0.1.0: SelectWithValueResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * SelectWithValue-ResponsePDU ::= SEQUENCE {
 *     reference       [0] IMPLICIT ObjectReference,
 *     ctlVal          [1] IMPLICIT Data,
 *     operTm          [2] IMPLICIT TimeStamp OPTIONAL,
 *     origin          [3] IMPLICIT Originator,
 *     ctlNum          [4] IMPLICIT Int8U,
 *     t               [5] IMPLICIT TimeStamp,
 *     test            [6] IMPLICIT Boolean,
 *     check           [7] IMPLICIT Check
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerSelectWithValueResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.MAPPER;
    public InnerSelectWithValueResponsePDU() {
        _v.put("reference", new InnerObjectReference()._v);
        _v.put("ctlVal", new InnerData()._v);
        _v.put("origin", new InnerOriginator()._v);
        _v.put("ctlNum", new InnerInt8U()._v);
        _v.put("t", new InnerTimeStamp()._v);
        _v.put("test", new InnerBoolean()._v);
        _v.put("check", new InnerCheck()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    public byte[] encode() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            return InnerNative.encode("SelectWithValueResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encode SelectWithValueResponsePDU failed, json=" + _json, e);
        }
    }
    public byte[] encodeTest() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            System.err.println("JSON: " + _json);
            return new byte[0];
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerSelectWithValueResponsePDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("SelectWithValueResponsePDU", DEFAULT_ENCODING, data), InnerSelectWithValueResponsePDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
