// Auto-generated by csasn1 v0.1.0: GetServerDirectoryErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetServerDirectory-ErrorPDU ::= ServiceError
 * }</pre>
 */
public class InnerGetServerDirectoryErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.MAPPER;
    public InnerGetServerDirectoryErrorPDU() { _v.put("_", 1); }
    @JsonCreator
    public static InnerGetServerDirectoryErrorPDU fromJson(int v) { InnerGetServerDirectoryErrorPDU r = new InnerGetServerDirectoryErrorPDU(); r._v.put("_", v); return r; }
    public InnerGetServerDirectoryErrorPDU(Integer v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("GetServerDirectoryErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetServerDirectoryErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public static InnerGetServerDirectoryErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetServerDirectoryErrorPDU", DEFAULT_ENCODING, data);
            InnerGetServerDirectoryErrorPDU r = new InnerGetServerDirectoryErrorPDU();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", _node.asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
