// Auto-generated by csasn1 v0.1.0: AnonymousGetAllCBValuesResponsePDUCbValueValue
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * (inline type within GetAllCBValues-ResponsePDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerAnonymousGetAllCBValuesResponsePDUCbValueValue extends InnerBase {
    public InnerAnonymousGetAllCBValuesResponsePDUCbValueValue() {
        _v.put("_choice", "brcb");
        _v.put("_", new InnerBRCB()._v);
    }
    @Override
    protected boolean isChoice() { return true; }
    @JsonSetter("brcb")
    public void setBrcb(Object v) {
        _v.put("_choice", "brcb");
        _setValue(v);
    }
    @JsonSetter("urcb")
    public void setUrcb(Object v) {
        _v.put("_choice", "urcb");
        _setValue(v);
    }
    @JsonSetter("lcb")
    public void setLcb(Object v) {
        _v.put("_choice", "lcb");
        _setValue(v);
    }
    @JsonSetter("sgcb")
    public void setSgcb(Object v) {
        _v.put("_choice", "sgcb");
        _setValue(v);
    }
    @JsonSetter("gocb")
    public void setGocb(Object v) {
        _v.put("_choice", "gocb");
        _setValue(v);
    }
    @JsonSetter("msvcb")
    public void setMsvcb(Object v) {
        _v.put("_choice", "msvcb");
        _setValue(v);
    }
    @Override
    protected String typeName() { return "AnonymousGetAllCBValuesResponsePDUCbValueValue"; }
    public static InnerAnonymousGetAllCBValuesResponsePDUCbValueValue decode(byte[] data) {
        return InnerBase.decode(InnerAnonymousGetAllCBValuesResponsePDUCbValueValue.class, "AnonymousGetAllCBValuesResponsePDUCbValueValue", data);
    }
}
