// Auto-generated by csasn1 v0.1.0: RpcCallRequestPDUReq
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerRpcCallRequestPDUReq extends InnerBase {
    public InnerRpcCallRequestPDUReq() {
        _v.put("_choice", "reqData");
        _v.put("_", new InnerData()._v);
    }
    @Override
    protected boolean isChoice() { return true; }
    @JsonSetter("reqData")
    public void setReqData(Object v) {
        _v.put("_choice", "reqData");
        _setValue(v);
    }
    @JsonSetter("callID")
    public void setCallID(Object v) {
        _v.put("_choice", "callID");
        _setValue(v);
    }
    @Override
    protected String typeName() { return "RpcCallRequestPDUReq"; }
    public static InnerRpcCallRequestPDUReq decode(byte[] data) {
        return InnerBase.decode(InnerRpcCallRequestPDUReq.class, "RpcCallRequestPDUReq", data);
    }
}
