// Auto-generated by csasn1 v0.1.0: GetRpcInterfaceDirectoryErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetRpcInterfaceDirectory-ErrorPDU ::= ServiceError
 * }</pre>
 */
public class InnerGetRpcInterfaceDirectoryErrorPDU extends InnerBase {
    public InnerGetRpcInterfaceDirectoryErrorPDU() { _v.put("_", 1); }
    @JsonCreator
    public static InnerGetRpcInterfaceDirectoryErrorPDU fromJson(int v) { InnerGetRpcInterfaceDirectoryErrorPDU r = new InnerGetRpcInterfaceDirectoryErrorPDU(); r._v.put("_", v); return r; }
    public InnerGetRpcInterfaceDirectoryErrorPDU(Integer v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("GetRpcInterfaceDirectoryErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetRpcInterfaceDirectoryErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public static InnerGetRpcInterfaceDirectoryErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetRpcInterfaceDirectoryErrorPDU", DEFAULT_ENCODING, data);
            InnerGetRpcInterfaceDirectoryErrorPDU r = new InnerGetRpcInterfaceDirectoryErrorPDU();
            com.fasterxml.jackson.databind.JsonNode _node = InnerBase.MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", _node.asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
