// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: SetEditSGValueResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * SetEditSGValue-ResponsePDU ::= NULL
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerSetEditSGValueResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerSetEditSGValueResponsePDU() { _v.put("_", new Object()); }
    @JsonCreator
    public static InnerSetEditSGValueResponsePDU fromJson(String v) { InnerSetEditSGValueResponsePDU r = new InnerSetEditSGValueResponsePDU(); r._v.put("_", v); return r; }
    public InnerSetEditSGValueResponsePDU(Object v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("SetEditSGValueResponsePDU", DEFAULT_ENCODING, "null");
    }
    public byte[] encodeTest() {
        return InnerNative.encode("SetEditSGValueResponsePDU", DEFAULT_ENCODING, "null");
    }
    public static InnerSetEditSGValueResponsePDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("SetEditSGValueResponsePDU", DEFAULT_ENCODING, data);
            InnerSetEditSGValueResponsePDU r = new InnerSetEditSGValueResponsePDU();
            r._v.put("_", null);
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
