// Auto-generated by csasn1 v0.1.0 at 2026-07-27 08:06 UTC: Float64
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * Float64 ::= OCTET STRING (SIZE (8))
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerFloat64 extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public byte[] value = new byte[8];
    public InnerFloat64() {}
    @JsonCreator
    public InnerFloat64(byte[] value) { this.value = value; }
    public byte[] encode() {
        try {
            return InnerNative.encode("Float64", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.hex(this.value)));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("Float64", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.hex(this.value)));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerFloat64 decode(byte[] data) {
        try {
            String json = InnerNative.decode("Float64", DEFAULT_ENCODING, data);
            InnerFloat64 r = new InnerFloat64();
            r.value = InnerBase.unhex(MAPPER.readTree(json).get("value").asText());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
