// Auto-generated by csasn1 v0.1.0: GetAllDataDefinitionErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetAllDataDefinition-ErrorPDU ::= ServiceError
 * }</pre>
 */
public class InnerGetAllDataDefinitionErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetAllDataDefinitionErrorPDU() { _v.put("_", 1); }
    @JsonCreator
    public static InnerGetAllDataDefinitionErrorPDU fromJson(int v) { InnerGetAllDataDefinitionErrorPDU r = new InnerGetAllDataDefinitionErrorPDU(); r._v.put("_", v); return r; }
    public InnerGetAllDataDefinitionErrorPDU(Integer v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("GetAllDataDefinitionErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetAllDataDefinitionErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public static InnerGetAllDataDefinitionErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetAllDataDefinitionErrorPDU", DEFAULT_ENCODING, data);
            InnerGetAllDataDefinitionErrorPDU r = new InnerGetAllDataDefinitionErrorPDU();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", _node.asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
