// Auto-generated by csasn1 v0.1.0: MSVCB
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * MSVCB ::= SEQUENCE {
 *     svEna           [1] IMPLICIT Boolean,
 *     msvID           [2] IMPLICIT VisibleString (SIZE (0..129)),
 *     datSet          [3] IMPLICIT ObjectReference,
 *     confRev         [4] IMPLICIT Int32U,
 *     smpMod          [5] IMPLICIT SmpMod OPTIONAL,
 *     smpRate         [6] IMPLICIT Int16U,
 *     optFlds         [7] IMPLICIT MsvcbOptFlds,
 *     dstAddress      [8] IMPLICIT PhyComAddr OPTIONAL
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerMSVCB extends InnerBase {
    public InnerMSVCB() {
        _v.put("svEna", new InnerBoolean()._v);
        _v.put("msvID", new DefaultInnerVisibleString("x"));
        _v.put("datSet", new InnerObjectReference()._v);
        _v.put("confRev", new InnerInt32U()._v);
        _v.put("smpRate", new InnerInt16U()._v);
        _v.put("optFlds", new InnerMsvcbOptFlds()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "MSVCB"; }
    public static InnerMSVCB decode(byte[] data) {
        return InnerBase.decode(InnerMSVCB.class, "MSVCB", data);
    }
}
