// Auto-generated by csasn1 v0.1.0: SelectEditSGResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * SelectEditSG-ResponsePDU ::= NULL
 * }</pre>
 */
public class InnerSelectEditSGResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerSelectEditSGResponsePDU() { _v.put("_", null); }
    @JsonCreator
    public static InnerSelectEditSGResponsePDU fromJson(String v) { InnerSelectEditSGResponsePDU r = new InnerSelectEditSGResponsePDU(); r._v.put("_", v); return r; }
    public InnerSelectEditSGResponsePDU(Object v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("SelectEditSGResponsePDU", DEFAULT_ENCODING, "null");
    }
    public byte[] encodeTest() {
        return InnerNative.encode("SelectEditSGResponsePDU", DEFAULT_ENCODING, "null");
    }
    public static InnerSelectEditSGResponsePDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("SelectEditSGResponsePDU", DEFAULT_ENCODING, data);
            InnerSelectEditSGResponsePDU r = new InnerSelectEditSGResponsePDU();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", null);
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
