// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: AssociateNegotiateResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * AssociateNegotiate-ResponsePDU ::= SEQUENCE {
 *     apduSize        [0] IMPLICIT Int16U,
 *     asduSize        [1] IMPLICIT Int32U,
 *     protocolVersion [2] IMPLICIT Int32U,
 *     modelVersion    [3] IMPLICIT VisibleString
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerAssociateNegotiateResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerInt16U apduSize = new InnerInt16U();
    public InnerInt32U asduSize = new InnerInt32U();
    public InnerInt32U protocolVersion = new InnerInt32U();
    public String modelVersion = "";
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AssociateNegotiateResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AssociateNegotiateResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerAssociateNegotiateResponsePDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("AssociateNegotiateResponsePDU", DEFAULT_ENCODING, data), InnerAssociateNegotiateResponsePDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
