// Auto-generated by csasn1 v0.1.0: GetRpcMethodDefinitionResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetRpcMethodDefinition-ResponsePDU ::= SEQUENCE {
 *     reference       [0] IMPLICIT SEQUENCE OF CHOICE {
 *         error       [0] IMPLICIT ServiceError,
 *         method      [1] IMPLICIT SEQUENCE {
 *             version     [0] IMPLICIT Int32U,
 *             timeout     [1] IMPLICIT Int32U,
 *             request     [2] IMPLICIT DataDefinition,
 *             response    [3] IMPLICIT DataDefinition
 *         }
 *     },
 *     moreFollows     [1] IMPLICIT Boolean DEFAULT 1
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerGetRpcMethodDefinitionResponsePDU extends InnerBase {
    public InnerGetRpcMethodDefinitionResponsePDU() {
        _v.put("reference", new InnerGetRpcMethodDefinitionResponsePDUReference()._v);
        _v.put("moreFollows", new InnerBoolean()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "GetRpcMethodDefinitionResponsePDU"; }
    public static InnerGetRpcMethodDefinitionResponsePDU decode(byte[] data) {
        return InnerBase.decode(InnerGetRpcMethodDefinitionResponsePDU.class, "GetRpcMethodDefinitionResponsePDU", data);
    }
}
