// Auto-generated by csasn1 v0.1.0: GetFileAttributeValuesRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetFileAttributeValues-RequestPDU ::= SEQUENCE {
 *     filename        [0] IMPLICIT VisibleString (SIZE (0..255))
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerGetFileAttributeValuesRequestPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.MAPPER;
    public InnerGetFileAttributeValuesRequestPDU() {
        _v.put("filename", new DefaultInnerVisibleString("x"));
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    public byte[] encode() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            return InnerNative.encode("GetFileAttributeValuesRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encode GetFileAttributeValuesRequestPDU failed, json=" + _json, e);
        }
    }
    public byte[] encodeTest() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            System.err.println("JSON: " + _json);
            return new byte[0];
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetFileAttributeValuesRequestPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetFileAttributeValuesRequestPDU", DEFAULT_ENCODING, data), InnerGetFileAttributeValuesRequestPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
