// Auto-generated by csasn1 v0.1.0: GetLogicalDeviceDirectoryRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetLogicalDeviceDirectory-RequestPDU ::= SEQUENCE {
 *     ldName            [0] IMPLICIT ObjectName OPTIONAL,
 *     referenceAfter    [1] IMPLICIT ObjectReference OPTIONAL
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerGetLogicalDeviceDirectoryRequestPDU extends InnerBase {
    public InnerGetLogicalDeviceDirectoryRequestPDU() {
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "GetLogicalDeviceDirectoryRequestPDU"; }
    public static InnerGetLogicalDeviceDirectoryRequestPDU decode(byte[] data) {
        return InnerBase.decode(InnerGetLogicalDeviceDirectoryRequestPDU.class, "GetLogicalDeviceDirectoryRequestPDU", data);
    }
}
