// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: GetDataDirectoryResponsePDUDataAttribute
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetDataDirectoryResponsePDUDataAttribute extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetDataDirectoryResponsePDUDataAttribute() { _v.put("_", new java.util.ArrayList<>()); }
    @JsonCreator
    public static InnerGetDataDirectoryResponsePDUDataAttribute fromJson(Object v) { InnerGetDataDirectoryResponsePDUDataAttribute r = new InnerGetDataDirectoryResponsePDUDataAttribute(); r._v.put("_", MAPPER.convertValue(v, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetDataDirectoryResponsePDUDataAttribute>>() {})); return r; }
    public InnerGetDataDirectoryResponsePDUDataAttribute(java.util.List<InnerAnonymousGetDataDirectoryResponsePDUDataAttribute> v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        try {
            return InnerNative.encode("GetDataDirectoryResponsePDUDataAttribute", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("GetDataDirectoryResponsePDUDataAttribute", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetDataDirectoryResponsePDUDataAttribute decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetDataDirectoryResponsePDUDataAttribute", DEFAULT_ENCODING, data);
            InnerGetDataDirectoryResponsePDUDataAttribute r = new InnerGetDataDirectoryResponsePDUDataAttribute();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            r._v.put("_", MAPPER.convertValue(_node.isArray() ? _node : _node.elements().next(), new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetDataDirectoryResponsePDUDataAttribute>>() {}));
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
