// Auto-generated by csasn1 v0.1.0: ReportPDUEntry
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerReportPDUEntry extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.MAPPER;
    public InnerReportPDUEntry() {
        _v.put("entryData", new InnerReportPDUEntryEntryData()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    public byte[] encode() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            return InnerNative.encode("ReportPDUEntry", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encode ReportPDUEntry failed, json=" + _json, e);
        }
    }
    public byte[] encodeTest() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            System.err.println("JSON: " + _json);
            return new byte[0];
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerReportPDUEntry decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("ReportPDUEntry", DEFAULT_ENCODING, data), InnerReportPDUEntry.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
