// Auto-generated by csasn1 v0.1.0 at 2026-07-23 14:23 UTC: LogEntry
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * LogEntry ::= SEQUENCE {
 *     timeOfEntry     [0] IMPLICIT EntryTime,
 *     entryID         [1] IMPLICIT EntryID,
 *     entryData       [2] IMPLICIT SEQUENCE OF SEQUENCE {
 *         reference   [0] IMPLICIT ObjectReference,
 *         fc          [1] IMPLICIT FunctionalConstraint,
 *         value       [2] IMPLICIT Data,
 *         reason      [3] IMPLICIT ReasonCode
 *     }
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerLogEntry extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerEntryTime timeOfEntry = new InnerEntryTime();
    public InnerEntryID entryID = new InnerEntryID();
    public InnerLogEntryEntryData entryData = new InnerLogEntryEntryData();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("LogEntry", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("LogEntry", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerLogEntry decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("LogEntry", DEFAULT_ENCODING, data), InnerLogEntry.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
