// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: SetGoCBValuesRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * SetGoCBValues-RequestPDU ::= SEQUENCE {
 *     gocb            [0] IMPLICIT SEQUENCE OF SEQUENCE {
 *         reference   [0] IMPLICIT ObjectReference,
 *         goEna       [1] IMPLICIT Boolean OPTIONAL,
 *         goID        [2] IMPLICIT VisibleString (SIZE (0..129)) OPTIONAL,
 *         datSet      [3] IMPLICIT ObjectReference OPTIONAL
 *     }
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerSetGoCBValuesRequestPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerSetGoCBValuesRequestPDU() {
        _v.put("gocb", new InnerSetGoCBValuesRequestPDUGocb()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    public byte[] encode() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            return InnerNative.encode("SetGoCBValuesRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encode SetGoCBValuesRequestPDU failed, json=" + _json, e);
        }
    }
    public byte[] encodeTest() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            System.err.println("JSON: " + _json);
            return new byte[0];
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerSetGoCBValuesRequestPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("SetGoCBValuesRequestPDU", DEFAULT_ENCODING, data), InnerSetGoCBValuesRequestPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
