// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: AnonymousGetRpcMethodDefinitionResponsePDUReferenceMethod
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * (inline type within GetRpcMethodDefinition-ResponsePDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerAnonymousGetRpcMethodDefinitionResponsePDUReferenceMethod extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerInt32U version = new InnerInt32U();
    public InnerInt32U timeout = new InnerInt32U();
    public InnerDataDefinition request = new InnerDataDefinition();
    public InnerDataDefinition response = new InnerDataDefinition();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AnonymousGetRpcMethodDefinitionResponsePDUReferenceMethod", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AnonymousGetRpcMethodDefinitionResponsePDUReferenceMethod", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerAnonymousGetRpcMethodDefinitionResponsePDUReferenceMethod decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("AnonymousGetRpcMethodDefinitionResponsePDUReferenceMethod", DEFAULT_ENCODING, data), InnerAnonymousGetRpcMethodDefinitionResponsePDUReferenceMethod.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
