// Auto-generated by csasn1 v0.1.0 at 2026-07-29 05:47 UTC: AnonymousGetAllCBValuesResponsePDUCbValue
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * (inline type within GetAllCBValues-ResponsePDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerAnonymousGetAllCBValuesResponsePDUCbValue extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerSubReference reference = new InnerSubReference();
    public InnerAnonymousGetAllCBValuesResponsePDUCbValueValue value = new InnerAnonymousGetAllCBValuesResponsePDUCbValueValue();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AnonymousGetAllCBValuesResponsePDUCbValue", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AnonymousGetAllCBValuesResponsePDUCbValue", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerAnonymousGetAllCBValuesResponsePDUCbValue decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("AnonymousGetAllCBValuesResponsePDUCbValue", DEFAULT_ENCODING, data), InnerAnonymousGetAllCBValuesResponsePDUCbValue.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
