// Auto-generated by csasn1 v0.1.0 at 2026-07-29 05:47 UTC: AnonymousGetDataDefinitionResponsePDUData
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * (inline type within GetDataDefinition-ResponsePDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerAnonymousGetDataDefinitionResponsePDUData extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public DefaultInnerVisibleString cdcType = new DefaultInnerVisibleString();
    public InnerDataDefinition definition = new InnerDataDefinition();
    @com.fasterxml.jackson.annotation.JsonIgnore
    @lombok.EqualsAndHashCode.Exclude
    public transient java.util.Set<String> _set = new java.util.HashSet<>();
    public InnerAnonymousGetDataDefinitionResponsePDUData cdcType(DefaultInnerVisibleString value) {
        this.cdcType = value;
        this._set.add("cdcType");
        return this;
    }
    public byte[] encode() {
        try {
            com.fasterxml.jackson.databind.node.ObjectNode _root = MAPPER.valueToTree(this);
            if (!_set.contains("cdcType")) _root.remove("cdcType");
            String _json = MAPPER.writeValueAsString(_root);
            return InnerNative.encode("AnonymousGetDataDefinitionResponsePDUData", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AnonymousGetDataDefinitionResponsePDUData", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerAnonymousGetDataDefinitionResponsePDUData decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("AnonymousGetDataDefinitionResponsePDUData", DEFAULT_ENCODING, data), InnerAnonymousGetDataDefinitionResponsePDUData.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
