// Auto-generated by csasn1 v0.1.0 at 2026-07-30 09:33 UTC: ObjectName
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * ObjectName ::= VisibleString (SIZE(0..64))
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerObjectName extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerObjectName() { _v.put("_", "x"); }
    @JsonCreator
    public static InnerObjectName fromJson(String v) { InnerObjectName r = new InnerObjectName(); r._v.put("_", v); return r; }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        try {
            return InnerNative.encode("ObjectName", DEFAULT_ENCODING, MAPPER.writeValueAsString(_v.get("_")));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("ObjectName", DEFAULT_ENCODING, MAPPER.writeValueAsString(_v.get("_")));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerObjectName decode(byte[] data) {
        try {
            String json = InnerNative.decode("ObjectName", DEFAULT_ENCODING, data);
            InnerObjectName r = new InnerObjectName();
            r._v.put("_", MAPPER.readValue(json.trim(), DefaultInnerVisibleString.class));
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
