// Auto-generated by csasn1 v0.1.0 at 2026-07-27 08:06 UTC: SubReference
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * SubReference ::= VisibleString (SIZE(0..129))
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerSubReference extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public String value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
    public InnerSubReference() {}
    @JsonCreator
    public InnerSubReference(String value) { this.value = value; }
    public byte[] encode() {
        try {
            return InnerNative.encode("SubReference", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("SubReference", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerSubReference decode(byte[] data) {
        try {
            String json = InnerNative.decode("SubReference", DEFAULT_ENCODING, data);
            InnerSubReference r = new InnerSubReference();
            r.value = MAPPER.readTree(json).get("value").asText();
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
