// Auto-generated by csasn1 v0.1.0 at 2026-07-28 03:54 UTC: Dbpos
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * Dbpos ::= BIT STRING (SIZE(2))
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerDbpos extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public Integer value = 0;
    public InnerDbpos() {}
    public InnerDbpos(Integer value) { this.value = value; }
    @JsonValue
    public String toJsonValue() { return InnerBase.bitStringHex(this.value, 2); }
    @JsonCreator
    public InnerDbpos(String hex) { this.value = InnerBase.parseBitStringHex(hex, 2); }
    public byte[] encode() {
        try {
            return InnerNative.encode("Dbpos", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.bitStringHex(this.value, 2)));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("Dbpos", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.bitStringHex(this.value, 2)));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerDbpos decode(byte[] data) {
        try {
            String json = InnerNative.decode("Dbpos", DEFAULT_ENCODING, data);
            InnerDbpos r = new InnerDbpos();
            r.value = InnerBase.parseBitStringHex(MAPPER.readTree(json).get("value").asText(), 2);
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
