// Auto-generated by csasn1 v0.1.0 at 2026-07-28 09:11 UTC: AnonymousGetLogStatusValuesResponsePDULogValue
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * (inline type within GetLogStatusValues-ResponsePDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerAnonymousGetLogStatusValuesResponsePDULogValue extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerEntryTime oldEntrTm = new InnerEntryTime();
    public InnerEntryTime newEntrTm = new InnerEntryTime();
    public InnerEntryID oldEntr = new InnerEntryID();
    public InnerEntryID newEntr = new InnerEntryID();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AnonymousGetLogStatusValuesResponsePDULogValue", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AnonymousGetLogStatusValuesResponsePDULogValue", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerAnonymousGetLogStatusValuesResponsePDULogValue decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("AnonymousGetLogStatusValuesResponsePDULogValue", DEFAULT_ENCODING, data), InnerAnonymousGetLogStatusValuesResponsePDULogValue.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
