// Auto-generated by csasn1 v0.1.0 at 2026-07-29 05:47 UTC: AnonymousSetURCBValuesRequestPDUUrcb
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * (inline type within SetURCBValues-RequestPDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerAnonymousSetURCBValuesRequestPDUUrcb extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerObjectReference reference = new InnerObjectReference();
    public DefaultInnerVisibleString rptID = new DefaultInnerVisibleString();
    public InnerBoolean rptEna = new InnerBoolean();
    public InnerObjectReference datSet = new InnerObjectReference();
    public InnerRcbOptFlds optFlds = new InnerRcbOptFlds();
    public InnerInt32U bufTm = new InnerInt32U();
    public InnerTriggerConditions trgOps = new InnerTriggerConditions();
    public InnerInt32U intgPd = new InnerInt32U();
    public InnerBoolean gi = new InnerBoolean();
    public InnerBoolean resv = new InnerBoolean();
    @com.fasterxml.jackson.annotation.JsonIgnore
    @lombok.EqualsAndHashCode.Exclude
    public transient java.util.Set<String> _set = new java.util.HashSet<>();
    public InnerAnonymousSetURCBValuesRequestPDUUrcb rptID(DefaultInnerVisibleString value) {
        this.rptID = value;
        this._set.add("rptID");
        return this;
    }
    public InnerAnonymousSetURCBValuesRequestPDUUrcb rptEna(InnerBoolean value) {
        this.rptEna = value;
        this._set.add("rptEna");
        return this;
    }
    public InnerAnonymousSetURCBValuesRequestPDUUrcb datSet(InnerObjectReference value) {
        this.datSet = value;
        this._set.add("datSet");
        return this;
    }
    public InnerAnonymousSetURCBValuesRequestPDUUrcb optFlds(InnerRcbOptFlds value) {
        this.optFlds = value;
        this._set.add("optFlds");
        return this;
    }
    public InnerAnonymousSetURCBValuesRequestPDUUrcb bufTm(InnerInt32U value) {
        this.bufTm = value;
        this._set.add("bufTm");
        return this;
    }
    public InnerAnonymousSetURCBValuesRequestPDUUrcb trgOps(InnerTriggerConditions value) {
        this.trgOps = value;
        this._set.add("trgOps");
        return this;
    }
    public InnerAnonymousSetURCBValuesRequestPDUUrcb intgPd(InnerInt32U value) {
        this.intgPd = value;
        this._set.add("intgPd");
        return this;
    }
    public InnerAnonymousSetURCBValuesRequestPDUUrcb gi(InnerBoolean value) {
        this.gi = value;
        this._set.add("gi");
        return this;
    }
    public InnerAnonymousSetURCBValuesRequestPDUUrcb resv(InnerBoolean value) {
        this.resv = value;
        this._set.add("resv");
        return this;
    }
    public byte[] encode() {
        try {
            com.fasterxml.jackson.databind.node.ObjectNode _root = MAPPER.valueToTree(this);
            if (!_set.contains("rptID")) _root.remove("rptID");
            if (!_set.contains("rptEna")) _root.remove("rptEna");
            if (!_set.contains("datSet")) _root.remove("datSet");
            if (!_set.contains("optFlds")) _root.remove("optFlds");
            if (!_set.contains("bufTm")) _root.remove("bufTm");
            if (!_set.contains("trgOps")) _root.remove("trgOps");
            if (!_set.contains("intgPd")) _root.remove("intgPd");
            if (!_set.contains("gi")) _root.remove("gi");
            if (!_set.contains("resv")) _root.remove("resv");
            String _json = MAPPER.writeValueAsString(_root);
            return InnerNative.encode("AnonymousSetURCBValuesRequestPDUUrcb", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AnonymousSetURCBValuesRequestPDUUrcb", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerAnonymousSetURCBValuesRequestPDUUrcb decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("AnonymousSetURCBValuesRequestPDUUrcb", DEFAULT_ENCODING, data), InnerAnonymousSetURCBValuesRequestPDUUrcb.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
