// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: GetGoCbValuesResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetGoCbValues-ResponsePDU ::= SEQUENCE {
 *     gocb            [0] IMPLICIT SEQUENCE OF CHOICE {
 *         error       [0] IMPLICIT ServiceError,
 *         value       [1] IMPLICIT GoCB
 *     },
 *     moreFollows     [1] IMPLICIT Boolean DEFAULT 1
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetGoCbValuesResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetGoCbValuesResponsePDUGocb gocb = new InnerGetGoCbValuesResponsePDUGocb();
    public InnerBoolean moreFollows = new InnerBoolean();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetGoCbValuesResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetGoCbValuesResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetGoCbValuesResponsePDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetGoCbValuesResponsePDU", DEFAULT_ENCODING, data), InnerGetGoCbValuesResponsePDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
