// Auto-generated by csasn1 v0.1.0: ReleaseErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * Release-ErrorPDU ::= ServiceError
 * }</pre>
 */
public class InnerReleaseErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.MAPPER;
    public InnerReleaseErrorPDU() { _v.put("_", 1); }
    @JsonCreator
    public static InnerReleaseErrorPDU fromJson(int v) { InnerReleaseErrorPDU r = new InnerReleaseErrorPDU(); r._v.put("_", v); return r; }
    public InnerReleaseErrorPDU(Integer v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("ReleaseErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("ReleaseErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public static InnerReleaseErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("ReleaseErrorPDU", DEFAULT_ENCODING, data);
            InnerReleaseErrorPDU r = new InnerReleaseErrorPDU();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", _node.asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
