// Auto-generated by csasn1 v0.1.0: GetLogStatusValuesErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetLogStatusValues-ErrorPDU ::= ServiceError
 * }</pre>
 */
public class InnerGetLogStatusValuesErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.MAPPER;
    public InnerGetLogStatusValuesErrorPDU() { _v.put("_", 1); }
    @JsonCreator
    public static InnerGetLogStatusValuesErrorPDU fromJson(int v) { InnerGetLogStatusValuesErrorPDU r = new InnerGetLogStatusValuesErrorPDU(); r._v.put("_", v); return r; }
    public InnerGetLogStatusValuesErrorPDU(Integer v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("GetLogStatusValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetLogStatusValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public static InnerGetLogStatusValuesErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetLogStatusValuesErrorPDU", DEFAULT_ENCODING, data);
            InnerGetLogStatusValuesErrorPDU r = new InnerGetLogStatusValuesErrorPDU();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", _node.asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
