// Auto-generated by csasn1 v0.1.0: LogEntry
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * LogEntry ::= SEQUENCE {
 *     timeOfEntry     [0] IMPLICIT EntryTime,
 *     entryID         [1] IMPLICIT EntryID,
 *     entryData       [2] IMPLICIT SEQUENCE OF SEQUENCE {
 *         reference   [0] IMPLICIT ObjectReference,
 *         fc          [1] IMPLICIT FunctionalConstraint,
 *         value       [2] IMPLICIT Data,
 *         reason      [3] IMPLICIT ReasonCode
 *     }
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerLogEntry extends InnerBase {
    public InnerLogEntry() {
        _v.put("timeOfEntry", new InnerEntryTime()._v);
        _v.put("entryID", new InnerEntryID()._v);
        _v.put("entryData", new InnerLogEntryEntryData()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "LogEntry"; }
    public static InnerLogEntry decode(byte[] data) {
        return InnerBase.decode(InnerLogEntry.class, "LogEntry", data);
    }
}
