// Auto-generated by csasn1 v0.1.0: QueryLogAfterRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * QueryLogAfter-RequestPDU ::= SEQUENCE {
 *     logReference    [0] IMPLICIT ObjectReference,
 *     startTime       [1] IMPLICIT EntryTime OPTIONAL,
 *     entry           [2] IMPLICIT EntryID
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerQueryLogAfterRequestPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerQueryLogAfterRequestPDU() {
        _v.put("logReference", new InnerObjectReference()._v);
        _v.put("startTime", new InnerEntryTime()._v);
        _v.put("entry", new InnerEntryID()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    public byte[] encode() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            return InnerNative.encode("QueryLogAfterRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encode QueryLogAfterRequestPDU failed, json=" + _json, e);
        }
    }
    public byte[] encodeTest() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            System.err.println("JSON: " + _json);
            return new byte[0];
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerQueryLogAfterRequestPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("QueryLogAfterRequestPDU", DEFAULT_ENCODING, data), InnerQueryLogAfterRequestPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
