// Auto-generated by csasn1 v0.1.0 at 2026-07-28 01:34 UTC: OperateErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * Operate-ErrorPDU ::= SEQUENCE {
 *     reference       [0] IMPLICIT ObjectReference,
 *     ctlVal          [1] IMPLICIT Data,
 *     origin          [3] IMPLICIT Originator,
 *     ctlNum          [4] IMPLICIT Int8U,
 *     t               [5] IMPLICIT TimeStamp,
 *     test            [6] IMPLICIT Boolean,
 *     check           [7] IMPLICIT Check,
 *     addCause        [8] IMPLICIT AddCause
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerOperateErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerObjectReference reference = new InnerObjectReference();
    public InnerData ctlVal = new InnerData();
    public InnerOriginator origin = new InnerOriginator();
    public InnerInt8U ctlNum = new InnerInt8U();
    public InnerTimeStamp t = new InnerTimeStamp();
    public InnerBoolean test = new InnerBoolean();
    public InnerCheck check = new InnerCheck();
    public InnerAddCause addCause = new InnerAddCause();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("OperateErrorPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("OperateErrorPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerOperateErrorPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("OperateErrorPDU", DEFAULT_ENCODING, data), InnerOperateErrorPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
