// Auto-generated by csasn1 v0.1.0: SetBRCBValuesResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * SetBRCBValues-ResponsePDU ::= NULL
 * }</pre>
 */
public class InnerSetBRCBValuesResponsePDU extends InnerBase {
    public InnerSetBRCBValuesResponsePDU() { _v.put("_", null); }
    @JsonCreator
    public static InnerSetBRCBValuesResponsePDU fromJson(String v) { InnerSetBRCBValuesResponsePDU r = new InnerSetBRCBValuesResponsePDU(); r._v.put("_", v); return r; }
    public InnerSetBRCBValuesResponsePDU(Object v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("SetBRCBValuesResponsePDU", DEFAULT_ENCODING, "null");
    }
    public byte[] encodeTest() {
        return InnerNative.encode("SetBRCBValuesResponsePDU", DEFAULT_ENCODING, "null");
    }
    public static InnerSetBRCBValuesResponsePDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("SetBRCBValuesResponsePDU", DEFAULT_ENCODING, data);
            InnerSetBRCBValuesResponsePDU r = new InnerSetBRCBValuesResponsePDU();
            com.fasterxml.jackson.databind.JsonNode _node = InnerBase.MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", null);
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
