// Auto-generated by csasn1 v0.1.0: SetMSVCBValuesRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * SetMSVCBValues-RequestPDU ::= SEQUENCE {
 *     msvcb           [0] IMPLICIT SEQUENCE OF SEQUENCE {
 *         reference   [0] IMPLICIT ObjectReference,
 *         svEna       [1] IMPLICIT Boolean OPTIONAL,
 *         msvID       [2] IMPLICIT VisibleString (SIZE (0..129)) OPTIONAL,
 *         datSet      [3] IMPLICIT ObjectReference OPTIONAL,
 *         smpMod      [5] IMPLICIT SmpMod OPTIONAL,
 *         smpRate     [6] IMPLICIT Int16U OPTIONAL,
 *         optFlds     [7] IMPLICIT MsvcbOptFlds OPTIONAL
 *     }
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerSetMSVCBValuesRequestPDU extends InnerBase {
    public InnerSetMSVCBValuesRequestPDU() {
        _v.put("msvcb", new InnerSetMSVCBValuesRequestPDUMsvcb()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "SetMSVCBValuesRequestPDU"; }
    public static InnerSetMSVCBValuesRequestPDU decode(byte[] data) {
        return InnerBase.decode(InnerSetMSVCBValuesRequestPDU.class, "SetMSVCBValuesRequestPDU", data);
    }
}
