// Auto-generated by csasn1 v0.1.0: QueryLogAfterResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * QueryLogAfter-ResponsePDU ::= SEQUENCE {
 *     logEntry        [0] IMPLICIT SEQUENCE OF LogEntry,
 *     moreFollows     [1] IMPLICIT Boolean DEFAULT 1
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerQueryLogAfterResponsePDU extends InnerBase {
    public InnerQueryLogAfterResponsePDU() {
        _v.put("logEntry", new java.util.ArrayList<>());
        _v.put("moreFollows", new InnerBoolean()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "QueryLogAfterResponsePDU"; }
    public static InnerQueryLogAfterResponsePDU decode(byte[] data) {
        return InnerBase.decode(InnerQueryLogAfterResponsePDU.class, "QueryLogAfterResponsePDU", data);
    }
}
