// Auto-generated by csasn1 v0.1.0 at 2026-07-28 04:52 UTC: GetRpcMethodDefinitionResponsePDUReference
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetRpcMethodDefinitionResponsePDUReference extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public java.util.List<InnerAnonymousGetRpcMethodDefinitionResponsePDUReference> value = new java.util.ArrayList<>();
    public InnerGetRpcMethodDefinitionResponsePDUReference() {}
    @JsonCreator
    public InnerGetRpcMethodDefinitionResponsePDUReference(java.util.List<InnerAnonymousGetRpcMethodDefinitionResponsePDUReference> value) { this.value = value; }
    public byte[] encode() {
        try {
            return InnerNative.encode("GetRpcMethodDefinitionResponsePDUReference", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("GetRpcMethodDefinitionResponsePDUReference", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetRpcMethodDefinitionResponsePDUReference decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetRpcMethodDefinitionResponsePDUReference", DEFAULT_ENCODING, data);
            InnerGetRpcMethodDefinitionResponsePDUReference r = new InnerGetRpcMethodDefinitionResponsePDUReference();
            r.value = MAPPER.convertValue(MAPPER.readTree(json).get("value"), new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetRpcMethodDefinitionResponsePDUReference>>() {});
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
