// Auto-generated by csasn1 v0.1.0: GetLogicalNodeDirectoryRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetLogicalNodeDirectory-RequestPDU ::= SEQUENCE {
 *     reference       [0] IMPLICIT CHOICE {
 *         ldName         [0] IMPLICIT ObjectName,
 *         lnReference    [1] IMPLICIT ObjectReference
 *     },
 *     acsiClass       [1] IMPLICIT ACSIClass,
 *     referenceAfter  [2] IMPLICIT ObjectReference OPTIONAL
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerGetLogicalNodeDirectoryRequestPDU extends InnerBase {
    public InnerGetLogicalNodeDirectoryRequestPDU() {
        _v.put("reference", new InnerGetLogicalNodeDirectoryRequestPDUReference()._v);
        _v.put("acsiClass", new InnerACSIClass()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "GetLogicalNodeDirectoryRequestPDU"; }
    public static InnerGetLogicalNodeDirectoryRequestPDU decode(byte[] data) {
        return InnerBase.decode(InnerGetLogicalNodeDirectoryRequestPDU.class, "GetLogicalNodeDirectoryRequestPDU", data);
    }
}
