// Auto-generated by csasn1 v0.1.0: InnerBase (abstract base class)

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.module.SimpleModule;
import java.io.IOException;

public abstract class InnerBase {
    public static final String DEFAULT_ENCODING = "aper";

    /** Shared ObjectMapper configured for JER-compatible serialization. Thread-safe once configured. */
    public static final ObjectMapper MAPPER = createMapper();

    /** The unified data store: all scalar/SEQUENCE/CHOICE fields live here. Underscore prefix avoids conflict with ASN.1 field names. */
    @JsonIgnore
    public java.util.LinkedHashMap<String, Object> _v = new java.util.LinkedHashMap<>();

    /** Encode this type to APER bytes via Rust FFI. Implemented by each generated subclass. */
    public abstract byte[] encode();

    /** Decode APER bytes into a new instance of this type. */
    public static InnerBase decode(byte[] data) { throw new UnsupportedOperationException("Use concrete subclass decode()"); }

    /** Convert byte array to uppercase hex string (matches Rust JER output). */
    public static String hex(byte[] bytes) {
        if (bytes == null) return "";
        StringBuilder sb = new StringBuilder(bytes.length * 2);
        for (byte b : bytes) {
            sb.append(HEX_BYTES_UPPER[b & 0xFF]);
        }
        return sb.toString();
    }

    private static final char[] HEX_DIGITS_UPPER = "0123456789ABCDEF".toCharArray();
    private static final String[] HEX_BYTES_UPPER = new String[256];
    static {
        for (int i = 0; i < 256; i++) {
            HEX_BYTES_UPPER[i] = "" + HEX_DIGITS_UPPER[(i >> 4) & 0xF] + HEX_DIGITS_UPPER[i & 0xF];
        }
    }

    /** Convert hex string to byte array. Handles both "4048F5C3" and "0x400x48..." formats. */
    public static byte[] unhex(String hex) {
        if (hex == null || hex.isEmpty()) return new byte[0];
        // Single pass: skip "0x"/"0X" byte prefixes (rasn JER uses {:02X?} format
        // which emits "0x40" per byte) without allocating intermediate strings.
        int len = hex.length();
        byte[] data = new byte[len / 2];
        int out = 0;
        int i = 0;
        while (i + 1 < len) {
            char hi = hex.charAt(i);
            char lo = hex.charAt(i + 1);
            if (hi == '0' && (lo == 'x' || lo == 'X')) {
                i += 2;
                continue;
            }
            data[out++] = (byte) ((Character.digit(hi, 16) << 4) + Character.digit(lo, 16));
            i += 2;
        }
        return out == data.length ? data : java.util.Arrays.copyOf(data, out);
    }

    @Override
    public String toString() {
        try {
            return MAPPER.writeValueAsString(this);
        } catch (Exception e) {
            return getClass().getSimpleName() + "{...}";
        }
    }

    /** Structural equality: both sides normalized via toJson() before comparison. */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        return java.util.Objects.equals(toJson(toJsonValue()), toJson(((InnerBase) o).toJsonValue()));
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hashCode(toJson(toJsonValue()));
    }

    /** Create an ObjectMapper configured for JER-compatible serialization. */
    protected static ObjectMapper createMapper() {
        ObjectMapper m = new ObjectMapper();
        m.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);
        m.setVisibility(PropertyAccessor.GETTER, JsonAutoDetect.Visibility.NONE);
        m.setVisibility(PropertyAccessor.IS_GETTER, JsonAutoDetect.Visibility.NONE);
        m.setVisibility(PropertyAccessor.SETTER, JsonAutoDetect.Visibility.NONE);
        m.setVisibility(PropertyAccessor.CREATOR, JsonAutoDetect.Visibility.NONE);
        SimpleModule mod = new SimpleModule();
        // MapSerializer's null handling is influenced by the @JsonInclude(NON_NULL)
        // on generated classes (which wins over the mapper-wide inclusion above),
        // so plain-Map nulls (e.g. NULL choice variants {"Boolean": null}) would be
        // silently dropped. Force them out as real JSON null instead.
        mod.addSerializer(java.util.LinkedHashMap.class, new JsonSerializer<Object>() {
            @Override
            public void serialize(Object value, JsonGenerator gen, SerializerProvider prov) throws IOException {
                java.util.LinkedHashMap<String, Object> m = (java.util.LinkedHashMap<String, Object>) value;
                gen.writeStartObject();
                for (java.util.Map.Entry<String, Object> e : m.entrySet()) {
                    Object v = e.getValue();
                    if (v == null) {
                        gen.writeNullField(e.getKey());
                    } else {
                        gen.writeObjectField(e.getKey(), v);
                    }
                }
                gen.writeEndObject();
            }
        });
        mod.addSerializer(byte[].class, new JsonSerializer<byte[]>() {
            @Override
            public void serialize(byte[] value, JsonGenerator gen, SerializerProvider prov) throws IOException {
                gen.writeString(hex(value));
            }
        });
        mod.addDeserializer(byte[].class, new JsonDeserializer<byte[]>() {
            @Override
            public byte[] deserialize(JsonParser p, DeserializationContext ctx) throws IOException {
                return unhex(p.getValueAsString());
            }
        });
        m.registerModule(mod);
        return m;
    }

    /** Convert integer value to BIT STRING JER hex (MSB-first byte packing). */
    public static String bitStringHex(int value, int numBits) {
        int bytes = (numBits + 7) / 8;
        int result = 0;
        for (int i = 0; i < numBits; i++) {
            if ((value & (1 << i)) != 0) {
                int bytePos = i / 8;
                int bitPos = 7 - (i % 8);
                result |= (1 << (bytePos * 8 + bitPos));
            }
        }
        // Output bytes LSB-first — matches Rust JER byte ordering.
        // Uppercase to match Rust JER output, so encode→decode equality holds
        // without case normalization in toJson().
        StringBuilder sb = new StringBuilder();
        for (int j = 0; j < bytes; j++) {
            sb.append(HEX_BYTES_UPPER[(result >> (j * 8)) & 0xFF]);
        }
        return sb.toString();
    }

    /** Parse BIT STRING JER hex back to integer value. */
    public static int parseBitStringHex(String hex, int numBits) {
        int bytes = hex.length() / 2;
        // Parse LSB-first hex bytes back to integer
        int packed = 0;
        for (int b = 0; b < bytes; b++) {
            int byteVal = Integer.parseInt(hex.substring(b * 2, b * 2 + 2), 16);
            packed |= (byteVal << (b * 8));
        }
        // Convert from MSB-first byte packing to LSB-0 packed value
        int result = 0;
        for (int i = 0; i < numBits; i++) {
            int bytePos = i / 8;
            int bitPos = 7 - (i % 8);
            if ((packed & (1 << (bytePos * 8 + bitPos))) != 0) {
                result |= (1 << i);
            }
        }
        return result;
    }

    /**
     * Unified serialization via _v map:
     * - Scalars: _v has only "_" → returns the scalar value directly
     * - CHOICE: _v has "_choice" → returns {"variant": value}
     * - SEQUENCE: all fields in _v → returns recursively processed map
     */
    @JsonValue
    public Object toJsonValue() {
        if (_v.containsKey("_choice")) {
            String choice = (String) _v.get("_choice");
            java.util.LinkedHashMap<String, Object> out = new java.util.LinkedHashMap<>();
            if (choice != null && _v.containsKey("_")) {
                out.put(choice, toJson(_v.get("_")));
            }
            return out;
        }
        if (_v.size() == 1 && _v.containsKey("_")) {
            return toJson(V.getVal(_v));
        }
        // Recursively process _v content to unwrap nested scalar wrappers {"_": value}.
        // This handles the case where _v stores raw Maps like {"_": 0} (from InnerInt32U()._v).
        return toJson(_v);
    }

    /** Return the scalar value stored under {@code _}. */
    @JsonIgnore
    public Object getValue() { return _v.get("_"); }

    /** Set the scalar value under {@code _}. */
    public void setValue(Object v) { _v.put("_", v); }

    /**
     * Recursively flatten _v content for correct JSON encoding:
     * - InnerBase instances -> their toJsonValue()
     * - Maps with only "_" (scalar wrappers) -> the scalar value
     * - Other Maps/Lists -> recursively processed
     * - Primitives -> as-is
     */
    public static Object toJson(Object val) {
        if (val instanceof InnerBase) {
            // toJsonValue() already runs toJson() recursively — do NOT re-run
            // toJson() on its result. On a second pass a CHOICE NULL variant map
            // {"Boolean": null} is treated as a plain map and the null value is
            // dropped again (plain-map branch skips nulls), emitting {} which the
            // native decoder rejects (NoValidChoice).
            return ((InnerBase) val).toJsonValue();
        }
        // byte[] -> hex string: canonical form never holds raw arrays (identity
        // equals/hashCode would break structural equality)
        if (val instanceof byte[]) {
            return hex((byte[]) val);
        }
        if (val instanceof java.util.Map) {
            java.util.Map<String, Object> m = (java.util.Map<String, Object>) val;
            // CHOICE map: {"_choice": "variant", "_": value} -> {"variant": value}
            if (m.containsKey("_choice")) {
                String choice = (String) m.get("_choice");
                java.util.LinkedHashMap<String, Object> out = new java.util.LinkedHashMap<>();
                if (choice != null && m.containsKey("_")) {
                    out.put(choice, toJson(m.get("_")));
                }
                return out;
            }
            // Scalar wrapper: {"_": value} -> value
            if (V.isScalarWrapper(m)) {
                return toJson(V.getVal(m));
            }
            // Regular map — recursively process values, skip nulls and metadata
            java.util.LinkedHashMap<String, Object> result = new java.util.LinkedHashMap<>();
            for (java.util.Map.Entry<String, Object> e : m.entrySet()) {
                if (e.getKey().startsWith("_")) continue;
                Object v = toJson(e.getValue());
                if (v != null) {
                    result.put(e.getKey(), v);
                }
            }
            return result;
        }
        if (val instanceof java.util.List) {
            java.util.List<Object> list = (java.util.List<Object>) val;
            java.util.ArrayList<Object> result = new java.util.ArrayList<>();
            for (Object item : list) {
                result.add(toJson(item));
            }
            return result;
        }
        if (val instanceof Integer || val instanceof Long || val instanceof Short || val instanceof Byte) {
            return ((Number) val).longValue();
        }
        if (val instanceof Float || val instanceof Double) {
            return ((Number) val).doubleValue();
        }
        if (val instanceof String) {
            // Return as-is: do NOT uppercase hex-shaped strings. Uppercasing here
            // would silently rewrite user-supplied string values (e.g. a VisibleString
            // "abc123") on every encode. BIT STRING hex case is already normalized by
            // bitStringHex() emitting uppercase (matching Rust JER).
            return val;
        }
        return val;
    }
}