// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: GetAllCBValuesResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetAllCBValues-ResponsePDU ::= SEQUENCE {
 *     cbValue          [0] IMPLICIT SEQUENCE OF SEQUENCE {
 *         reference     [0] IMPLICIT SubReference,
 *         value         [1] IMPLICIT CHOICE {
 *             brcb        [0] IMPLICIT BRCB,
 *             urcb        [1] IMPLICIT URCB,
 *             lcb         [2] IMPLICIT LCB,
 *             sgcb        [3] IMPLICIT SGCB,
 *             gocb        [4] IMPLICIT GoCB,
 *             msvcb       [5] IMPLICIT MSVCB
 *         }
 *     },
 *     moreFollows      [1] IMPLICIT Boolean DEFAULT 1
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetAllCBValuesResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetAllCBValuesResponsePDUCbValue cbValue = new InnerGetAllCBValuesResponsePDUCbValue();
    public InnerBoolean moreFollows = new InnerBoolean();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetAllCBValuesResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetAllCBValuesResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetAllCBValuesResponsePDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetAllCBValuesResponsePDU", DEFAULT_ENCODING, data), InnerGetAllCBValuesResponsePDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
