// Auto-generated by csasn1 v0.1.0: GetFileDirectoryResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetFileDirectory-ResponsePDU ::= SEQUENCE {
 *     fileEntry       [0] IMPLICIT SEQUENCE OF FileEntry,
 *     moreFollows     [1] IMPLICIT Boolean DEFAULT 1
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerGetFileDirectoryResponsePDU extends InnerBase {
    public InnerGetFileDirectoryResponsePDU() {
        _v.put("fileEntry", new java.util.ArrayList<>());
        _v.put("moreFollows", new InnerBoolean()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "GetFileDirectoryResponsePDU"; }
    public static InnerGetFileDirectoryResponsePDU decode(byte[] data) {
        return InnerBase.decode(InnerGetFileDirectoryResponsePDU.class, "GetFileDirectoryResponsePDU", data);
    }
}
