// Auto-generated by csasn1 v0.1.0 at 2026-07-28 09:11 UTC: AnonymousSetGoCBValuesErrorPDUResult
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * (inline type within SetGoCBValues-ErrorPDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerAnonymousSetGoCBValuesErrorPDUResult extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerServiceError error = new InnerServiceError();
    public InnerServiceError goEna = new InnerServiceError();
    public InnerServiceError goID = new InnerServiceError();
    public InnerServiceError datSet = new InnerServiceError();
    @com.fasterxml.jackson.annotation.JsonIgnore
    @lombok.EqualsAndHashCode.Exclude
    public transient java.util.Set<String> _set = new java.util.HashSet<>();
    public InnerAnonymousSetGoCBValuesErrorPDUResult error(InnerServiceError value) {
        this.error = value;
        this._set.add("error");
        return this;
    }
    public InnerAnonymousSetGoCBValuesErrorPDUResult goEna(InnerServiceError value) {
        this.goEna = value;
        this._set.add("goEna");
        return this;
    }
    public InnerAnonymousSetGoCBValuesErrorPDUResult goID(InnerServiceError value) {
        this.goID = value;
        this._set.add("goID");
        return this;
    }
    public InnerAnonymousSetGoCBValuesErrorPDUResult datSet(InnerServiceError value) {
        this.datSet = value;
        this._set.add("datSet");
        return this;
    }
    public byte[] encode() {
        try {
            com.fasterxml.jackson.databind.node.ObjectNode _root = MAPPER.valueToTree(this);
            if (!_set.contains("error")) _root.remove("error");
            if (!_set.contains("goEna")) _root.remove("goEna");
            if (!_set.contains("goID")) _root.remove("goID");
            if (!_set.contains("datSet")) _root.remove("datSet");
            String _json = MAPPER.writeValueAsString(_root);
            return InnerNative.encode("AnonymousSetGoCBValuesErrorPDUResult", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AnonymousSetGoCBValuesErrorPDUResult", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerAnonymousSetGoCBValuesErrorPDUResult decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("AnonymousSetGoCBValuesErrorPDUResult", DEFAULT_ENCODING, data), InnerAnonymousSetGoCBValuesErrorPDUResult.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
