// Auto-generated by csasn1 v0.1.0 at 2026-07-30 09:33 UTC: GetMSVCBValuesErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetMSVCBValues-ErrorPDU ::= ServiceError
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetMSVCBValuesErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetMSVCBValuesErrorPDU() { _v.put("_", 1); }
    @JsonCreator
    public static InnerGetMSVCBValuesErrorPDU fromJson(int v) { InnerGetMSVCBValuesErrorPDU r = new InnerGetMSVCBValuesErrorPDU(); r._v.put("_", v); return r; }
    public InnerGetMSVCBValuesErrorPDU(Integer v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("GetMSVCBValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetMSVCBValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public static InnerGetMSVCBValuesErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetMSVCBValuesErrorPDU", DEFAULT_ENCODING, data);
            InnerGetMSVCBValuesErrorPDU r = new InnerGetMSVCBValuesErrorPDU();
            r._v.put("_", MAPPER.readTree(json).asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
