// Auto-generated by csasn1 v0.1.0 at 2026-07-28 09:11 UTC: SetBRCBValuesRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * SetBRCBValues-RequestPDU ::= SEQUENCE {
 *     brcb            [0] IMPLICIT SEQUENCE OF SEQUENCE {
 *         reference   [0] IMPLICIT ObjectReference,
 *         rptID       [1] IMPLICIT VisibleString (SIZE (0..129)) OPTIONAL,
 *         rptEna      [2] IMPLICIT Boolean OPTIONAL,
 *         datSet      [3] IMPLICIT ObjectReference OPTIONAL,
 *         optFlds     [5] IMPLICIT RcbOptFlds OPTIONAL,
 *         bufTm       [6] IMPLICIT Int32U OPTIONAL,
 *         trgOps      [8] IMPLICIT TriggerConditions OPTIONAL,
 *         intgPd      [9] IMPLICIT Int32U OPTIONAL,
 *         gi          [10] IMPLICIT Boolean OPTIONAL,
 *         purgeBuf    [11] IMPLICIT Boolean OPTIONAL,
 *         entryID     [12] IMPLICIT EntryID OPTIONAL,
 *         resvTms     [13] IMPLICIT Int16 OPTIONAL
 *     }
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerSetBRCBValuesRequestPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerSetBRCBValuesRequestPDUBrcb brcb = new InnerSetBRCBValuesRequestPDUBrcb();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("SetBRCBValuesRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("SetBRCBValuesRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerSetBRCBValuesRequestPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("SetBRCBValuesRequestPDU", DEFAULT_ENCODING, data), InnerSetBRCBValuesRequestPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
