// Auto-generated by csasn1 v0.1.0 at 2026-07-23 14:23 UTC: Asdu
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * Asdu ::= SEQUENCE {
 *     reqId       Int16U
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerAsdu extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerInt16U reqId = new InnerInt16U();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("Asdu", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("Asdu", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerAsdu decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("Asdu", DEFAULT_ENCODING, data), InnerAsdu.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
