// Auto-generated by csasn1 v0.1.0: GetAllCBValuesRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetAllCBValues-RequestPDU ::= SEQUENCE {
 *     reference        [0] IMPLICIT CHOICE {
 *         ldName         [0] IMPLICIT ObjectName,
 *         lnReference    [1] IMPLICIT ObjectReference
 *     },
 *     acsiClass        [1] IMPLICIT ACSIClass,
 *     referenceAfter   [2] IMPLICIT ObjectReference OPTIONAL
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerGetAllCBValuesRequestPDU extends InnerBase {
    public InnerGetAllCBValuesRequestPDU() {
        _v.put("reference", new InnerGetAllCBValuesRequestPDUReference()._v);
        _v.put("acsiClass", new InnerACSIClass()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "GetAllCBValuesRequestPDU"; }
    public static InnerGetAllCBValuesRequestPDU decode(byte[] data) {
        return InnerBase.decode(InnerGetAllCBValuesRequestPDU.class, "GetAllCBValuesRequestPDU", data);
    }
}
