// Auto-generated by csasn1 v0.1.0 at 2026-07-28 04:52 UTC: Int64U
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * Int64U ::= INTEGER (0..18446744073709551615)
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerInt64U extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public Long value = 0L;
    public InnerInt64U() {}
    @JsonCreator
    public InnerInt64U(Long value) { this.value = value; }
    public byte[] encode() {
        return InnerNative.encode("Int64U", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("Int64U", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public static InnerInt64U decode(byte[] data) {
        try {
            String json = InnerNative.decode("Int64U", DEFAULT_ENCODING, data);
            InnerInt64U r = new InnerInt64U();
            r.value = MAPPER.readTree(json).get("value").asLong();
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
