// Auto-generated by csasn1 v0.1.0: GetAllCBValuesErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetAllCBValues-ErrorPDU ::= ServiceError
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetAllCBValuesErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetAllCBValuesErrorPDU() { _v.put("_", 1); }
    @JsonCreator
    public static InnerGetAllCBValuesErrorPDU fromJson(int v) { InnerGetAllCBValuesErrorPDU r = new InnerGetAllCBValuesErrorPDU(); r._v.put("_", v); return r; }
    public InnerGetAllCBValuesErrorPDU(Integer v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("GetAllCBValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetAllCBValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public static InnerGetAllCBValuesErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetAllCBValuesErrorPDU", DEFAULT_ENCODING, data);
            InnerGetAllCBValuesErrorPDU r = new InnerGetAllCBValuesErrorPDU();
            r._v.put("_", MAPPER.readTree(json).asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
