// Auto-generated by csasn1 v0.1.0 at 2026-07-29 05:47 UTC: CancelErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * Cancel-ErrorPDU ::= SEQUENCE {
 *     reference       [0] IMPLICIT ObjectReference,
 *     ctlVal          [1] IMPLICIT Data,
 *     operTm          [2] IMPLICIT TimeStamp OPTIONAL,
 *     origin          [3] IMPLICIT Originator,
 *     ctlNum          [4] IMPLICIT Int8U,
 *     t               [5] IMPLICIT TimeStamp,
 *     test            [6] IMPLICIT Boolean,
 *     addCause        [8] IMPLICIT AddCause
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerCancelErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerObjectReference reference = new InnerObjectReference();
    public InnerData ctlVal = new InnerData();
    public InnerTimeStamp operTm = new InnerTimeStamp();
    public InnerOriginator origin = new InnerOriginator();
    public InnerInt8U ctlNum = new InnerInt8U();
    public InnerTimeStamp t = new InnerTimeStamp();
    public InnerBoolean test = new InnerBoolean();
    public InnerAddCause addCause = new InnerAddCause();
    @com.fasterxml.jackson.annotation.JsonIgnore
    @lombok.EqualsAndHashCode.Exclude
    public transient java.util.Set<String> _set = new java.util.HashSet<>();
    public InnerCancelErrorPDU operTm(InnerTimeStamp value) {
        this.operTm = value;
        this._set.add("operTm");
        return this;
    }
    public byte[] encode() {
        try {
            com.fasterxml.jackson.databind.node.ObjectNode _root = MAPPER.valueToTree(this);
            if (!_set.contains("operTm")) _root.remove("operTm");
            String _json = MAPPER.writeValueAsString(_root);
            return InnerNative.encode("CancelErrorPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("CancelErrorPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerCancelErrorPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("CancelErrorPDU", DEFAULT_ENCODING, data), InnerCancelErrorPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
