// Auto-generated by csasn1 v0.1.0: Int24U
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * Int24U ::= INTEGER (0..16777215)
 * }</pre>
 */
public class InnerInt24U extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerInt24U() { _v.put("_", 0); }
    @JsonValue
    @Override
    public Object toJsonValue() { return Integer.toUnsignedLong((int) _v.get("_")); }
    public InnerInt24U(long v) { this(); _v.put("_", (int) v); }
    @JsonCreator
    public static InnerInt24U fromJson(long v) { return new InnerInt24U(v); }
    public byte[] encode() {
        return InnerNative.encode("Int24U", DEFAULT_ENCODING, String.valueOf(Integer.toUnsignedLong((int) _v.get("_"))));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("Int24U", DEFAULT_ENCODING, String.valueOf(Integer.toUnsignedLong((int) _v.get("_"))));
    }
    public static InnerInt24U decode(byte[] data) {
        try {
            String json = InnerNative.decode("Int24U", DEFAULT_ENCODING, data);
            InnerInt24U r = new InnerInt24U();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", _node.asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
