// Auto-generated by csasn1 v0.1.0: GetLogStatusValuesResponsePDULog
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

public class InnerGetLogStatusValuesResponsePDULog extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetLogStatusValuesResponsePDULog() { _v.put("_", new java.util.ArrayList<>()); }
    @JsonCreator
    public static InnerGetLogStatusValuesResponsePDULog fromJson(Object v) { InnerGetLogStatusValuesResponsePDULog r = new InnerGetLogStatusValuesResponsePDULog(); r._v.put("_", MAPPER.convertValue(v, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetLogStatusValuesResponsePDULog>>() {})); return r; }
    public InnerGetLogStatusValuesResponsePDULog(java.util.List<InnerAnonymousGetLogStatusValuesResponsePDULog> v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        try {
            return InnerNative.encode("GetLogStatusValuesResponsePDULog", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("GetLogStatusValuesResponsePDULog", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.toJson(_v.get("_"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetLogStatusValuesResponsePDULog decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetLogStatusValuesResponsePDULog", DEFAULT_ENCODING, data);
            InnerGetLogStatusValuesResponsePDULog r = new InnerGetLogStatusValuesResponsePDULog();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", MAPPER.convertValue(_node, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetLogStatusValuesResponsePDULog>>() {}));
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
