// Auto-generated by csasn1 v0.1.0: AnonymousReportPDUEntryEntryData
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * (inline type within ReportPDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerAnonymousReportPDUEntryEntryData extends InnerBase {
    public InnerAnonymousReportPDUEntryEntryData() {
        _v.put("id", new InnerInt16U()._v);
        _v.put("value", new InnerData()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "AnonymousReportPDUEntryEntryData"; }
    public static InnerAnonymousReportPDUEntryEntryData decode(byte[] data) {
        return InnerBase.decode(InnerAnonymousReportPDUEntryEntryData.class, "AnonymousReportPDUEntryEntryData", data);
    }
}
