// Auto-generated by csasn1 v0.1.0 at 2026-07-28 04:52 UTC: GetGoCbValuesErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetGoCbValues-ErrorPDU ::= ServiceError
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetGoCbValuesErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public Integer value = 0;
    public InnerGetGoCbValuesErrorPDU() {}
    @JsonCreator
    public InnerGetGoCbValuesErrorPDU(Integer value) { this.value = value; }
    public byte[] encode() {
        return InnerNative.encode("GetGoCbValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetGoCbValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(this.value));
    }
    public static InnerGetGoCbValuesErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetGoCbValuesErrorPDU", DEFAULT_ENCODING, data);
            InnerGetGoCbValuesErrorPDU r = new InnerGetGoCbValuesErrorPDU();
            r.value = MAPPER.readTree(json).get("value").asInt();
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
