// Auto-generated by csasn1 v0.1.0 at 2026-07-31 00:52 UTC: SetFileErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * SetFile-ErrorPDU ::= ServiceError
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerSetFileErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerSetFileErrorPDU() { _v.put("_", 1); }
    @JsonCreator
    public static InnerSetFileErrorPDU fromJson(int v) { InnerSetFileErrorPDU r = new InnerSetFileErrorPDU(); r._v.put("_", v); return r; }
    public InnerSetFileErrorPDU(Integer v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("SetFileErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("SetFileErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public static InnerSetFileErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("SetFileErrorPDU", DEFAULT_ENCODING, data);
            InnerSetFileErrorPDU r = new InnerSetFileErrorPDU();
            r._v.put("_", MAPPER.readTree(json).asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
