// Auto-generated by csasn1 v0.1.0: GetGOOSEElementNumberErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetGOOSEElementNumber-ErrorPDU ::= ServiceError
 * }</pre>
 */
public class InnerGetGOOSEElementNumberErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.MAPPER;
    public InnerGetGOOSEElementNumberErrorPDU() { _v.put("_", 1); }
    @JsonCreator
    public static InnerGetGOOSEElementNumberErrorPDU fromJson(int v) { InnerGetGOOSEElementNumberErrorPDU r = new InnerGetGOOSEElementNumberErrorPDU(); r._v.put("_", v); return r; }
    public InnerGetGOOSEElementNumberErrorPDU(Integer v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("GetGOOSEElementNumberErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetGOOSEElementNumberErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public static InnerGetGOOSEElementNumberErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetGOOSEElementNumberErrorPDU", DEFAULT_ENCODING, data);
            InnerGetGOOSEElementNumberErrorPDU r = new InnerGetGOOSEElementNumberErrorPDU();
            com.fasterxml.jackson.databind.JsonNode _node = MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", _node.asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
