// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: AssociateRequestPDUAuthenticationParameter
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerAssociateRequestPDUAuthenticationParameter extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public byte[] signatureCertificate = new byte[0];
    public InnerUtcTime signedTime = new InnerUtcTime();
    public byte[] signedValue = new byte[0];
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AssociateRequestPDUAuthenticationParameter", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("AssociateRequestPDUAuthenticationParameter", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerAssociateRequestPDUAuthenticationParameter decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("AssociateRequestPDUAuthenticationParameter", DEFAULT_ENCODING, data), InnerAssociateRequestPDUAuthenticationParameter.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
