// Auto-generated by csasn1 v0.1.0 at 2026-07-24 09:04 UTC: GetGoReferenceResponsePDUMemberData
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetGoReferenceResponsePDUMemberData extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public java.util.List<InnerAnonymousGetGoReferenceResponsePDUMemberData> value = new java.util.ArrayList<>();
    public InnerGetGoReferenceResponsePDUMemberData() {}
    @JsonCreator
    public InnerGetGoReferenceResponsePDUMemberData(java.util.List<InnerAnonymousGetGoReferenceResponsePDUMemberData> value) { this.value = value; }
    public byte[] encode() {
        try {
            return InnerNative.encode("GetGoReferenceResponsePDUMemberData", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("GetGoReferenceResponsePDUMemberData", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetGoReferenceResponsePDUMemberData decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetGoReferenceResponsePDUMemberData", DEFAULT_ENCODING, data);
            InnerGetGoReferenceResponsePDUMemberData r = new InnerGetGoReferenceResponsePDUMemberData();
            r.value = MAPPER.convertValue(MAPPER.readTree(json).get("value"), new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetGoReferenceResponsePDUMemberData>>() {});
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
