// Auto-generated by csasn1 v0.1.0: SetBRCBValuesRequestPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * SetBRCBValues-RequestPDU ::= SEQUENCE {
 *     brcb            [0] IMPLICIT SEQUENCE OF SEQUENCE {
 *         reference   [0] IMPLICIT ObjectReference,
 *         rptID       [1] IMPLICIT VisibleString (SIZE (0..129)) OPTIONAL,
 *         rptEna      [2] IMPLICIT Boolean OPTIONAL,
 *         datSet      [3] IMPLICIT ObjectReference OPTIONAL,
 *         optFlds     [5] IMPLICIT RcbOptFlds OPTIONAL,
 *         bufTm       [6] IMPLICIT Int32U OPTIONAL,
 *         trgOps      [8] IMPLICIT TriggerConditions OPTIONAL,
 *         intgPd      [9] IMPLICIT Int32U OPTIONAL,
 *         gi          [10] IMPLICIT Boolean OPTIONAL,
 *         purgeBuf    [11] IMPLICIT Boolean OPTIONAL,
 *         entryID     [12] IMPLICIT EntryID OPTIONAL,
 *         resvTms     [13] IMPLICIT Int16 OPTIONAL
 *     }
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerSetBRCBValuesRequestPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.MAPPER;
    public InnerSetBRCBValuesRequestPDU() {
        _v.put("brcb", new InnerSetBRCBValuesRequestPDUBrcb()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    public byte[] encode() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            return InnerNative.encode("SetBRCBValuesRequestPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encode SetBRCBValuesRequestPDU failed, json=" + _json, e);
        }
    }
    public byte[] encodeTest() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            System.err.println("JSON: " + _json);
            return new byte[0];
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerSetBRCBValuesRequestPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("SetBRCBValuesRequestPDU", DEFAULT_ENCODING, data), InnerSetBRCBValuesRequestPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
