// Auto-generated by csasn1 v0.1.0: GetDataDirectoryResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetDataDirectory-ResponsePDU ::= SEQUENCE {
 *     dataAttribute    [0] IMPLICIT SEQUENCE OF SEQUENCE {
 *         reference     [0] IMPLICIT SubReference,
 *         fc            [1] IMPLICIT FunctionalConstraint OPTIONAL
 *     },
 *     moreFollows      [1] IMPLICIT Boolean DEFAULT 1
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerGetDataDirectoryResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetDataDirectoryResponsePDU() {
        _v.put("dataAttribute", new InnerGetDataDirectoryResponsePDUDataAttribute()._v);
        _v.put("moreFollows", new InnerBoolean()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    public byte[] encode() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            return InnerNative.encode("GetDataDirectoryResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encode GetDataDirectoryResponsePDU failed, json=" + _json, e);
        }
    }
    public byte[] encodeTest() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            System.err.println("JSON: " + _json);
            return new byte[0];
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetDataDirectoryResponsePDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetDataDirectoryResponsePDU", DEFAULT_ENCODING, data), InnerGetDataDirectoryResponsePDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
