// Auto-generated by csasn1 v0.1.0 at 2026-07-23 14:23 UTC: GetMSVCBValuesResponsePDUMsvcb
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetMSVCBValuesResponsePDUMsvcb extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    @JsonValue public java.util.List<InnerAnonymousGetMSVCBValuesResponsePDUMsvcb> value = new java.util.ArrayList<>();
    public InnerGetMSVCBValuesResponsePDUMsvcb() {}
    @JsonCreator
    public InnerGetMSVCBValuesResponsePDUMsvcb(java.util.List<InnerAnonymousGetMSVCBValuesResponsePDUMsvcb> value) { this.value = value; }
    public byte[] encode() {
        try {
            return InnerNative.encode("GetMSVCBValuesResponsePDUMsvcb", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("GetMSVCBValuesResponsePDUMsvcb", DEFAULT_ENCODING, MAPPER.writeValueAsString(this.value));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetMSVCBValuesResponsePDUMsvcb decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetMSVCBValuesResponsePDUMsvcb", DEFAULT_ENCODING, data);
            InnerGetMSVCBValuesResponsePDUMsvcb r = new InnerGetMSVCBValuesResponsePDUMsvcb();
            r.value = MAPPER.convertValue(MAPPER.readTree(json).get("value"), new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InnerAnonymousGetMSVCBValuesResponsePDUMsvcb>>() {});
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
