// Auto-generated by csasn1 v0.1.0: AnonymousGetAllDataValuesResponsePDUData
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * (inline type within GetAllDataValues-ResponsePDU ::= SEQUENCE {)
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerAnonymousGetAllDataValuesResponsePDUData extends InnerBase {
    public InnerAnonymousGetAllDataValuesResponsePDUData() {
        _v.put("reference", new InnerSubReference()._v);
        _v.put("value", new InnerData()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "AnonymousGetAllDataValuesResponsePDUData"; }
    public static InnerAnonymousGetAllDataValuesResponsePDUData decode(byte[] data) {
        return InnerBase.decode(InnerAnonymousGetAllDataValuesResponsePDUData.class, "AnonymousGetAllDataValuesResponsePDUData", data);
    }
}
