// Auto-generated by csasn1 v0.1.0 at 2026-07-24 01:13 UTC: GetAllDataDefinitionResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetAllDataDefinition-ResponsePDU ::= SEQUENCE {
 *     data             [0] IMPLICIT SEQUENCE OF SEQUENCE {
 *         reference     [0] IMPLICIT SubReference,
 *         cdcType       [1] IMPLICIT VisibleString OPTIONAL,
 *         definition    [2] IMPLICIT DataDefinition
 *     },
 *     moreFollows      [1] IMPLICIT Boolean DEFAULT 1
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetAllDataDefinitionResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetAllDataDefinitionResponsePDUData data = new InnerGetAllDataDefinitionResponsePDUData();
    public InnerBoolean moreFollows = new InnerBoolean();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetAllDataDefinitionResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetAllDataDefinitionResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetAllDataDefinitionResponsePDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetAllDataDefinitionResponsePDU", DEFAULT_ENCODING, data), InnerGetAllDataDefinitionResponsePDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
