// Auto-generated by csasn1 v0.1.0 at 2026-07-28 03:54 UTC: GetDataDirectoryResponsePDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * GetDataDirectory-ResponsePDU ::= SEQUENCE {
 *     dataAttribute    [0] IMPLICIT SEQUENCE OF SEQUENCE {
 *         reference     [0] IMPLICIT SubReference,
 *         fc            [1] IMPLICIT FunctionalConstraint OPTIONAL
 *     },
 *     moreFollows      [1] IMPLICIT Boolean DEFAULT 1
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerGetDataDirectoryResponsePDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerGetDataDirectoryResponsePDUDataAttribute dataAttribute = new InnerGetDataDirectoryResponsePDUDataAttribute();
    public InnerBoolean moreFollows = new InnerBoolean();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetDataDirectoryResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("GetDataDirectoryResponsePDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerGetDataDirectoryResponsePDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("GetDataDirectoryResponsePDU", DEFAULT_ENCODING, data), InnerGetDataDirectoryResponsePDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
