// Auto-generated by csasn1 v0.1.0: AssociateResponsePDUAuthenticationParameter
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerAssociateResponsePDUAuthenticationParameter extends InnerBase {
    public InnerAssociateResponsePDUAuthenticationParameter() {
        _v.put("signatureCertificate", new DefaultInnerOctetString(new byte[]{ 1 }));
        _v.put("signedTime", new InnerUtcTime()._v);
        _v.put("signedValue", new DefaultInnerOctetString(new byte[]{ 1 }));
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    @Override
    protected String typeName() { return "AssociateResponsePDUAuthenticationParameter"; }
    public static InnerAssociateResponsePDUAuthenticationParameter decode(byte[] data) {
        return InnerBase.decode(InnerAssociateResponsePDUAuthenticationParameter.class, "AssociateResponsePDUAuthenticationParameter", data);
    }
}
