// Auto-generated by csasn1 v0.1.0 at 2026-07-28 03:54 UTC: MsvcbOptFlds
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * MsvcbOptFlds ::= BIT STRING {
 *     refresh-time                (0),
 *     reserved                    (1),
 *     sample-rate                 (2),
 *     data-set-name               (3),
 *     security                    (4)
 * } (SIZE(5))
 * }</pre>
 */
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerMsvcbOptFlds extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public Integer value = 0;
    public InnerMsvcbOptFlds() {}
    public InnerMsvcbOptFlds(Integer value) { this.value = value; }
    @JsonValue
    public String toJsonValue() { return InnerBase.bitStringHex(this.value, 5); }
    @JsonCreator
    public InnerMsvcbOptFlds(String hex) { this.value = InnerBase.parseBitStringHex(hex, 5); }
    public byte[] encode() {
        try {
            return InnerNative.encode("MsvcbOptFlds", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.bitStringHex(this.value, 5)));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            return InnerNative.encode("MsvcbOptFlds", DEFAULT_ENCODING, MAPPER.writeValueAsString(InnerBase.bitStringHex(this.value, 5)));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerMsvcbOptFlds decode(byte[] data) {
        try {
            String json = InnerNative.decode("MsvcbOptFlds", DEFAULT_ENCODING, data);
            InnerMsvcbOptFlds r = new InnerMsvcbOptFlds();
            r.value = InnerBase.parseBitStringHex(MAPPER.readTree(json).get("value").asText(), 5);
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
