// Auto-generated by csasn1 v0.1.0: ReportPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * ReportPDU ::= SEQUENCE {
 *     rptID           [0] IMPLICIT VisibleString (SIZE (0..129)),
 *     optFlds         [1] IMPLICIT RcbOptFlds,
 *     sqNum           [2] IMPLICIT Int16U OPTIONAL,
 *     subSeqNum       [3] IMPLICIT Int16U OPTIONAL,
 *     moreSegmentsFollow [4] IMPLICIT Boolean OPTIONAL,
 *     dataSet         [5] IMPLICIT ObjectReference OPTIONAL,
 *     bufOvfl         [6] IMPLICIT Boolean OPTIONAL,
 *     confRev         [7] IMPLICIT Int32U OPTIONAL,
 *     entry           [8] IMPLICIT SEQUENCE {
 *         timeOfEntry     [0] IMPLICIT EntryTime OPTIONAL,
 *         entryID         [1] IMPLICIT EntryID OPTIONAL,
 *         entryData       [2] IMPLICIT SEQUENCE OF SEQUENCE {
 *             reference   [0] IMPLICIT ObjectReference OPTIONAL,
 *             fc          [1] IMPLICIT FunctionalConstraint OPTIONAL,
 *             id          [2] IMPLICIT Int16U,
 *             value       [3] IMPLICIT Data,
 *             reason      [4] IMPLICIT ReasonCode OPTIONAL
 *         }
 *     }
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InnerReportPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerReportPDU() {
        _v.put("rptID", new DefaultInnerVisibleString("x"));
        _v.put("optFlds", new InnerRcbOptFlds()._v);
        _v.put("entry", new InnerReportPDUEntry()._v);
    }
    @JsonAnySetter
    public void setField(String key, Object value) {
        if (key.startsWith("_")) return;
        _v.put(key, value);
    }
    public byte[] encode() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            return InnerNative.encode("ReportPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException("encode ReportPDU failed, json=" + _json, e);
        }
    }
    public byte[] encodeTest() {
        String _json = null;
        try {
            _json = MAPPER.writeValueAsString(InnerBase.toJson(_v));
            System.err.println("JSON: " + _json);
            return new byte[0];
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerReportPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("ReportPDU", DEFAULT_ENCODING, data), InnerReportPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
