// Auto-generated by csasn1 v0.1.0 at 2026-07-30 09:33 UTC: InnerNative (JNA bridge)
// All native functions return JSON strings; binary data is base64-encoded.

package com.ysh.jcms.data;

import com.sun.jna.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Map;

public class InnerNative {
    private static final NativeImpl LIB = Native.load("asn1", NativeImpl.class,
        java.util.Collections.singletonMap(Library.OPTION_STRING_ENCODING, "UTF-8"));
    private static final ObjectMapper MAPPER = new ObjectMapper();

    private interface NativeImpl extends Library {
        Pointer csasn1_ping();
        Pointer csasn1_encode(String typeName, String encoding, String json);
        Pointer csasn1_decode(String typeName, String encoding, byte[] data, int len);
        void csasn1_free_string(Pointer s);
    }

    /** Quick check that native library loads and responds. */
    public static String ping() {
        Pointer p = LIB.csasn1_ping();
        try {
            return p.getString(0, "UTF-8");
        } finally {
            LIB.csasn1_free_string(p);
        }
    }

    /** Read a null-terminated C string from a Pointer and free it. */
    private static String readAndFree(Pointer p) {
        try {
            return p.getString(0, "UTF-8");
        } finally {
            LIB.csasn1_free_string(p);
        }
    }

    /**
     * Encode JSON to ASN.1 binary.
     * @param typeName  ASN.1 type name
     * @param encoding  encoding rule ("ber", "der", "aper", "uper")
     * @param json      JSON representation of the data
     * @return encoded binary data
     */
    public static byte[] encode(String typeName, String encoding, String json) {
        try {
            String resp = readAndFree(LIB.csasn1_encode(typeName, encoding, json));
            @SuppressWarnings("unchecked")
            Map<String, Object> m = MAPPER.readValue(resp, Map.class);
            if (Boolean.TRUE.equals(m.get("ok"))) {
                return MAPPER.convertValue(m.get("bytes"), byte[].class);
            }
            throw new RuntimeException("encode failed: " + m.get("error"));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Decode ASN.1 binary to JSON.
     * @param typeName  ASN.1 type name
     * @param encoding  encoding rule
     * @param data      binary encoded data
     * @return JSON representation (with 0x prefixes stripped from hex strings)
     */
    public static String decode(String typeName, String encoding, byte[] data) {
        try {
            String resp = readAndFree(LIB.csasn1_decode(typeName, encoding, data, data.length));
            @SuppressWarnings("unchecked")
            Map<String, Object> m = MAPPER.readValue(resp, Map.class);
            if (Boolean.TRUE.equals(m.get("ok"))) {
                String json = MAPPER.writeValueAsString(m.get("value"));
                // Strip 0x prefixes from hex strings (rasn JER uses {:02X?} format)
                json = json.replace("0x", "").replace("0X", "");
                return json;
            }
            throw new RuntimeException("decode failed: " + m.get("error"));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}