// Auto-generated by csasn1 v0.1.0: GetBRCBValuesErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;

/**
 * <pre>{@code
 * GetBRCBValues-ErrorPDU ::= ServiceError
 * }</pre>
 */
public class InnerGetBRCBValuesErrorPDU extends InnerBase {
    public InnerGetBRCBValuesErrorPDU() { _v.put("_", 1); }
    @JsonCreator
    public static InnerGetBRCBValuesErrorPDU fromJson(int v) { InnerGetBRCBValuesErrorPDU r = new InnerGetBRCBValuesErrorPDU(); r._v.put("_", v); return r; }
    public InnerGetBRCBValuesErrorPDU(Integer v) { this(); _v.put("_", v); }
    @JsonValue
    public Object toJsonValue() { return _v.get("_"); }
    public byte[] encode() {
        return InnerNative.encode("GetBRCBValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public byte[] encodeTest() {
        return InnerNative.encode("GetBRCBValuesErrorPDU", DEFAULT_ENCODING, String.valueOf(_v.get("_")));
    }
    public static InnerGetBRCBValuesErrorPDU decode(byte[] data) {
        try {
            String json = InnerNative.decode("GetBRCBValuesErrorPDU", DEFAULT_ENCODING, data);
            InnerGetBRCBValuesErrorPDU r = new InnerGetBRCBValuesErrorPDU();
            com.fasterxml.jackson.databind.JsonNode _node = InnerBase.MAPPER.readTree(json);
            if (_node.isObject() && _node.has("value")) _node = _node.get("value");
            r._v.put("_", _node.asInt());
            return r;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
