// Auto-generated by csasn1 v0.1.0 at 2026-07-28 04:52 UTC: SetBRCBValuesErrorPDU
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * SetBRCBValues-ErrorPDU ::= SEQUENCE {
 *     result          [0] IMPLICIT SEQUENCE OF SEQUENCE {
 *         error       [0] IMPLICIT ServiceError OPTIONAL,
 *         rptID       [1] IMPLICIT ServiceError OPTIONAL,
 *         rptEna      [2] IMPLICIT ServiceError OPTIONAL,
 *         datSet      [3] IMPLICIT ServiceError OPTIONAL,
 *         optFlds     [5] IMPLICIT ServiceError OPTIONAL,
 *         bufTm       [6] IMPLICIT ServiceError OPTIONAL,
 *         trgOps      [8] IMPLICIT ServiceError OPTIONAL,
 *         intgPd      [9] IMPLICIT ServiceError OPTIONAL,
 *         gi          [10] IMPLICIT ServiceError OPTIONAL,
 *         purgeBuf    [11] IMPLICIT ServiceError OPTIONAL,
 *         entryID     [12] IMPLICIT ServiceError OPTIONAL,
 *         resvTms     [14] IMPLICIT ServiceError OPTIONAL
 *     }
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerSetBRCBValuesErrorPDU extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public InnerSetBRCBValuesErrorPDUResult result = new InnerSetBRCBValuesErrorPDUResult();
    public byte[] encode() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("SetBRCBValuesErrorPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("SetBRCBValuesErrorPDU", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerSetBRCBValuesErrorPDU decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("SetBRCBValuesErrorPDU", DEFAULT_ENCODING, data), InnerSetBRCBValuesErrorPDU.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
