// Auto-generated by csasn1 v0.1.0 at 2026-07-29 05:47 UTC: URCB
//

package com.ysh.jcms.data;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import lombok.Data;

/**
 * <pre>{@code
 * URCB ::= SEQUENCE {
 *     rptID           [1] IMPLICIT VisibleString (SIZE (0..129)),
 *     rptEna          [2] IMPLICIT Boolean,
 *     datSet          [3] IMPLICIT ObjectReference,
 *     confRev         [4] IMPLICIT Int32U,
 *     optFlds         [5] IMPLICIT RcbOptFlds,
 *     bufTm           [6] IMPLICIT Int32U,
 *     sqNum           [7] IMPLICIT Int16U,
 *     trgOps          [8] IMPLICIT TriggerConditions,
 *     intgPd          [9] IMPLICIT Int32U,
 *     gi              [10] IMPLICIT Boolean,
 *     resv            [14] IMPLICIT Boolean,
 *     owner           [15] IMPLICIT OCTET STRING (SIZE (0..64)) OPTIONAL
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@lombok.experimental.Accessors(chain = true, fluent = true)
public class InnerURCB extends InnerBase {
    private static final ObjectMapper MAPPER = InnerBase.createMapper();
    public DefaultInnerVisibleString rptID = new DefaultInnerVisibleString();
    public InnerBoolean rptEna = new InnerBoolean();
    public InnerObjectReference datSet = new InnerObjectReference();
    public InnerInt32U confRev = new InnerInt32U();
    public InnerRcbOptFlds optFlds = new InnerRcbOptFlds();
    public InnerInt32U bufTm = new InnerInt32U();
    public InnerInt16U sqNum = new InnerInt16U();
    public InnerTriggerConditions trgOps = new InnerTriggerConditions();
    public InnerInt32U intgPd = new InnerInt32U();
    public InnerBoolean gi = new InnerBoolean();
    public InnerBoolean resv = new InnerBoolean();
    public DefaultInnerOctetString owner = new DefaultInnerOctetString();
    @com.fasterxml.jackson.annotation.JsonIgnore
    @lombok.EqualsAndHashCode.Exclude
    public transient java.util.Set<String> _set = new java.util.HashSet<>();
    public InnerURCB owner(DefaultInnerOctetString value) {
        this.owner = value;
        this._set.add("owner");
        return this;
    }
    public byte[] encode() {
        try {
            com.fasterxml.jackson.databind.node.ObjectNode _root = MAPPER.valueToTree(this);
            if (!_set.contains("owner")) _root.remove("owner");
            String _json = MAPPER.writeValueAsString(_root);
            return InnerNative.encode("URCB", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public byte[] encodeTest() {
        try {
            String _json = MAPPER.writeValueAsString(this);
            return InnerNative.encode("URCB", DEFAULT_ENCODING, _json);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    public static InnerURCB decode(byte[] data) {
        try {
            return MAPPER.readValue(InnerNative.decode("URCB", DEFAULT_ENCODING, data), InnerURCB.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
